// Date: 2/10/2013 4:02:23 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelNew extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape1;
    ModelRenderer Shape1;
    ModelRenderer Shape1;
    ModelRenderer Shape1;
    ModelRenderer Shape1;
    ModelRenderer Shape1;
    ModelRenderer Shape1;
    ModelRenderer Shape1;
    ModelRenderer Shape1;
    ModelRenderer Shape1;
    ModelRenderer Shape1;
    ModelRenderer Shape1;
    ModelRenderer Shape1;
    ModelRenderer Shape1;
    ModelRenderer Shape1;
    ModelRenderer Shape1;
    ModelRenderer Shape1;
    ModelRenderer Shape1;
    ModelRenderer Shape1;
    ModelRenderer Shape1;
    ModelRenderer Shape1;
    ModelRenderer Shape1;
    ModelRenderer Shape1;
    ModelRenderer Shape1;
  
  public ModelNew()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Shape1 = new ModelRenderer(this, 41, 0);
      Shape1.addBox(-4F, 5.8F, -4F, 8, 1, 8);
      Shape1.setRotationPoint(0F, 17.2F, 2F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(-5F, 0F, -5F, 10, 6, 10);
      Shape1.setRotationPoint(0F, 17.2F, 2F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 0, 49);
      Shape1.addBox(-4.5F, 4.5F, -4.5F, 9, 2, 9);
      Shape1.setRotationPoint(0F, 17.2F, 2F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 41, 17);
      Shape1.addBox(-4F, -3.4F, -4F, 8, 2, 8);
      Shape1.setRotationPoint(0F, 17.2F, 2F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 0, 17);
      Shape1.addBox(-5.5F, 0.5F, -4.5F, 11, 5, 9);
      Shape1.setRotationPoint(0F, 17.2F, 2F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 0, 32);
      Shape1.addBox(-4.5F, 0.5F, -5.5F, 9, 5, 11);
      Shape1.setRotationPoint(0F, 17.2F, 2F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 41, 10);
      Shape1.addBox(-2F, -1.4F, -2F, 4, 2, 4);
      Shape1.setRotationPoint(0F, 17.2F, 2F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 52, 57);
      Shape1.addBox(-2.5F, -8F, -2.5F, 5, 1, 5);
      Shape1.setRotationPoint(0F, 17.2F, 2F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 37, 49);
      Shape1.addBox(2.1F, -9F, -3F, 1, 2, 6);
      Shape1.setRotationPoint(0F, 17.2F, 2F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 41, 37);
      Shape1.addBox(-6.4F, -4.7F, -3.5F, 2, 0, 7);
      Shape1.setRotationPoint(0F, 17.2F, 2F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 1.343904F);
      Shape1 = new ModelRenderer(this, 41, 28);
      Shape1.addBox(-4.4F, -4.7F, -4F, 2, 0, 8);
      Shape1.setRotationPoint(0F, 17.2F, 2F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 1.343904F);
      Shape1 = new ModelRenderer(this, 55, 49);
      Shape1.addBox(-3F, -9F, 2.1F, 6, 2, 1);
      Shape1.setRotationPoint(0F, 17.2F, 2F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 58, 10);
      Shape1.addBox(-4F, -4.7F, -4.4F, 8, 0, 2);
      Shape1.setRotationPoint(0F, 17.2F, 2F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, -1.343904F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 60, 45);
      Shape1.addBox(-3.5F, -4.7F, -6.4F, 7, 0, 2);
      Shape1.setRotationPoint(0F, 17.2F, 2F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, -1.343904F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 55, 53);
      Shape1.addBox(-3F, -9F, -3.1F, 6, 2, 1);
      Shape1.setRotationPoint(0F, 17.2F, 2F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 58, 14);
      Shape1.addBox(-4F, -4.7F, 2.4F, 8, 0, 2);
      Shape1.setRotationPoint(0F, 17.2F, 2F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 1.343904F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 41, 45);
      Shape1.addBox(-3.5F, -4.7F, 4.4F, 7, 0, 2);
      Shape1.setRotationPoint(0F, 17.2F, 2F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 1.343904F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 73, 49);
      Shape1.addBox(-3.1F, -9F, -3F, 1, 2, 6);
      Shape1.setRotationPoint(0F, 17.2F, 2F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 62, 28);
      Shape1.addBox(2.4F, -4.7F, -4F, 2, 0, 8);
      Shape1.setRotationPoint(0F, 17.2F, 2F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, -1.343904F);
      Shape1 = new ModelRenderer(this, 60, 37);
      Shape1.addBox(4.4F, -4.7F, -3.5F, 2, 0, 7);
      Shape1.setRotationPoint(0F, 17.2F, 2F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, -1.343904F);
      Shape1 = new ModelRenderer(this, 79, 13);
      Shape1.addBox(-2.5F, 5.4F, -3F, 2, 1, 1);
      Shape1.setRotationPoint(0F, 17.2F, 2F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, -0.9424778F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 86, 13);
      Shape1.addBox(-2.5F, 7.1F, -3.2F, 2, 1, 1);
      Shape1.setRotationPoint(0F, 17.2F, 2F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, -0.9424778F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 74, 0);
      Shape1.addBox(-3.5F, 2.9F, -8.7F, 7, 3, 4);
      Shape1.setRotationPoint(0F, 17.2F, 2F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape1.mirror = true;
      Shape1 = new ModelRenderer(this, 74, 17);
      Shape1.addBox(-3.5F, 4.7F, -2.8F, 7, 4, 2);
      Shape1.setRotationPoint(0F, 17.2F, 2F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, -0.9424778F, 0F, 0F);
      Shape1.mirror = false;
      Shape1 = new ModelRenderer(this, 79, 9);
      Shape1.addBox(0.7F, 5.7F, -3.2F, 2, 2, 1);
      Shape1.setRotationPoint(0F, 17.2F, 2F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, -0.9424778F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Shape1.render(f5);
    Shape1.render(f5);
    Shape1.render(f5);
    Shape1.render(f5);
    Shape1.render(f5);
    Shape1.render(f5);
    Shape1.render(f5);
    Shape1.render(f5);
    Shape1.render(f5);
    Shape1.render(f5);
    Shape1.render(f5);
    Shape1.render(f5);
    Shape1.render(f5);
    Shape1.render(f5);
    Shape1.render(f5);
    Shape1.render(f5);
    Shape1.render(f5);
    Shape1.render(f5);
    Shape1.render(f5);
    Shape1.render(f5);
    Shape1.render(f5);
    Shape1.render(f5);
    Shape1.render(f5);
    Shape1.render(f5);
    Shape1.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
