package pixelmon.config;


import cpw.mods.fml.common.registry.EntityRegistry;
import net.minecraftforge.common.Configuration;

public class IDListPixelmon {
	public static int abraId;
	public static int arbokId;
	public static int blastoiseId;
	public static int bulbasaurId;
	public static int butterfreeId;
	public static int caterpieId;
	public static int charizardId;
	public static int charmanderId;
	public static int charmeleonId;
	public static int cuboneId;
	public static int diglettId;
	public static int dugtrioId;
	public static int eeveeId;
	public static int ekansId;
	public static int electrodeId;
	public static int flareonId;
	public static int gastlyId;
	public static int geodudeId;
	public static int goldeenId;
	public static int growlitheId;
	public static int gyaradosId;
	public static int horseaId;
	public static int ivysaurId;
	public static int jigglypuffId;
	public static int jolteonId;
	public static int magikarpId;
	public static int magnemiteId;
	public static int mankeyId;
	public static int mewId;
	public static int metapodId;
	public static int miltankId;
	public static int ninetalesId;
	public static int oddishId;
	public static int omanyteId;
	public static int omastarId;
	public static int pidgeyId;
	public static int pidgeottoId;
	public static int pidgeotId;
	public static int pikachuId;
	public static int psyduckId;
	public static int rattataId;
	public static int seakingId;
	public static int snorlaxId;
	public static int sandileId;
	public static int staryuId;
	public static int starmieId;
	public static int krokorokId;
	public static int squirtleId;
	public static int shellderId;
	public static int trapinchId;
	public static int venusaurId;
	public static int voltorbId;
	public static int vulpixId;
	public static int wartortleId;
	public static int wigglytuffId;
	public static int zubatId;
	public static int dratiniId;
	public static int vibravaId;
	public static int magnetonId;
	public static int mareepId;
	public static int solrockId;
	public static int lunatoneId;
	public static int tentacoolId;
	public static int nidoranMaleId;
	public static int vaporeonId;
	public static int gloomId;
	public static int krabbyId;
	public static int weedleId;
	public static int kakunaId;
	public static int koffingId;
	public static int weezingId;
	public static int primeapeId;
	public static int arcanineId;
	public static int parasId;
	public static int golbatId;
	public static int drowzeeId;
	public static int numelId;
	public static int cameruptId;
	public static int scytherId;
	public static int flygonId;
	
	public static int i=0;
	public static void load(Configuration configuration) {
		abraId = i++;
		arbokId = i++;
		blastoiseId = i++;
		bulbasaurId = i++;
		butterfreeId = i++;
		caterpieId = i++;
		charizardId = i++;
		charmanderId = i++;
		charmeleonId = i++;
		cuboneId = i++;
		diglettId = i++;
		dugtrioId = i++;
		eeveeId = i++;
		ekansId = i++;
		flareonId = i++;
		gastlyId = i++;
		geodudeId = i++;
		goldeenId = i++;
		growlitheId = i++;
		gyaradosId = i++;
		horseaId = i++;
		ivysaurId = i++;
		jigglypuffId = i++;
		jolteonId = i++;
		sandileId = i++;
		krokorokId = i++;
		magikarpId = i++;
		magnemiteId = i++;
		mankeyId = i++;
		metapodId = i++;
		mewId = i++;
		miltankId = i++;
		pidgeyId = i++;
		pikachuId = i++;
		pidgeottoId = i++;
		pidgeotId = i++;
		ninetalesId = i++;
		oddishId = i++;
		omanyteId = i++;
		omastarId = i++;
		psyduckId = i++;
		rattataId = i++;
		seakingId = i++;
		shellderId = i++;
		snorlaxId = i++;
		squirtleId = i++;
		staryuId = i++;
		starmieId = i++;
		trapinchId = i++;
		venusaurId = i++;
		voltorbId = i++;
		vulpixId = i++;
		wartortleId = i++;
		wigglytuffId = i++;
		zubatId = i++;
		pikachuId = i++;
		dratiniId = i++;
		magnetonId = i++;
		vibravaId = i++;
		mareepId = i++;
		solrockId = i++;
		lunatoneId = i++;
		tentacoolId = i++;
		nidoranMaleId = i++;
		vaporeonId = i++;
		gloomId = i++;
		krabbyId = i++;
		weedleId = i++;
		kakunaId = i++;
		koffingId = i++;
		weezingId = i++;
		primeapeId = i++;
		arcanineId = i++;
		parasId = i++;
		electrodeId = i++;
		golbatId = i++;
		drowzeeId = i++;
		numelId = i++;
		cameruptId = i++;
		scytherId = i++;
		flygonId = i++;
	}
}
