package pixelmon.config;


import cpw.mods.fml.common.registry.EntityRegistry;
import net.minecraftforge.common.Configuration;

public class IDListPixelmon {
	public static int abraId;
	public static int arbokId;
	public static int blastoiseId;
	public static int bulbasaurId;
	public static int butterfreeId;
	public static int caterpieId;
	public static int charizardId;
	public static int charmanderId;
	public static int charmeleonId;
	public static int cuboneId;
	public static int diglettId;
	public static int dugtrioId;
	public static int eeveeId;
	public static int ekansId;
	public static int electrodeId;
	public static int flareonId;
	public static int gastlyId;
	public static int geodudeId;
	public static int goldeenId;
	public static int growlitheId;
	public static int gyaradosId;
	public static int horseaId;
	public static int ivysaurId;
	public static int jigglypuffId;
	public static int jolteonId;
	public static int magikarpId;
	public static int magnemiteId;
	public static int mankeyId;
	public static int mewId;
	public static int metapodId;
	public static int miltankId;
	public static int ninetalesId;
	public static int oddishId;
	public static int omanyteId;
	public static int omastarId;
	public static int pidgeyId;
	public static int pidgeottoId;
	public static int pidgeotId;
	public static int pikachuId;
	public static int psyduckId;
	public static int rattataId;
	public static int seakingId;
	public static int snorlaxId;
	public static int sandileId;
	public static int staryuId;
	public static int starmieId;
	public static int krokorokId;
	public static int squirtleId;
	public static int shellderId;
	public static int trapinchId;
	public static int venusaurId;
	public static int voltorbId;
	public static int vulpixId;
	public static int wartortleId;
	public static int wigglytuffId;
	public static int zubatId;
	public static int dratiniId;
	public static int vibravaId;
	public static int magnetonId;
	public static int mareepId;
	public static int solrockId;
	public static int lunatoneId;
	public static int tentacoolId;
	public static int nidoranMaleId;
	public static int vaporeonId;
	public static int gloomId;
	public static int krabbyId;
	public static int weedleId;
	public static int kakunaId;
	public static int koffingId;
	public static int weezingId;
	public static int primeapeId;
	public static int arcanineId;
	public static int parasId;
	public static int golbatId;
	public static int drowzeeId;
	public static int numelId;
	
	
	public static void load(Configuration configuration) {
		abraId = Integer.parseInt(configuration.getOrCreateIntProperty("Abra", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		arbokId = Integer.parseInt(configuration.getOrCreateIntProperty("Arbok", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		blastoiseId = Integer.parseInt(configuration.getOrCreateIntProperty("Blastoise", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		bulbasaurId = Integer.parseInt(configuration.getOrCreateIntProperty("Bulbasaur", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		butterfreeId = Integer.parseInt(configuration.getOrCreateIntProperty("Butterfree", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		caterpieId = Integer.parseInt(configuration.getOrCreateIntProperty("Caterpie", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		charizardId = Integer.parseInt(configuration.getOrCreateIntProperty("Charizard", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		charmanderId = Integer.parseInt(configuration.getOrCreateIntProperty("Charmander", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		charmeleonId = Integer.parseInt(configuration.getOrCreateIntProperty("Charmeleon", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		cuboneId = Integer.parseInt(configuration.getOrCreateIntProperty("Cubone", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		diglettId = Integer.parseInt(configuration.getOrCreateIntProperty("Diglett", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		dugtrioId = Integer.parseInt(configuration.getOrCreateIntProperty("Dugtrio", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		eeveeId = Integer.parseInt(configuration.getOrCreateIntProperty("Eevee", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		ekansId = Integer.parseInt(configuration.getOrCreateIntProperty("Ekans", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		flareonId = Integer.parseInt(configuration.getOrCreateIntProperty("Flareon", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		gastlyId = Integer.parseInt(configuration.getOrCreateIntProperty("Gastly", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		geodudeId = Integer.parseInt(configuration.getOrCreateIntProperty("Geodude", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		goldeenId = Integer.parseInt(configuration.getOrCreateIntProperty("Goldeen", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		growlitheId = Integer.parseInt(configuration.getOrCreateIntProperty("Growlithe", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		gyaradosId = Integer.parseInt(configuration.getOrCreateIntProperty("Gyarados", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		horseaId = Integer.parseInt(configuration.getOrCreateIntProperty("Horsea", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		ivysaurId = Integer.parseInt(configuration.getOrCreateIntProperty("Ivysaur", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		jigglypuffId = Integer.parseInt(configuration.getOrCreateIntProperty("Jigglypuff", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		jolteonId = Integer.parseInt(configuration.getOrCreateIntProperty("Jolteon", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		sandileId = Integer.parseInt(configuration.getOrCreateIntProperty("Sandile", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		krokorokId = Integer.parseInt(configuration.getOrCreateIntProperty("Krokorok", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		magikarpId = Integer.parseInt(configuration.getOrCreateIntProperty("Magikarp", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		magnemiteId = Integer.parseInt(configuration.getOrCreateIntProperty("Magnemite", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		mankeyId = Integer.parseInt(configuration.getOrCreateIntProperty("Mankey", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		metapodId = Integer.parseInt(configuration.getOrCreateIntProperty("Metapod", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		mewId = Integer.parseInt(configuration.getOrCreateIntProperty("Mew", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		miltankId = Integer.parseInt(configuration.getOrCreateIntProperty("Miltank", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		pidgeyId = Integer.parseInt(configuration.getOrCreateIntProperty("Pidgey", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		pikachuId = Integer.parseInt(configuration.getOrCreateIntProperty("Pikachu", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		pidgeottoId = Integer.parseInt(configuration.getOrCreateIntProperty("Pidgeotto", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		pidgeotId = Integer.parseInt(configuration.getOrCreateIntProperty("Pidgeot", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		ninetalesId = Integer.parseInt(configuration.getOrCreateIntProperty("Ninetales", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		oddishId = Integer.parseInt(configuration.getOrCreateIntProperty("Oddish", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		omanyteId = Integer.parseInt(configuration.getOrCreateIntProperty("Omanyte", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		omastarId = Integer.parseInt(configuration.getOrCreateIntProperty("Omastar", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		psyduckId = Integer.parseInt(configuration.getOrCreateIntProperty("Psyduck", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		rattataId = Integer.parseInt(configuration.getOrCreateIntProperty("Rattata", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		seakingId = Integer.parseInt(configuration.getOrCreateIntProperty("Seaking", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		shellderId = Integer.parseInt(configuration.getOrCreateIntProperty("Shellder", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		snorlaxId = Integer.parseInt(configuration.getOrCreateIntProperty("Snorlax", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		squirtleId = Integer.parseInt(configuration.getOrCreateIntProperty("Squirtle", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		staryuId = Integer.parseInt(configuration.getOrCreateIntProperty("Staryu", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		starmieId = Integer.parseInt(configuration.getOrCreateIntProperty("Starmie", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		trapinchId = Integer.parseInt(configuration.getOrCreateIntProperty("Trapinch", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		venusaurId = Integer.parseInt(configuration.getOrCreateIntProperty("Venusaur", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		voltorbId = Integer.parseInt(configuration.getOrCreateIntProperty("Voltorb", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		vulpixId = Integer.parseInt(configuration.getOrCreateIntProperty("Vulpix", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		wartortleId = Integer.parseInt(configuration.getOrCreateIntProperty("Wartortle", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		wigglytuffId = Integer.parseInt(configuration.getOrCreateIntProperty("Wigglytuff", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		zubatId = Integer.parseInt(configuration.getOrCreateIntProperty("Zubat", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		pikachuId = Integer.parseInt(configuration.getOrCreateIntProperty("Pikachu", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		dratiniId = Integer.parseInt(configuration.getOrCreateIntProperty("Dratini", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		magnetonId = Integer.parseInt(configuration.getOrCreateIntProperty("Magneton", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		vibravaId = Integer.parseInt(configuration.getOrCreateIntProperty("Vibrava", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		mareepId = Integer.parseInt(configuration.getOrCreateIntProperty("Mareep", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		solrockId = Integer.parseInt(configuration.getOrCreateIntProperty("Solrock", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		lunatoneId = Integer.parseInt(configuration.getOrCreateIntProperty("Lunatone", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		tentacoolId = Integer.parseInt(configuration.getOrCreateIntProperty("Tentacool", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		nidoranMaleId = Integer.parseInt(configuration.getOrCreateIntProperty("NidoranMale", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		vaporeonId = Integer.parseInt(configuration.getOrCreateIntProperty("Vaporeon", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		gloomId = Integer.parseInt(configuration.getOrCreateIntProperty("Gloom", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		krabbyId = Integer.parseInt(configuration.getOrCreateIntProperty("Krabby", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		weedleId = Integer.parseInt(configuration.getOrCreateIntProperty("Weedle", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		kakunaId = Integer.parseInt(configuration.getOrCreateIntProperty("Kakuna", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		koffingId = Integer.parseInt(configuration.getOrCreateIntProperty("Koffing", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		weezingId = Integer.parseInt(configuration.getOrCreateIntProperty("Weezing", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		primeapeId = Integer.parseInt(configuration.getOrCreateIntProperty("Primeape", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		arcanineId = Integer.parseInt(configuration.getOrCreateIntProperty("Arcanine", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		parasId = Integer.parseInt(configuration.getOrCreateIntProperty("Paras", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		electrodeId = Integer.parseInt(configuration.getOrCreateIntProperty("Electrode", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		golbatId = Integer.parseInt(configuration.getOrCreateIntProperty("Golbat", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		drowzeeId = Integer.parseInt(configuration.getOrCreateIntProperty("Drowzee", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
		numelId = Integer.parseInt(configuration.getOrCreateIntProperty("Numel", "pokemon", EntityRegistry.findGlobalUniqueEntityId()).value);
	}
}
