// Date: 4/24/2013 2:33:33 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package pixelmon.client.models.pokemon;

import pixelmon.client.models.PixelmonModelRenderer;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import pixelmon.client.models.PixelmonModelBase;
import pixelmon.client.models.animations.ModuleHead;
import pixelmon.client.models.animations.SkeletonBase;
import pixelmon.client.models.animations.serpent.SkeletonSerpent;

public class ModelOnix extends PixelmonModelBase {
	// fields
	PixelmonModelRenderer Body;

	public ModelOnix() {
		textureWidth = 512;
		textureHeight = 512;

		Body = new PixelmonModelRenderer(this, "Body");
		Body.setRotationPoint(0, 10, -47);
		// Body.setRotationPoint(0, -47, -47);

		PixelmonModelRenderer Head = new PixelmonModelRenderer(this, "Head");
		Head.setRotationPoint(0, 0, 0);
		PixelmonModelRenderer CheekRight = new PixelmonModelRenderer(this, 443,
				0);
		CheekRight.addBox(-10.18F, 1.05F, 2.34F, 9, 5, 3);
		CheekRight.setTextureSize(512, 512);
		CheekRight.mirror = true;
		setRotation(CheekRight, 0.3427827F, -1.570796F, -0.3403392F);
		PixelmonModelRenderer headtopr = new PixelmonModelRenderer(this, 19, 40);
		headtopr.addBox(-4.9F, -2.2F, -10.2F, 4, 3, 9);
		headtopr.setTextureSize(512, 512);
		headtopr.mirror = true;
		setRotation(headtopr, 0.3490659F, 0.1064651F, -0.2617994F);
		PixelmonModelRenderer headtop1 = new PixelmonModelRenderer(this, 20,
				430);
		headtop1.addBox(-1.6F, -1.801F, -10.18F, 3, 3, 9);
		headtop1.setTextureSize(512, 512);
		headtop1.mirror = true;
		setRotation(headtop1, 0.3316126F, 0F, 0F);
		PixelmonModelRenderer headtop2 = new PixelmonModelRenderer(this, 100,
				100);
		headtop2.addBox(-1.4F, -1.8F, -10.18F, 3, 3, 9);
		headtop2.setTextureSize(512, 512);
		headtop2.mirror = true;
		setRotation(headtop2, 0.3316126F, 0F, 0F);
		PixelmonModelRenderer headtopl = new PixelmonModelRenderer(this, 2, 39);
		headtopl.addBox(0.9F, -2.2F, -10.2F, 4, 3, 9);
		headtopl.setTextureSize(512, 512);
		headtopl.mirror = true;
		setRotation(headtopl, 0.3490659F, -0.1064651F, 0.2617994F);
		PixelmonModelRenderer CheekLeft = new PixelmonModelRenderer(this, 17,
				42);
		CheekLeft.addBox(-10.18F, 1.05F, -5.32F, 9, 5, 3);
		CheekLeft.setTextureSize(512, 512);
		CheekLeft.mirror = true;
		setRotation(CheekLeft, -0.3427827F, -1.58825F, -0.3403392F);
		PixelmonModelRenderer LipTop1 = new PixelmonModelRenderer(this, 248, 22);
		LipTop1.addBox(-4.933333F, 1.32F, 4.2F, 9, 2, 11);
		LipTop1.setTextureSize(512, 512);
		LipTop1.mirror = true;
		setRotation(LipTop1, -0.5410346F, 3.176499F, -0.0047124F);
		PixelmonModelRenderer LipR1 = new PixelmonModelRenderer(this, 100, 100);
		LipR1.addBox(8.4F, 1.3F, 7.5F, 2, 2, 2);
		LipR1.setRotationPoint(1F, 0F, 0F);
		LipR1.setTextureSize(512, 512);
		LipR1.mirror = true;
		setRotation(LipR1, -0.5235988F, 2.881539F, 0.1570796F);
		PixelmonModelRenderer LipR2 = new PixelmonModelRenderer(this, 0, 112);
		LipR2.addBox(8.4F, 1.3F, 8.8F, 2, 2, 4);
		LipR2.setRotationPoint(1F, 0F, 0F);
		LipR2.setTextureSize(512, 512);
		LipR2.mirror = true;
		setRotation(LipR2, -0.5235988F, 2.881539F, 0.1570796F);
		PixelmonModelRenderer LipR3 = new PixelmonModelRenderer(this, 24, 448);
		LipR3.addBox(13.1F, 1.47F, 3.44F, 3, 2, 4);
		LipR3.setRotationPoint(1F, 0F, 0F);
		LipR3.setTextureSize(512, 512);
		LipR3.mirror = true;
		setRotation(LipR3, -0.296706F, 2.235767F, 0.439823F);
		PixelmonModelRenderer LipR4 = new PixelmonModelRenderer(this, 114, 45);
		LipR4.addBox(14.1F, 1.47F, 7.3F, 2, 2, 1);
		LipR4.setRotationPoint(1F, 0F, 0F);
		LipR4.setTextureSize(512, 512);
		LipR4.mirror = true;
		setRotation(LipR4, -0.296706F, 2.235767F, 0.439823F);
		PixelmonModelRenderer lipmiddle1 = new PixelmonModelRenderer(this, 114,
				45);
		lipmiddle1.addBox(14.5F, 1.85F, 4.54F, 3, 2, 1);
		lipmiddle1.setRotationPoint(1F, 0F, 0F);
		lipmiddle1.setTextureSize(512, 512);
		lipmiddle1.mirror = true;
		setRotation(lipmiddle1, -0.1745329F, 1.991421F, 0.4747296F);
		PixelmonModelRenderer lipmiddle2 = new PixelmonModelRenderer(this, 114,
				45);
		lipmiddle2.addBox(-17.5F, 1.9F, 4.5F, 3, 2, 1);
		lipmiddle2.setRotationPoint(-1F, 0F, 0F);
		lipmiddle2.setTextureSize(512, 512);
		lipmiddle2.mirror = true;
		setRotation(lipmiddle2, -0.1745329F, -1.991421F, -0.4712389F);
		PixelmonModelRenderer LipL1 = new PixelmonModelRenderer(this, 100, 100);
		LipL1.addBox(-10.43333F, 1.266667F, 7.85F, 2, 2, 5);
		LipL1.setRotationPoint(-1F, 0F, 0F);
		LipL1.setTextureSize(512, 512);
		LipL1.mirror = true;
		setRotation(LipL1, -0.5235988F, -2.881539F, -0.1570796F);
		PixelmonModelRenderer LipL2 = new PixelmonModelRenderer(this, 114, 52);
		LipL2.addBox(-16.13F, 1.45F, 3.48F, 3, 2, 4);
		LipL2.setRotationPoint(-1F, 0F, 0F);
		LipL2.setTextureSize(512, 512);
		LipL2.mirror = true;
		setRotation(LipL2, -0.296706F, -2.235767F, -0.439823F);
		PixelmonModelRenderer LipL3 = new PixelmonModelRenderer(this, 114, 45);
		LipL3.addBox(-16.13F, 1.45F, 7.26F, 3, 2, 1);
		LipL3.setRotationPoint(-1F, 0F, 0F);
		LipL3.setTextureSize(512, 512);
		LipL3.mirror = true;
		setRotation(LipL3, -0.296706F, -2.235767F, -0.439823F);
		PixelmonModelRenderer mouthplateau = new PixelmonModelRenderer(this,
				13, 170);
		mouthplateau.addBox(-4.466667F, -0.06F, -15.7F, 9, 1, 5);
		mouthplateau.setTextureSize(512, 512);
		mouthplateau.mirror = true;
		setRotation(mouthplateau, 0.6283185F, 0F, 0F);
		PixelmonModelRenderer Nose1 = new PixelmonModelRenderer(this, 43, 133);
		Nose1.addBox(-1F, -10.15F, -14.6F, 2, 2, 3);
		Nose1.setTextureSize(512, 512);
		Nose1.mirror = true;
		setRotation(Nose1, 1.22173F, 0F, 0F);
		PixelmonModelRenderer Nose2 = new PixelmonModelRenderer(this, 24, 45);
		Nose2.addBox(-1F, -6.812F, -13.84F, 2, 3, 6);
		Nose2.setTextureSize(512, 512);
		Nose2.mirror = true;
		setRotation(Nose2, 0.9599311F, 0F, 0F);
		PixelmonModelRenderer Nose3 = new PixelmonModelRenderer(this, 24, 45);
		Nose3.addBox(-1F, -8.3F, -11.1F, 2, 3, 5);
		Nose3.setTextureSize(512, 512);
		Nose3.mirror = true;
		setRotation(Nose3, 1.099557F, 0F, 0F);
		PixelmonModelRenderer Nose4 = new PixelmonModelRenderer(this, 24, 45);
		Nose4.addBox(-1.5F, -8.299F, -9.1F, 3, 3, 3);
		Nose4.setTextureSize(512, 512);
		Nose4.mirror = true;
		setRotation(Nose4, 1.099557F, 0F, 0F);
		PixelmonModelRenderer Hornmain = new PixelmonModelRenderer(this, 118,
				11);
		Hornmain.addBox(-0.5F, -11.2F, -7.7F, 1, 15, 2);
		Hornmain.setTextureSize(512, 512);
		Hornmain.mirror = true;
		setRotation(Hornmain, -0.1570796F, 0F, 0F);
		PixelmonModelRenderer horn1 = new PixelmonModelRenderer(this, 137, 49);
		horn1.addBox(-0.501F, 1.4F, -8F, 1, 5, 2);
		horn1.setTextureSize(512, 512);
		horn1.mirror = true;
		setRotation(horn1, -0.5235988F, 0F, 0F);
		PixelmonModelRenderer horn2 = new PixelmonModelRenderer(this, 118, 15);
		horn2.addBox(-0.5F, -4F, -8.3F, 1, 7, 2);
		horn2.setTextureSize(512, 512);
		horn2.mirror = true;
		setRotation(horn2, -0.1396263F, 0F, 0F);
		PixelmonModelRenderer horn3 = new PixelmonModelRenderer(this, 133, 15);
		horn3.addBox(-0.5F, -4F, -7.3F, 1, 7, 2);
		horn3.setTextureSize(512, 512);
		horn3.mirror = true;
		setRotation(horn3, -0.1396263F, 0F, 0F);
		PixelmonModelRenderer horn4 = new PixelmonModelRenderer(this, 121, 56);
		horn4.addBox(-0.5F, -1.02F, -9.162F, 1, 2, 2);
		horn4.setTextureSize(512, 512);
		horn4.mirror = true;
		setRotation(horn4, -0.6981317F, 0F, 0F);
		PixelmonModelRenderer horn5 = new PixelmonModelRenderer(this, 133, 11);
		horn5.addBox(-0.5F, -11.4F, -5.2F, 1, 10, 2);
		horn5.setTextureSize(512, 512);
		horn5.mirror = true;
		setRotation(horn5, 0.0436332F, 0F, 0F);
		PixelmonModelRenderer horn6 = new PixelmonModelRenderer(this, 14, 204);
		horn6.addBox(-0.5F, -12.3F, -4.4F, 1, 10, 2);
		horn6.setTextureSize(512, 512);
		horn6.mirror = true;
		setRotation(horn6, 0.1047198F, 0F, 0F);
		PixelmonModelRenderer eyeleftmain = new PixelmonModelRenderer(this,
				187, 26);
		eyeleftmain.addBox(-7.2F, 2.55F, -10.5F, 6, 3, 2);
		eyeleftmain.setTextureSize(512, 512);
		eyeleftmain.mirror = true;
		setRotation(eyeleftmain, 0.1047198F, -0.5235988F, -0.3490659F);
		PixelmonModelRenderer eyeleft1 = new PixelmonModelRenderer(this, 184,
				26);
		eyeleft1.addBox(-5.7F, 2.55F, -10.501F, 1, 2, 1);
		eyeleft1.setTextureSize(512, 512);
		eyeleft1.mirror = true;
		setRotation(eyeleft1, 0.1047198F, -0.5235988F, -0.3490659F);
		PixelmonModelRenderer eyeleft2 = new PixelmonModelRenderer(this, 185,
				26);
		eyeleft2.addBox(-7.1F, 2.55F, -10.501F, 1, 2, 1);
		eyeleft2.setTextureSize(512, 512);
		eyeleft2.mirror = true;
		setRotation(eyeleft2, 0.1047198F, -0.5235988F, -0.3490659F);
		PixelmonModelRenderer EyebrowL1 = new PixelmonModelRenderer(this, 288,
				0);
		EyebrowL1.addBox(-6.9F, 0.5F, -11.1F, 1, 1, 2);
		EyebrowL1.setTextureSize(512, 512);
		EyebrowL1.mirror = true;
		setRotation(EyebrowL1, 0.1570796F, -0.4537856F, -0.4886922F);
		PixelmonModelRenderer EyebrowL2 = new PixelmonModelRenderer(this, 2,
				139);
		EyebrowL2.addBox(-7.266667F, 1.1F, -11.1F, 6, 1, 2);
		EyebrowL2.setTextureSize(512, 512);
		EyebrowL2.mirror = true;
		setRotation(EyebrowL2, 0.1570796F, -0.4537856F, -0.4886922F);
		PixelmonModelRenderer EyebrowL3 = new PixelmonModelRenderer(this, 288,
				0);
		EyebrowL3.addBox(-5.9F, 0.3F, -11.1F, 1, 1, 2);
		EyebrowL3.setTextureSize(512, 512);
		EyebrowL3.mirror = true;
		setRotation(EyebrowL3, 0.1570796F, -0.4537856F, -0.4886922F);
		PixelmonModelRenderer EyebrowL4 = new PixelmonModelRenderer(this, 288,
				0);
		EyebrowL4.addBox(-5.266667F, 0.3F, -11.1F, 4, 1, 2);
		EyebrowL4.setTextureSize(512, 512);
		EyebrowL4.mirror = true;
		setRotation(EyebrowL4, 0.1570796F, -0.4537856F, -0.4886922F);
		PixelmonModelRenderer eyerightmain = new PixelmonModelRenderer(this,
				179, 26);
		eyerightmain.addBox(0.2F, 2.5F, -10.4F, 7, 3, 2);
		eyerightmain.setTextureSize(512, 512);
		eyerightmain.mirror = true;
		setRotation(eyerightmain, 0.1047198F, 0.5235988F, 0.3490659F);
		PixelmonModelRenderer eyeright1 = new PixelmonModelRenderer(this, 185,
				41);
		eyeright1.addBox(4.7F, 2.5F, -10.401F, 1, 2, 1);
		eyeright1.setTextureSize(512, 512);
		eyeright1.mirror = true;
		setRotation(eyeright1, 0.1047198F, 0.5235988F, 0.3490659F);
		PixelmonModelRenderer eyeright2 = new PixelmonModelRenderer(this, 182,
				10);
		eyeright2.addBox(6.066667F, 2.5F, -10.401F, 1, 2, 1);
		eyeright2.setTextureSize(512, 512);
		eyeright2.mirror = true;
		setRotation(eyeright2, 0.1047198F, 0.5235988F, 0.3490659F);
		PixelmonModelRenderer EyeBrowR = new PixelmonModelRenderer(this, 249,
				10);
		EyeBrowR.addBox(6F, 0.5F, -11.1F, 1, 1, 2);
		EyeBrowR.setTextureSize(512, 512);
		EyeBrowR.mirror = true;
		setRotation(EyeBrowR, 0.1570796F, 0.4537856F, 0.4886922F);
		PixelmonModelRenderer EyeBrowR1 = new PixelmonModelRenderer(this, 29,
				171);
		EyeBrowR1.addBox(0.9666666F, 1.1F, -11.101F, 6, 1, 2);
		EyeBrowR1.setTextureSize(512, 512);
		EyeBrowR1.mirror = true;
		setRotation(EyeBrowR1, 0.1570796F, 0.4537856F, 0.4886922F);
		PixelmonModelRenderer EyeBrowR2 = new PixelmonModelRenderer(this, 249,
				10);
		EyeBrowR2.addBox(1.28F, 0.3F, -11.1F, 4, 1, 2);
		EyeBrowR2.setTextureSize(512, 512);
		EyeBrowR2.mirror = true;
		setRotation(EyeBrowR2, 0.1570796F, 0.4537856F, 0.4886922F);
		PixelmonModelRenderer EyeBrowR3 = new PixelmonModelRenderer(this, 249,
				10);
		EyeBrowR3.addBox(5F, 0.3F, -11.1F, 1, 1, 2);
		EyeBrowR3.setTextureSize(512, 512);
		EyeBrowR3.mirror = true;
		setRotation(EyeBrowR3, 0.1570796F, 0.4537856F, 0.4886922F);
		PixelmonModelRenderer headdecol1 = new PixelmonModelRenderer(this, 288,
				0);
		headdecol1.addBox(-2.3F, -8.6F, -6.9F, 1, 1, 1);
		headdecol1.setTextureSize(512, 512);
		headdecol1.mirror = true;
		setRotation(headdecol1, 1.134464F, -0.3839724F, -0.2617994F);
		PixelmonModelRenderer headdecol2 = new PixelmonModelRenderer(this, 288,
				0);
		headdecol2.addBox(-3.8F, -8.6F, -7.66F, 1, 1, 1);
		headdecol2.setTextureSize(512, 512);
		headdecol2.mirror = true;
		setRotation(headdecol2, 1.134464F, -0.3839724F, -0.2617994F);
		PixelmonModelRenderer headdecol3 = new PixelmonModelRenderer(this, 288,
				0);
		headdecol3.addBox(-2.95F, -8.6F, -6.133333F, 1, 1, 1);
		headdecol3.setTextureSize(512, 512);
		headdecol3.mirror = true;
		setRotation(headdecol3, 1.134464F, -0.3839724F, -0.2617994F);
		PixelmonModelRenderer headdecol4 = new PixelmonModelRenderer(this, 288,
				0);
		headdecol4.addBox(-2.8F, -8.6F, -7.4F, 1, 1, 1);
		headdecol4.setTextureSize(512, 512);
		headdecol4.mirror = true;
		setRotation(headdecol4, 1.134464F, -0.3839724F, -0.2617994F);
		PixelmonModelRenderer headdecol5 = new PixelmonModelRenderer(this, 288,
				0);
		headdecol5.addBox(-3.4F, -8.6F, -7.2F, 1, 1, 1);
		headdecol5.setTextureSize(512, 512);
		headdecol5.mirror = true;
		setRotation(headdecol5, 1.134464F, -0.3839724F, -0.2617994F);
		PixelmonModelRenderer headdecol6 = new PixelmonModelRenderer(this, 288,
				0);
		headdecol6.addBox(-3.2F, -8.6F, -6.6F, 1, 1, 1);
		headdecol6.setTextureSize(512, 512);
		headdecol6.mirror = true;
		setRotation(headdecol6, 1.134464F, -0.3839724F, -0.2617994F);
		PixelmonModelRenderer headdecol7 = new PixelmonModelRenderer(this, 288,
				0);
		headdecol7.addBox(-2.8F, -8.6F, -7.2F, 1, 1, 2);
		headdecol7.setTextureSize(512, 512);
		headdecol7.mirror = true;
		setRotation(headdecol7, 1.134464F, -0.3839724F, -0.2617994F);
		PixelmonModelRenderer headdecol8 = new PixelmonModelRenderer(this, 288,
				0);
		headdecol8.addBox(-1.5F, -8.6F, -7.2F, 1, 1, 1);
		headdecol8.setTextureSize(512, 512);
		headdecol8.mirror = true;
		setRotation(headdecol8, 1.134464F, -0.3839724F, -0.2617994F);
		PixelmonModelRenderer headdecol9 = new PixelmonModelRenderer(this, 288,
				0);
		headdecol9.addBox(-1.8F, -8.6F, -7.2F, 1, 1, 1);
		headdecol9.setTextureSize(512, 512);
		headdecol9.mirror = true;
		setRotation(headdecol9, 1.134464F, -0.3839724F, -0.2617994F);
		PixelmonModelRenderer headdecor1 = new PixelmonModelRenderer(this, 126,
				53);
		headdecor1.addBox(3.67F, -7.43F, -7.118F, 1, 1, 1);
		headdecor1.setTextureSize(512, 512);
		headdecor1.mirror = true;
		setRotation(headdecor1, 1.134464F, 0.8552113F, -0.0523599F);
		PixelmonModelRenderer headdecor2 = new PixelmonModelRenderer(this, 126,
				53);
		headdecor2.addBox(0.64F, -8.6F, -7.28F, 1, 1, 1);
		headdecor2.setTextureSize(512, 512);
		headdecor2.mirror = true;
		setRotation(headdecor2, 1.134464F, 0.3839724F, 0.2617994F);
		PixelmonModelRenderer headdecor3 = new PixelmonModelRenderer(this, 126,
				53);
		headdecor3.addBox(1.9F, -8.6F, -6.6F, 1, 2, 1);
		headdecor3.setTextureSize(512, 512);
		headdecor3.mirror = true;
		setRotation(headdecor3, 1.134464F, 0.3839724F, 0.2617994F);
		PixelmonModelRenderer headdecor4 = new PixelmonModelRenderer(this, 126,
				53);
		headdecor4.addBox(2.9F, -8.6F, -7.2F, 1, 2, 0);
		headdecor4.setTextureSize(512, 512);
		headdecor4.mirror = true;
		setRotation(headdecor4, 1.134464F, 0.3839724F, 0.2617994F);
		PixelmonModelRenderer headdecor5 = new PixelmonModelRenderer(this, 126,
				53);
		headdecor5.addBox(1.4F, -8.6F, -6.766667F, 1, 2, 1);
		headdecor5.setTextureSize(512, 512);
		headdecor5.mirror = true;
		setRotation(headdecor5, 1.134464F, 0.3839724F, 0.2617994F);
		PixelmonModelRenderer headdecor6 = new PixelmonModelRenderer(this, 126,
				53);
		headdecor6.addBox(1.3F, -8.6F, -7.4F, 1, 2, 1);
		headdecor6.setTextureSize(512, 512);
		headdecor6.mirror = true;
		setRotation(headdecor6, 1.134464F, 0.3839724F, 0.2617994F);
		PixelmonModelRenderer headdecor7 = new PixelmonModelRenderer(this, 126,
				53);
		headdecor7.addBox(1.9F, -8.6F, -6.5F, 1, 2, 1);
		headdecor7.setTextureSize(512, 512);
		headdecor7.mirror = true;
		setRotation(headdecor7, 1.134464F, 0.3839724F, 0.2617994F);
		PixelmonModelRenderer headdecor8 = new PixelmonModelRenderer(this, 126,
				53);
		headdecor8.addBox(0.9F, -8.6F, -7.166667F, 1, 2, 1);
		headdecor8.setTextureSize(512, 512);
		headdecor8.mirror = true;
		setRotation(headdecor8, 1.134464F, 0.3839724F, 0.2617994F);
		PixelmonModelRenderer headdecor9 = new PixelmonModelRenderer(this, 126,
				53);
		headdecor9.addBox(1.96F, -8.6F, -6.2F, 1, 1, 1);
		headdecor9.setTextureSize(512, 512);
		headdecor9.mirror = true;
		setRotation(headdecor9, 1.134464F, 0.3839724F, 0.2617994F);
		PixelmonModelRenderer headdecor10 = new PixelmonModelRenderer(this,
				126, 53);
		headdecor10.addBox(2.433333F, -8.6F, -7.6F, 1, 2, 1);
		headdecor10.setTextureSize(512, 512);
		headdecor10.mirror = true;
		setRotation(headdecor10, 1.134464F, 0.3839724F, 0.2617994F);
		PixelmonModelRenderer headdecor11 = new PixelmonModelRenderer(this,
				126, 53);
		headdecor11.addBox(2.2F, -8.6F, -7.6F, 1, 2, 2);
		headdecor11.setTextureSize(512, 512);
		headdecor11.mirror = true;
		setRotation(headdecor11, 1.134464F, 0.3839724F, 0.2617994F);
		PixelmonModelRenderer headdecor12 = new PixelmonModelRenderer(this,
				126, 53);
		headdecor12.addBox(2.3F, -8.6F, -7.2F, 1, 2, 1);
		headdecor12.setTextureSize(512, 512);
		headdecor12.mirror = true;
		setRotation(headdecor12, 1.134464F, 0.3839724F, 0.2617994F);
		PixelmonModelRenderer headdecor13 = new PixelmonModelRenderer(this,
				126, 53);
		headdecor13.addBox(2.87F, -8.6F, -7.666667F, 1, 1, 1);
		headdecor13.setTextureSize(512, 512);
		headdecor13.mirror = true;
		setRotation(headdecor13, 1.134464F, 0.3839724F, 0.2617994F);
		PixelmonModelRenderer headdecor14 = new PixelmonModelRenderer(this,
				126, 53);
		headdecor14.addBox(2.9F, -8.6F, -7.7F, 1, 1, 1);
		headdecor14.setTextureSize(512, 512);
		headdecor14.mirror = true;
		setRotation(headdecor14, 1.134464F, 0.3839724F, 0.2617994F);
		PixelmonModelRenderer horndecomain = new PixelmonModelRenderer(this, 0,
				212);
		horndecomain.addBox(-1.5F, -4.2F, -5.6F, 3, 3, 4);
		horndecomain.setTextureSize(512, 512);
		horndecomain.mirror = true;
		setRotation(horndecomain, 0.296706F, 0F, 0F);
		PixelmonModelRenderer horndeco1 = new PixelmonModelRenderer(this, 0,
				213);
		horndeco1.addBox(0.12F, -3.95F, -5.59F, 2, 4, 4);
		horndeco1.setTextureSize(512, 512);
		horndeco1.mirror = true;
		setRotation(horndeco1, 0.296706F, 0.0523599F, -0.122173F);
		PixelmonModelRenderer horndeco2 = new PixelmonModelRenderer(this, 0,
				213);
		horndeco2.addBox(-2.12F, -3.95F, -5.59F, 2, 4, 4);
		horndeco2.setTextureSize(512, 512);
		horndeco2.mirror = true;
		setRotation(horndeco2, 0.296706F, -0.0523599F, 0.122173F);
		PixelmonModelRenderer horndeco3 = new PixelmonModelRenderer(this, 0,
				213);
		horndeco3.addBox(0.9F, -6.8F, -2.8F, 1, 3, 1);
		horndeco3.setTextureSize(512, 512);
		horndeco3.mirror = true;
		setRotation(horndeco3, 0.296706F, 0.0523599F, -0.1396263F);
		PixelmonModelRenderer horndeco4 = new PixelmonModelRenderer(this, 0,
				213);
		horndeco4.addBox(0.9F, -6.8F, -5.3F, 1, 3, 3);
		horndeco4.setTextureSize(512, 512);
		horndeco4.mirror = true;
		setRotation(horndeco4, 0.296706F, 0.0523599F, -0.1396263F);
		PixelmonModelRenderer horndeco5 = new PixelmonModelRenderer(this, 0,
				203);
		horndeco5.addBox(-1.899F, -6.783333F, -2.8F, 1, 3, 1);
		horndeco5.setTextureSize(512, 512);
		horndeco5.mirror = true;
		setRotation(horndeco5, 0.296706F, -0.0523599F, 0.1396263F);
		PixelmonModelRenderer horndeco6 = new PixelmonModelRenderer(this, 0,
				213);
		horndeco6.addBox(-1.9F, -6.783333F, -5.3F, 1, 3, 3);
		horndeco6.setTextureSize(512, 512);
		horndeco6.mirror = true;
		setRotation(horndeco6, 0.296706F, -0.0523599F, 0.1396263F);
		PixelmonModelRenderer horndeco7 = new PixelmonModelRenderer(this, 0,
				203);
		horndeco7.addBox(-1.5409F, -7.133333F, -6.3F, 1, 2, 2);
		horndeco7.setTextureSize(512, 512);
		horndeco7.mirror = true;
		setRotation(horndeco7, 0.0523599F, -0.0523599F, 0.0872665F);
		PixelmonModelRenderer horndeco8 = new PixelmonModelRenderer(this, 0,
				213);
		horndeco8.addBox(-1.54F, -9.49F, -3.3F, 1, 3, 1);
		horndeco8.setTextureSize(512, 512);
		horndeco8.mirror = true;
		setRotation(horndeco8, 0.296706F, -0.0523599F, 0.0872665F);
		PixelmonModelRenderer horndeco9 = new PixelmonModelRenderer(this, 0,
				213);
		horndeco9.addBox(-1.54F, -4.73F, -9.1F, 1, 2, 1);
		horndeco9.setTextureSize(512, 512);
		horndeco9.mirror = true;
		setRotation(horndeco9, -0.5061455F, -0.0523599F, 0.0872665F);
		PixelmonModelRenderer horndeco11 = new PixelmonModelRenderer(this, 0,
				213);
		horndeco11.addBox(0.66F, -9.5F, -3.3F, 1, 3, 1);
		horndeco11.setTextureSize(512, 512);
		horndeco11.mirror = true;
		setRotation(horndeco11, 0.296706F, 0.0523599F, -0.1047198F);
		PixelmonModelRenderer horndeco12 = new PixelmonModelRenderer(this, 0,
				213);
		horndeco12.addBox(0.54F, -4.7F, -9.1F, 1, 2, 1);
		horndeco12.setTextureSize(512, 512);
		horndeco12.mirror = true;
		setRotation(horndeco12, -0.5061455F, 0.0523599F, -0.0872665F);
		PixelmonModelRenderer horndeco13 = new PixelmonModelRenderer(this, 0,
				213);
		horndeco13.addBox(0.54F, -7.1F, -6.3F, 1, 2, 2);
		horndeco13.setTextureSize(512, 512);
		horndeco13.mirror = true;
		setRotation(horndeco13, 0.0523599F, 0.0523599F, -0.0872665F);
		PixelmonModelRenderer headbackl1 = new PixelmonModelRenderer(this, 2,
				39);
		headbackl1.addBox(-1.72F, 1.23F, -4.69F, 1, 4, 3);
		headbackl1.setTextureSize(512, 512);
		headbackl1.mirror = true;
		setRotation(headbackl1, -0.3427827F, -1.58825F, -0.3403392F);
		PixelmonModelRenderer headbackl2 = new PixelmonModelRenderer(this, 2,
				39);
		headbackl2.addBox(1.5F, -1.7F, -1.733333F, 3, 7, 1);
		headbackl2.setTextureSize(512, 512);
		headbackl2.mirror = true;
		setRotation(headbackl2, 0.3490659F, -0.1064651F, 0.2617994F);
		PixelmonModelRenderer headbackmiddle = new PixelmonModelRenderer(this,
				2, 39);
		headbackmiddle.addBox(-2F, -1.2F, -1.697F, 4, 7, 1);
		headbackmiddle.setTextureSize(512, 512);
		headbackmiddle.mirror = true;
		setRotation(headbackmiddle, 0.3490659F, 0F, 0F);
		PixelmonModelRenderer headbackl12 = new PixelmonModelRenderer(this, 2,
				39);
		headbackl12.addBox(-1.64F, 1.25F, 1.64F, 1, 4, 3);
		headbackl12.setTextureSize(512, 512);
		headbackl12.mirror = true;
		setRotation(headbackl12, 0.3427827F, -1.58825F, -0.3403392F);
		PixelmonModelRenderer headbackr2 = new PixelmonModelRenderer(this, 2,
				39);
		headbackr2.addBox(-4.5F, -1.7F, -1.733333F, 3, 7, 1);
		headbackr2.setTextureSize(512, 512);
		headbackr2.mirror = true;
		setRotation(headbackr2, 0.3490659F, 0.1064651F, -0.2617994F);
		PixelmonModelRenderer LowerJawR1 = new PixelmonModelRenderer(this, 246,
				280);
		LowerJawR1.addBox(-5.57F, 4.3F, 1.25F, 1, 7, 1);
		LowerJawR1.setTextureSize(512, 512);
		LowerJawR1.mirror = true;
		setRotation(LowerJawR1, -0.6283185F, 0F, 0F);
		PixelmonModelRenderer LowerJawR2 = new PixelmonModelRenderer(this, 246,
				280);
		LowerJawR2.addBox(-6.57F, 3.3F, 1.25F, 1, 1, 1);
		LowerJawR2.setTextureSize(512, 512);
		LowerJawR2.mirror = true;
		setRotation(LowerJawR2, -0.6283185F, 0F, 0F);
		PixelmonModelRenderer LowerJawR3 = new PixelmonModelRenderer(this, 0,
				285);
		LowerJawR3.addBox(-6.601F, 4.3F, 0.25F, 1, 7, 2);
		LowerJawR3.setTextureSize(512, 512);
		LowerJawR3.mirror = true;
		setRotation(LowerJawR3, -0.6283185F, 0F, 0F);
		PixelmonModelRenderer LowerJawR4 = new PixelmonModelRenderer(this, 2,
				245);
		LowerJawR4.addBox(-6.57F, 5.3F, -0.75F, 1, 6, 2);
		LowerJawR4.setTextureSize(512, 512);
		LowerJawR4.mirror = true;
		setRotation(LowerJawR4, -0.6283185F, 0F, 0F);
		PixelmonModelRenderer LowerJawR5 = new PixelmonModelRenderer(this, 243,
				283);
		LowerJawR5.addBox(-6.57F, 8.3F, -2.75F, 1, 3, 3);
		LowerJawR5.setTextureSize(512, 512);
		LowerJawR5.mirror = true;
		setRotation(LowerJawR5, -0.6283185F, 0F, 0F);
		PixelmonModelRenderer LowerJawR6 = new PixelmonModelRenderer(this, 100,
				95);
		LowerJawR6.addBox(7.1F, 4.6F, 7F, 2, 2, 3);
		LowerJawR6.setTextureSize(512, 512);
		LowerJawR6.mirror = true;
		setRotation(LowerJawR6, -0.5235988F, 2.881539F, 0.1518436F);
		PixelmonModelRenderer LowerJawR7 = new PixelmonModelRenderer(this, 100,
				98);
		LowerJawR7.addBox(7.1F, 4.6F, 9.2F, 2, 2, 4);
		LowerJawR7.setTextureSize(512, 512);
		LowerJawR7.mirror = true;
		setRotation(LowerJawR7, -0.5235988F, 2.881539F, 0.1518436F);
		PixelmonModelRenderer LowerJawR8 = new PixelmonModelRenderer(this, 98,
				100);
		LowerJawR8.addBox(15.1F, 4.85F, 0.71F, 1, 2, 4);
		LowerJawR8.setTextureSize(512, 512);
		LowerJawR8.mirror = true;
		setRotation(LowerJawR8, -0.1570796F, 1.991421F, 0.4886922F);
		PixelmonModelRenderer LowerJawMiddle = new PixelmonModelRenderer(this,
				340, 299);
		LowerJawMiddle.addBox(-16.94667F, -1F, -6.35F, 1, 2, 2);
		LowerJawMiddle.setTextureSize(512, 512);
		LowerJawMiddle.mirror = true;
		setRotation(LowerJawMiddle, 1.570796F, -1.570796F, -0.5410521F);
		PixelmonModelRenderer LowerJawL1 = new PixelmonModelRenderer(this, 217,
				299);
		LowerJawL1.addBox(4.56F, 4.3F, 0.2F, 1, 7, 2);
		LowerJawL1.setTextureSize(512, 512);
		LowerJawL1.mirror = true;
		setRotation(LowerJawL1, -0.6283185F, 0F, 0F);
		PixelmonModelRenderer LowerJawL2 = new PixelmonModelRenderer(this, 2,
				291);
		LowerJawL2.addBox(4.6F, 4.3F, 0.204F, 1, 7, 2);
		LowerJawL2.setTextureSize(512, 512);
		LowerJawL2.mirror = true;
		setRotation(LowerJawL2, -0.6283185F, 0F, 0F);
		PixelmonModelRenderer LowerJawL3 = new PixelmonModelRenderer(this, 324,
				300);
		LowerJawL3.addBox(5.56F, 3.526667F, 1.2F, 1, 1, 1);
		LowerJawL3.setTextureSize(512, 512);
		LowerJawL3.mirror = true;
		setRotation(LowerJawL3, -0.6283185F, 0F, 0F);
		PixelmonModelRenderer LowerJawL4 = new PixelmonModelRenderer(this, 324,
				301);
		LowerJawL4.addBox(5.56F, 6.33F, -0.8F, 1, 1, 2);
		LowerJawL4.setTextureSize(512, 512);
		LowerJawL4.mirror = true;
		setRotation(LowerJawL4, -0.6283185F, 0F, 0F);
		PixelmonModelRenderer LowerJawL5 = new PixelmonModelRenderer(this, 324,
				301);
		LowerJawL5.addBox(5.56F, 7.3F, -1.8F, 1, 4, 2);
		LowerJawL5.setTextureSize(512, 512);
		LowerJawL5.mirror = true;
		setRotation(LowerJawL5, -0.6283185F, 0F, 0F);
		PixelmonModelRenderer LowerJawL6 = new PixelmonModelRenderer(this, 324,
				300);
		LowerJawL6.addBox(5.56F, 8.3F, -2.8F, 1, 3, 2);
		LowerJawL6.setTextureSize(512, 512);
		LowerJawL6.mirror = true;
		setRotation(LowerJawL6, -0.6283185F, 0F, 0F);
		PixelmonModelRenderer LowerJawL7 = new PixelmonModelRenderer(this, 324,
				300);
		LowerJawL7.addBox(5.56F, 4.3F, 0.2F, 1, 7, 2);
		LowerJawL7.setTextureSize(512, 512);
		LowerJawL7.mirror = true;
		setRotation(LowerJawL7, -0.6283185F, 0F, 0F);
		PixelmonModelRenderer LowerJawL8 = new PixelmonModelRenderer(this, 100,
				100);
		LowerJawL8.addBox(-9.1F, 4.54F, 7F, 2, 2, 6);
		LowerJawL8.setTextureSize(512, 512);
		LowerJawL8.mirror = true;
		setRotation(LowerJawL8, -0.5235988F, -2.881539F, -0.1518436F);
		PixelmonModelRenderer LowerJawL9 = new PixelmonModelRenderer(this, 100,
				100);
		LowerJawL9.addBox(-9.1F, 4.54F, 7.29F, 2, 2, 6);
		LowerJawL9.setTextureSize(512, 512);
		LowerJawL9.mirror = true;
		setRotation(LowerJawL9, -0.5235988F, -2.881539F, -0.1518436F);
		PixelmonModelRenderer LowerJawL10 = new PixelmonModelRenderer(this,
				100, 100);
		LowerJawL10.addBox(-16.05F, 4.82F, 0.9F, 1, 2, 4);
		LowerJawL10.setTextureSize(512, 512);
		LowerJawL10.mirror = true;
		setRotation(LowerJawL10, -0.1570796F, -1.991421F, -0.4886922F);
		PixelmonModelRenderer LowerJawPlateauThingy1 = new PixelmonModelRenderer(
				this, 202, 300);
		LowerJawPlateauThingy1.addBox(-6.6F, 4.3F, 0.6F, 12, 7, 1);
		LowerJawPlateauThingy1.setTextureSize(512, 512);
		LowerJawPlateauThingy1.mirror = true;
		setRotation(LowerJawPlateauThingy1, -0.6108652F, -0.0174533F,
				-0.0349066F);
		PixelmonModelRenderer LowerJawPlateauThingy2 = new PixelmonModelRenderer(
				this, 20, 42);
		LowerJawPlateauThingy2.addBox(-4.033333F, 3.08F, 1.67F, 9, 1, 9);
		LowerJawPlateauThingy2.setTextureSize(512, 512);
		LowerJawPlateauThingy2.mirror = true;
		setRotation(LowerJawPlateauThingy2, -0.7470009F, 3.141593F, 0.0349066F);
		PixelmonModelRenderer LowerJawPlateauThingy3 = new PixelmonModelRenderer(
				this, 276, 291);
		LowerJawPlateauThingy3.addBox(-4.033333F, 4.862F, 9.8F, 9, 1, 5);
		LowerJawPlateauThingy3.setTextureSize(512, 512);
		LowerJawPlateauThingy3.mirror = true;
		setRotation(LowerJawPlateauThingy3, -0.572468F, 3.141593F, 0.0349066F);
		PixelmonModelRenderer LowerJawPlateauThingy4 = new PixelmonModelRenderer(
				this, 234, 328);
		LowerJawPlateauThingy4.addBox(-4.1F, 5.57F, 14.26667F, 9, 1, 1);
		LowerJawPlateauThingy4.setTextureSize(512, 512);
		LowerJawPlateauThingy4.mirror = true;
		setRotation(LowerJawPlateauThingy4, -0.5235988F, 3.160209F, 0.0232652F);
		PixelmonModelRenderer LowerJawPlateauThingy5 = new PixelmonModelRenderer(
				this, 251, 305);
		LowerJawPlateauThingy5.addBox(-16F, -2.366667F, -6.3F, 1, 5, 1);
		LowerJawPlateauThingy5.setTextureSize(512, 512);
		LowerJawPlateauThingy5.mirror = true;
		setRotation(LowerJawPlateauThingy5, 1.570796F, -1.553343F, -0.5410521F);
		Head.addChild(CheekRight);
		Head.addChild(headtopr);
		Head.addChild(headtop1);
		Head.addChild(headtop2);
		Head.addChild(headtopl);
		Head.addChild(CheekLeft);
		Head.addChild(LipTop1);
		Head.addChild(LipR1);
		Head.addChild(LipR2);
		Head.addChild(LipR3);
		Head.addChild(LipR4);
		Head.addChild(lipmiddle1);
		Head.addChild(lipmiddle2);
		Head.addChild(LipL1);
		Head.addChild(LipL2);
		Head.addChild(LipL3);
		Head.addChild(mouthplateau);
		Head.addChild(Nose1);
		Head.addChild(Nose2);
		Head.addChild(Nose3);
		Head.addChild(Nose4);
		Head.addChild(Hornmain);
		Head.addChild(horn1);
		Head.addChild(horn2);
		Head.addChild(horn3);
		Head.addChild(horn4);
		Head.addChild(horn5);
		Head.addChild(horn6);
		Head.addChild(eyeleftmain);
		Head.addChild(eyeleft1);
		Head.addChild(eyeleft2);
		Head.addChild(EyebrowL1);
		Head.addChild(EyebrowL2);
		Head.addChild(EyebrowL3);
		Head.addChild(EyebrowL4);
		Head.addChild(eyerightmain);
		Head.addChild(eyeright1);
		Head.addChild(eyeright2);
		Head.addChild(EyeBrowR);
		Head.addChild(EyeBrowR1);
		Head.addChild(EyeBrowR2);
		Head.addChild(EyeBrowR3);
		Head.addChild(headdecol1);
		Head.addChild(headdecol2);
		Head.addChild(headdecol3);
		Head.addChild(headdecol4);
		Head.addChild(headdecol5);
		Head.addChild(headdecol6);
		Head.addChild(headdecol7);
		Head.addChild(headdecol8);
		Head.addChild(headdecol9);
		Head.addChild(headdecor1);
		Head.addChild(headdecor2);
		Head.addChild(headdecor3);
		Head.addChild(headdecor4);
		Head.addChild(headdecor5);
		Head.addChild(headdecor6);
		Head.addChild(headdecor7);
		Head.addChild(headdecor8);
		Head.addChild(headdecor9);
		Head.addChild(headdecor10);
		Head.addChild(headdecor11);
		Head.addChild(headdecor12);
		Head.addChild(headdecor13);
		Head.addChild(headdecor14);
		Head.addChild(horndecomain);
		Head.addChild(horndeco1);
		Head.addChild(horndeco2);
		Head.addChild(horndeco3);
		Head.addChild(horndeco4);
		Head.addChild(horndeco5);
		Head.addChild(horndeco6);
		Head.addChild(horndeco7);
		Head.addChild(horndeco8);
		Head.addChild(horndeco9);
		Head.addChild(horndeco11);
		Head.addChild(horndeco12);
		Head.addChild(horndeco13);
		Head.addChild(headbackl1);
		Head.addChild(headbackl2);
		Head.addChild(headbackmiddle);
		Head.addChild(headbackl12);
		Head.addChild(headbackr2);
		Head.addChild(LowerJawR1);
		Head.addChild(LowerJawR2);
		Head.addChild(LowerJawR3);
		Head.addChild(LowerJawR4);
		Head.addChild(LowerJawR5);
		Head.addChild(LowerJawR6);
		Head.addChild(LowerJawR7);
		Head.addChild(LowerJawR8);
		Head.addChild(LowerJawMiddle);
		Head.addChild(LowerJawL1);
		Head.addChild(LowerJawL2);
		Head.addChild(LowerJawL3);
		Head.addChild(LowerJawL4);
		Head.addChild(LowerJawL5);
		Head.addChild(LowerJawL6);
		Head.addChild(LowerJawL7);
		Head.addChild(LowerJawL8);
		Head.addChild(LowerJawL9);
		Head.addChild(LowerJawL10);
		Head.addChild(LowerJawPlateauThingy1);
		Head.addChild(LowerJawPlateauThingy2);
		Head.addChild(LowerJawPlateauThingy3);
		Head.addChild(LowerJawPlateauThingy4);
		Head.addChild(LowerJawPlateauThingy5);
		Body.addChild(Head);

		PixelmonModelRenderer Seg1 = new PixelmonModelRenderer(this,
				"Segment 1");
		Seg1.setRotationPoint(0, 2, 7);
		PixelmonModelRenderer rockpart1 = new PixelmonModelRenderer(this, 8,
				349);
		rockpart1.addBox(-4.933333F, -0.9333333F, -2.4F, 9, 9, 10);
		rockpart1.setRotationPoint(0F, -1.36666F, -2.9F);
		rockpart1.setTextureSize(512, 512);
		rockpart1.mirror = true;
		setRotation(rockpart1, -0.1570796F, -0.6981317F, -0.6108652F);
		PixelmonModelRenderer rockpart2 = new PixelmonModelRenderer(this, 19,
				318);
		rockpart2.addBox(-6.233333F, -2.533333F, -1.333333F, 11, 9, 10);
		rockpart2.setRotationPoint(0F, -0.7F, -2.9F);
		rockpart2.setTextureSize(512, 512);
		rockpart2.mirror = true;
		setRotation(rockpart2, -0.122173F, 0.0174533F, -0.1919862F);
		PixelmonModelRenderer rockpart3 = new PixelmonModelRenderer(this, 12,
				420);
		rockpart3.addBox(-3.933333F, -3.266667F, -1.733333F, 10, 9, 10);
		rockpart3.setRotationPoint(0F, -0.66667F, -2.9F);
		rockpart3.setTextureSize(512, 512);
		rockpart3.mirror = true;
		setRotation(rockpart3, -0.3839724F, -0.3490659F, 0.0523599F);
		PixelmonModelRenderer rockpart21 = new PixelmonModelRenderer(this, 19,
				318);
		rockpart21.addBox(-2.766667F, -1.533333F, -2.8F, 10, 9, 10);
		rockpart21.setRotationPoint(0F, -0.7F, -2.9F);
		rockpart21.setTextureSize(512, 512);
		rockpart21.mirror = true;
		setRotation(rockpart21, 0.1570796F, 0.2094395F, 1.134464F);
		Seg1.addChild(rockpart1);
		Seg1.addChild(rockpart2);
		Seg1.addChild(rockpart3);
		Seg1.addChild(rockpart21);
		Body.addChild(Seg1);

		PixelmonModelRenderer Seg2 = new PixelmonModelRenderer(this,
				"Segment 2");
		Seg2.setRotationPoint(0, 0, 13);
		PixelmonModelRenderer rockpart5 = new PixelmonModelRenderer(this, 6,
				101);
		rockpart5.addBox(-5.2F, -1.133333F, -4.2F, 9, 9, 10);
		rockpart5.setRotationPoint(0F, -0.3F, -3.6F);
		rockpart5.setTextureSize(512, 512);
		rockpart5.mirror = true;
		setRotation(rockpart5, 0.3141593F, -0.3665191F, -0.5934119F);
		PixelmonModelRenderer rockpart6 = new PixelmonModelRenderer(this, 1, 30);
		rockpart6.addBox(-4.633333F, -1.6F, -1.4F, 10, 9, 9);
		rockpart6.setRotationPoint(0F, -0.26667F, -3.6F);
		rockpart6.setTextureSize(512, 512);
		rockpart6.mirror = true;
		setRotation(rockpart6, -0.0523599F, -0.3316126F, -0.3839724F);
		PixelmonModelRenderer rockpart7 = new PixelmonModelRenderer(this, 9,
				424);
		rockpart7.addBox(-6.533333F, -0.9333333F, -0.7333333F, 11, 8, 9);
		rockpart7.setRotationPoint(0F, -1.16667F, -3.6F);
		rockpart7.setTextureSize(512, 512);
		rockpart7.mirror = true;
		setRotation(rockpart7, -0.3490659F, -0.1570796F, -0.4712389F);
		PixelmonModelRenderer rockpart8 = new PixelmonModelRenderer(this, 1, 30);
		rockpart8.addBox(-4.566667F, -1.6F, -0.8F, 10, 9, 9);
		rockpart8.setRotationPoint(0F, -0.26667F, -3.6F);
		rockpart8.setTextureSize(512, 512);
		rockpart8.mirror = true;
		setRotation(rockpart8, -0.0523599F, 0F, -0.0349066F);
		Seg2.addChild(rockpart5);
		Seg2.addChild(rockpart6);
		Seg2.addChild(rockpart7);
		Seg2.addChild(rockpart8);
		Seg1.addChild(Seg2);

		PixelmonModelRenderer Seg3 = new PixelmonModelRenderer(this,
				"Segment 3");
		Seg3.setRotationPoint(0, 0, 9);
		PixelmonModelRenderer rockpart9 = new PixelmonModelRenderer(this, 12,
				388);
		rockpart9.addBox(-2.433333F, -3.466667F, -0.06666667F, 7, 7, 7);
		rockpart9.setRotationPoint(0F, 3.5F, -3F);
		rockpart9.setTextureSize(512, 512);
		rockpart9.mirror = true;
		setRotation(rockpart9, 0F, 0F, -0.5934119F);
		PixelmonModelRenderer rockpart10 = new PixelmonModelRenderer(this, 4,
				166);
		rockpart10.addBox(-4.166667F, -1.2F, -1.333333F, 7, 8, 7);
		rockpart10.setRotationPoint(0F, 3.5F, -3F);
		rockpart10.setTextureSize(512, 512);
		rockpart10.mirror = true;
		setRotation(rockpart10, 0.5934119F, -0.0523599F, 4.258604F);
		PixelmonModelRenderer rockpart11 = new PixelmonModelRenderer(this, 4,
				166);
		rockpart11.addBox(-1.233333F, -5.2F, -1.333333F, 7, 8, 7);
		rockpart11.setRotationPoint(0F, 3.5F, -3F);
		rockpart11.setTextureSize(512, 512);
		rockpart11.mirror = true;
		setRotation(rockpart11, 0.122173F, -0.715585F, 0.3490659F);
		Seg3.addChild(rockpart9);
		Seg3.addChild(rockpart10);
		Seg3.addChild(rockpart11);
		Seg2.addChild(Seg3);

		PixelmonModelRenderer Seg4 = new PixelmonModelRenderer(this,
				"Segment 4");
		Seg4.setRotationPoint(0, 0, 9);
		PixelmonModelRenderer rockpart12 = new PixelmonModelRenderer(this, 9,
				231);
		rockpart12.addBox(-0.7666667F, -5.822222F, -2.866667F, 10, 11, 11);
		rockpart12.setRotationPoint(1F, 1.96667F, -4.3F);
		rockpart12.setTextureSize(512, 512);
		rockpart12.mirror = true;
		setRotation(rockpart12, -0.296706F, -1.169371F, 0.2792527F);
		PixelmonModelRenderer rockpart13 = new PixelmonModelRenderer(this, 2,
				446);
		rockpart13.addBox(-5.233333F, -3.666667F, -0.4666667F, 10, 10, 11);
		rockpart13.setRotationPoint(0F, 1F, -4.33333F);
		rockpart13.setTextureSize(512, 512);
		rockpart13.mirror = true;
		setRotation(rockpart13, 0F, 0F, -0.6068986F);
		PixelmonModelRenderer rockpart14 = new PixelmonModelRenderer(this, 2,
				446);
		rockpart14.addBox(-5.166667F, -4F, -0.4666667F, 10, 10, 11);
		rockpart14.setRotationPoint(0F, 1F, -4.33333F);
		rockpart14.setTextureSize(512, 512);
		rockpart14.mirror = true;
		setRotation(rockpart14, -0.2268928F, 0F, -0.2578327F);
		PixelmonModelRenderer rockpart15 = new PixelmonModelRenderer(this, 29,
				314);
		rockpart15.addBox(-6.233333F, -3.8F, -0.06666667F, 12, 10, 10);
		rockpart15.setRotationPoint(0F, 1F, -4.33333F);
		rockpart15.setTextureSize(512, 512);
		rockpart15.mirror = true;
		setRotation(rockpart15, -0.7330383F, -0.7679449F, -1.287577F);
		Seg4.addChild(rockpart12);
		Seg4.addChild(rockpart13);
		Seg4.addChild(rockpart14);
		Seg4.addChild(rockpart15);
		Seg3.addChild(Seg4);

		PixelmonModelRenderer Seg5 = new PixelmonModelRenderer(this,
				"Segment 5");
		Seg5.setRotationPoint(0, 0, 10);
		PixelmonModelRenderer rockpart16 = new PixelmonModelRenderer(this, 14,
				427);
		rockpart16.addBox(-7.166667F, -2.933333F, -5.733333F, 9, 8, 8);
		rockpart16.setRotationPoint(0F, 0.5F, -2.6F);
		rockpart16.setTextureSize(512, 512);
		rockpart16.mirror = true;
		setRotation(rockpart16, 0.0698132F, 2.338741F, 0F);
		PixelmonModelRenderer rockpart17 = new PixelmonModelRenderer(this, 14,
				427);
		rockpart17.addBox(-5.166667F, -1.666667F, -0.7333333F, 9, 8, 8);
		rockpart17.setRotationPoint(0F, 0.5F, -2.6F);
		rockpart17.setTextureSize(512, 512);
		rockpart17.mirror = true;
		setRotation(rockpart17, 0.1570796F, 0.2617994F, -0.2722714F);
		PixelmonModelRenderer rockpart18 = new PixelmonModelRenderer(this, 20,
				166);
		rockpart18.addBox(-3.7F, -0.3333333F, -4.066667F, 9, 8, 9);
		rockpart18.setRotationPoint(0F, 0.5F, -2.6F);
		rockpart18.setTextureSize(512, 512);
		rockpart18.mirror = true;
		setRotation(rockpart18, 1.047198F, 0F, 0F);
		Seg5.addChild(rockpart16);
		Seg5.addChild(rockpart17);
		Seg5.addChild(rockpart18);
		Seg4.addChild(Seg5);

		PixelmonModelRenderer Seg6 = new PixelmonModelRenderer(this,
				"Segment 6");
		Seg6.setRotationPoint(0, 0, 10);
		PixelmonModelRenderer rockpart19 = new PixelmonModelRenderer(this, -1,
				495);
		rockpart19.addBox(-4.9F, -2.933333F, -0.5333334F, 8, 8, 9);
		rockpart19.setRotationPoint(0F, 1.7F, -3.9F);
		rockpart19.setTextureSize(512, 512);
		rockpart19.mirror = true;
		setRotation(rockpart19, 0.1396263F, 0.418879F, 0.2268928F);
		PixelmonModelRenderer rockpart20 = new PixelmonModelRenderer(this, -1,
				494);
		rockpart20.addBox(-3.9F, -3.933333F, 0.4666667F, 8, 8, 9);
		rockpart20.setRotationPoint(0F, 1.7F, -3.9F);
		rockpart20.setTextureSize(512, 512);
		rockpart20.mirror = true;
		setRotation(rockpart20, 0F, 0.1919862F, 0.3141593F);
		PixelmonModelRenderer rockpart212 = new PixelmonModelRenderer(this, 27,
				303);
		rockpart212.addBox(-3.633333F, -4.066667F, 0.3333333F, 8, 7, 8);
		rockpart212.setRotationPoint(0F, 1.7F, -3.9F);
		rockpart212.setTextureSize(512, 512);
		rockpart212.mirror = true;
		setRotation(rockpart212, -0.1745329F, 0F, -0.2792527F);
		PixelmonModelRenderer rockpart22 = new PixelmonModelRenderer(this, 9,
				424);
		rockpart22.addBox(-3.366667F, -3.133333F, 0.2666667F, 8, 8, 9);
		rockpart22.setRotationPoint(0F, 1.7F, -3.9F);
		rockpart22.setTextureSize(512, 512);
		rockpart22.mirror = true;
		setRotation(rockpart22, 0.2094395F, 0.0523599F, 0.5934119F);
		Seg6.addChild(rockpart19);
		Seg6.addChild(rockpart20);
		Seg6.addChild(rockpart212);
		Seg6.addChild(rockpart22);
		Seg5.addChild(Seg6);

		PixelmonModelRenderer Seg7 = new PixelmonModelRenderer(this,
				"Segment 7");
		Seg7.setRotationPoint(0, 0, 8);
		PixelmonModelRenderer rockpart222 = new PixelmonModelRenderer(this, 6,
				479);
		rockpart222.addBox(-4.233333F, -4.4F, 0.2F, 7, 7, 6);
		rockpart222.setRotationPoint(0F, 2.7F, -2F);
		rockpart222.setTextureSize(512, 512);
		rockpart222.mirror = true;
		setRotation(rockpart222, -0.1047198F, 0.4014257F, 0.5585054F);
		PixelmonModelRenderer rockpart23 = new PixelmonModelRenderer(this, 7,
				478);
		rockpart23.addBox(-1.233333F, -2.4F, -0.8F, 7, 7, 6);
		rockpart23.setRotationPoint(0F, 2.7F, -2F);
		rockpart23.setTextureSize(512, 512);
		rockpart23.mirror = true;
		setRotation(rockpart23, 0.1047198F, -0.4014257F, -0.5585054F);
		PixelmonModelRenderer rockpart24 = new PixelmonModelRenderer(this, 20,
				262);
		rockpart24.addBox(-2.566667F, -3.4F, -0.7333333F, 7, 7, 7);
		rockpart24.setRotationPoint(0F, 2.7F, -2F);
		rockpart24.setTextureSize(512, 512);
		rockpart24.mirror = true;
		setRotation(rockpart24, 0.0872665F, -0.0349066F, 0.0174533F);
		Seg7.addChild(rockpart222);
		Seg7.addChild(rockpart23);
		Seg7.addChild(rockpart24);
		Seg6.addChild(Seg7);

		PixelmonModelRenderer Seg8 = new PixelmonModelRenderer(this,
				"Segment 8");
		Seg8.setRotationPoint(0, 0, 7);
		PixelmonModelRenderer rockpart25 = new PixelmonModelRenderer(this, 488,
				34);
		rockpart25.addBox(-3.4F, -2.6F, -0.6F, 6, 6, 6);
		rockpart25.setRotationPoint(0F, 2F, -2F);
		rockpart25.setTextureSize(512, 512);
		rockpart25.mirror = true;
		setRotation(rockpart25, 0.4363323F, 0.296706F, -1.082104F);
		PixelmonModelRenderer rockpart26 = new PixelmonModelRenderer(this, 19,
				39);
		rockpart26.addBox(-4.5F, -2.6F, -1.4F, 6, 6, 6);
		rockpart26.setRotationPoint(0F, 1F, -2F);
		rockpart26.setTextureSize(512, 512);
		rockpart26.mirror = true;
		setRotation(rockpart26, -0.2094395F, 0.715585F, -0.122173F);
		PixelmonModelRenderer rockpart27 = new PixelmonModelRenderer(this, 19,
				39);
		rockpart27.addBox(-3.5F, -2F, -0.4F, 6, 6, 6);
		rockpart27.setRotationPoint(0F, 1F, -2F);
		rockpart27.setTextureSize(512, 512);
		rockpart27.mirror = true;
		setRotation(rockpart27, 0.0698132F, 0.2012946F, -0.122173F);
		Seg8.addChild(rockpart25);
		Seg8.addChild(rockpart26);
		Seg8.addChild(rockpart27);
		Seg7.addChild(Seg8);

		PixelmonModelRenderer Seg9 = new PixelmonModelRenderer(this,
				"Segment 9");
		Seg9.setRotationPoint(0, 0, 6);
		PixelmonModelRenderer rockpart28 = new PixelmonModelRenderer(this, 484,
				4);
		rockpart28.addBox(-3.266667F, -1.066667F, -0.6666667F, 6, 5, 5);
		rockpart28.setRotationPoint(0F, 1.8F, -1.5F);
		rockpart28.setTextureSize(512, 512);
		rockpart28.mirror = true;
		setRotation(rockpart28, 0.5934119F, 0.4049164F, -0.2792527F);
		PixelmonModelRenderer rockpart29 = new PixelmonModelRenderer(this, 490,
				62);
		rockpart29.addBox(-1.733333F, -2.8F, -0.4666667F, 5, 6, 5);
		rockpart29.setRotationPoint(0F, 1.8F, -1.5F);
		rockpart29.setTextureSize(512, 512);
		rockpart29.mirror = true;
		setRotation(rockpart29, 0F, -0.0523599F, 0F);
		PixelmonModelRenderer rockpart30 = new PixelmonModelRenderer(this, 484,
				4);
		rockpart30.addBox(-2.266667F, -3.066667F, -0.6666667F, 6, 5, 5);
		rockpart30.setRotationPoint(0F, 1.8F, -1.5F);
		rockpart30.setTextureSize(512, 512);
		rockpart30.mirror = true;
		setRotation(rockpart30, 0.0174533F, -0.4014257F, 0.418879F);
		Seg9.addChild(rockpart28);
		Seg9.addChild(rockpart29);
		Seg9.addChild(rockpart30);
		Seg8.addChild(Seg9);

		PixelmonModelRenderer Seg10 = new PixelmonModelRenderer(this,
				"Segment 10");
		Seg10.setRotationPoint(0, 0, 5);
		PixelmonModelRenderer rockpart31 = new PixelmonModelRenderer(this, 472,
				4);
		rockpart31.addBox(-0.5333334F, -2.366667F, -3.933333F, 5, 4, 5);
		rockpart31.setRotationPoint(0F, 2F, -1.4F);
		rockpart31.setTextureSize(512, 512);
		rockpart31.mirror = true;
		setRotation(rockpart31, -2.70526F, -0.6632251F, 0.0698132F);
		PixelmonModelRenderer rockpart32 = new PixelmonModelRenderer(this, 419,
				0);
		rockpart32.addBox(-3.566667F, -0.3333333F, -2.766667F, 5, 5, 5);
		rockpart32.setRotationPoint(0.4666667F, 2F, -1.4F);
		rockpart32.setTextureSize(512, 512);
		rockpart32.mirror = true;
		setRotation(rockpart32, 1.518436F, 0.4014257F, 0.2268928F);
		PixelmonModelRenderer rockpart33 = new PixelmonModelRenderer(this, 419,
				0);
		rockpart33.addBox(-2.566667F, -3.133333F, -0.6333333F, 5, 5, 5);
		rockpart33.setRotationPoint(0.4666667F, 2F, -1.4F);
		rockpart33.setTextureSize(512, 512);
		rockpart33.mirror = true;
		setRotation(rockpart33, -0.2443461F, 0F, 0F);
		Seg10.addChild(rockpart31);
		Seg10.addChild(rockpart32);
		Seg10.addChild(rockpart33);
		Seg9.addChild(Seg10);

		PixelmonModelRenderer Seg11 = new PixelmonModelRenderer(this,
				"Segment 11");
		Seg11.setRotationPoint(0, 0, 5);
		PixelmonModelRenderer rockpart34 = new PixelmonModelRenderer(this, 1,
				291);
		rockpart34.addBox(-2.266667F, -2.2F, 0.4666667F, 4, 3, 4);
		rockpart34.setRotationPoint(0F, 2.7F, -1.1F);
		rockpart34.setTextureSize(512, 512);
		rockpart34.mirror = true;
		setRotation(rockpart34, 0F, -0.0174533F, -0.0523599F);
		PixelmonModelRenderer rockpart35 = new PixelmonModelRenderer(this, 16,
				291);
		rockpart35.addBox(-2.5F, -2.866667F, 0.9333333F, 4, 4, 3);
		rockpart35.setRotationPoint(0F, 2.7F, -1.1F);
		rockpart35.setTextureSize(512, 512);
		rockpart35.mirror = true;
		setRotation(rockpart35, -0.1919862F, 0.1745329F, -0.2094395F);
		PixelmonModelRenderer rockpart36 = new PixelmonModelRenderer(this, 3,
				325);
		rockpart36.addBox(-1.333333F, -2.133333F, -0.1333333F, 4, 4, 4);
		rockpart36.setRotationPoint(0F, 2.7F, -1.1F);
		rockpart36.setTextureSize(512, 512);
		rockpart36.mirror = true;
		setRotation(rockpart36, 0.0174533F, -0.5235988F, -0.296706F);
		Seg11.addChild(rockpart34);
		Seg11.addChild(rockpart35);
		Seg11.addChild(rockpart36);
		Seg10.addChild(Seg11);

		PixelmonModelRenderer Seg12 = new PixelmonModelRenderer(this,
				"Segment 12");
		Seg12.setRotationPoint(0, 0, 5);
		PixelmonModelRenderer rockpart37 = new PixelmonModelRenderer(this, 4,
				370);
		rockpart37.addBox(-1.733333F, -1.8F, -0.1F, 3, 3, 3);
		rockpart37.setRotationPoint(0F, 3.1F, -1.3F);
		rockpart37.setTextureSize(512, 512);
		rockpart37.mirror = true;
		setRotation(rockpart37, 0.296706F, 0.0698132F, -0.0349066F);
		PixelmonModelRenderer rockpart38 = new PixelmonModelRenderer(this, 0,
				399);
		rockpart38.addBox(-2.333333F, -1.333333F, -0.3666667F, 4, 2, 3);
		rockpart38.setRotationPoint(0F, 3.1F, -1.3F);
		rockpart38.setTextureSize(512, 512);
		rockpart38.mirror = true;
		setRotation(rockpart38, -0.0698132F, 0F, -0.2792527F);
		PixelmonModelRenderer rockpart39 = new PixelmonModelRenderer(this, 4,
				370);
		rockpart39.addBox(-1.733333F, -1.8F, -0.1F, 3, 3, 3);
		rockpart39.setRotationPoint(0F, 3.1F, -1.3F);
		rockpart39.setTextureSize(512, 512);
		rockpart39.mirror = true;
		setRotation(rockpart39, 0.296706F, -0.2094395F, 0.2094395F);
		Seg12.addChild(rockpart37);
		Seg12.addChild(rockpart38);
		Seg12.addChild(rockpart39);
		Seg11.addChild(Seg12);

		PixelmonModelRenderer Seg13 = new PixelmonModelRenderer(this,
				"Segment 13");
		Seg13.setRotationPoint(0, 0, 2);
		PixelmonModelRenderer tailrock1 = new PixelmonModelRenderer(this, 33,
				330);
		tailrock1.addBox(-0.7F, -0.4F, 0.3F, 1, 1, 1);
		tailrock1.setRotationPoint(0F, 2.2F, -0.7F);
		tailrock1.setTextureSize(512, 512);
		tailrock1.mirror = true;
		setRotation(tailrock1, 0F, 0.1047198F, -0.1570796F);
		PixelmonModelRenderer tailrock2 = new PixelmonModelRenderer(this, 29,
				187);
		tailrock2.addBox(-0.6666667F, -0.4F, 0.2F, 1, 1, 1);
		tailrock2.setRotationPoint(0F, 2.2F, -0.7F);
		tailrock2.setTextureSize(512, 512);
		tailrock2.mirror = true;
		setRotation(tailrock2, -0.0349066F, -0.0698132F, 0.2792527F);
		PixelmonModelRenderer tailrock3 = new PixelmonModelRenderer(this, 7, 46);
		tailrock3.addBox(-1F, -0.4F, 1F, 2, 1, 3);
		tailrock3.setRotationPoint(0F, 2.2F, -0.7F);
		tailrock3.setTextureSize(512, 512);
		tailrock3.mirror = true;
		setRotation(tailrock3, 0F, 0F, 0.616683F);
		PixelmonModelRenderer tailrock4 = new PixelmonModelRenderer(this, 45,
				370);
		tailrock4.addBox(-1F, -0.4F, 1.1F, 2, 1, 3);
		tailrock4.setRotationPoint(0F, 2.2F, -0.7F);
		tailrock4.setTextureSize(512, 512);
		tailrock4.mirror = true;
		setRotation(tailrock4, 0F, 0F, -0.7679449F);
		PixelmonModelRenderer tailrock5 = new PixelmonModelRenderer(this, 64,
				362);
		tailrock5.addBox(-0.45F, -0.4F, 4.2F, 1, 1, 1);
		tailrock5.setRotationPoint(0F, 2.2F, -0.7F);
		tailrock5.setTextureSize(512, 512);
		tailrock5.mirror = true;
		setRotation(tailrock5, 0F, 0F, 0.1396263F);
		PixelmonModelRenderer tailrock6 = new PixelmonModelRenderer(this, 67,
				373);
		tailrock6.addBox(-0.4666667F, -0.4F, 4.1F, 1, 1, 1);
		tailrock6.setRotationPoint(0F, 2.2F, -0.7F);
		tailrock6.setTextureSize(512, 512);
		tailrock6.mirror = true;
		setRotation(tailrock6, 0F, 0F, -0.1570796F);
		Seg13.addChild(tailrock1);
		Seg13.addChild(tailrock2);
		Seg13.addChild(tailrock3);
		Seg13.addChild(tailrock4);
		Seg13.addChild(tailrock5);
		Seg13.addChild(tailrock6);
		Seg12.addChild(Seg13);

		ModuleHead headModule = new ModuleHead(Head);
		ModelRenderer[] bodyArgs = {Seg1, Seg2, Seg3, Seg4, Seg5, Seg6, Seg7,
				Seg8, Seg9, Seg10, Seg11, Seg12, Seg13 };
		
		setRotation(Seg1, 0F, (float) (30*(Math.PI)/180),0F);
		setRotation(Seg2, 0F, (float) (-30*(Math.PI)/180),0F);
		
		float animationAngle = 0;
		float topAngle = (float) (Math.PI/5);
		float dampeningFactor = (float) -1/12;
		float animationSpeed = (float) 1/2;
		float phaseoffset = (float) -1;		
		
		skeleton = new SkeletonSerpent(Body, headModule, animationAngle, topAngle, dampeningFactor, animationSpeed,phaseoffset, bodyArgs);

	}

	public void render(Entity entity, float f, float f1, float f2, float f3,
			float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5);
		Body.render(f5);
	}

	private void setRotation(PixelmonModelRenderer model, float x, float y,
			float z) {

		model.rotateAngleX = x;
		model.rotateAngleZ = z;
		model.rotateAngleY = y;

	}

	public void setRotationAngles(float f, float f1, float f2, float f3,
			float f4, float f5) {
	}

}
