// Date: 5/20/2013 11:19:55 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package pixelmon.client.models.pokemon;

import net.minecraft.entity.Entity;
import pixelmon.client.models.PixelmonModelBase;
import pixelmon.client.models.PixelmonModelRenderer;
import pixelmon.client.models.animations.EnumLeg;
import pixelmon.client.models.animations.EnumPhase;
import pixelmon.client.models.animations.ModuleHead;
import pixelmon.client.models.animations.ModuleLeg;
import pixelmon.client.models.animations.quadruped.SkeletonQuadruped;

public class ModelNidoranmale extends PixelmonModelBase
{
  //fields
    PixelmonModelRenderer Body;
  
  public ModelNidoranmale()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Body = new PixelmonModelRenderer(this, "Body");
      Body.setRotationPoint(0, 17, -3);
      
      PixelmonModelRenderer Head = new PixelmonModelRenderer(this, "Head");
      Head.setRotationPoint(0,0,0);
      PixelmonModelRenderer left_eye = new PixelmonModelRenderer(this, 56, 0);
      left_eye.addBox(2.8F, -0.5F, -3.8F, 1, 2, 3);
      left_eye.setTextureSize(64, 32);
      left_eye.mirror = true;
      setRotation(left_eye, 0.2663372F, 0.418879F, 0F);
      PixelmonModelRenderer head_top_2 = new PixelmonModelRenderer(this, 23, 12);
      head_top_2.addBox(-2F, 0F, -2.2F, 4, 3, 1);
      head_top_2.setTextureSize(64, 32);
      head_top_2.mirror = true;
      setRotation(head_top_2, -1.326244F, 0F, 0F);
      PixelmonModelRenderer brow_right = new PixelmonModelRenderer(this, 19, 0);
      brow_right.addBox(-3F, -3.2F, -4.1F, 2, 2, 3);
      brow_right.setTextureSize(64, 32);
      brow_right.mirror = true;
      setRotation(brow_right, 0.6995775F, -0.158633F, -0.2511703F);
      PixelmonModelRenderer head_front = new PixelmonModelRenderer(this, 32, 7);
      head_front.addBox(-2F, 0.8F, -5.3F, 4, 2, 1);
      head_front.setTextureSize(64, 32);
      head_front.mirror = true;
      setRotation(head_front, 0F, 0F, 0F);
      PixelmonModelRenderer head_front_2 = new PixelmonModelRenderer(this, 48, 15);
      head_front_2.addBox(-2F, 0.7F, -5.9F, 4, 2, 4);
      head_front_2.setTextureSize(64, 32);
      head_front_2.mirror = true;
      setRotation(head_front_2, 0.3839724F, 0F, 0F);
      PixelmonModelRenderer snout_2 = new PixelmonModelRenderer(this, 35, 11);
      snout_2.addBox(-1F, -2.9F, -6.5F, 2, 2, 2);
      snout_2.setTextureSize(64, 32);
      snout_2.mirror = true;
      setRotation(snout_2, 0.904473F, 0F, 0F);
      PixelmonModelRenderer snout_bridge_ = new PixelmonModelRenderer(this, 33, 6);
      snout_bridge_.addBox(-1F, 0.6F, -5.6F, 2, 2, 1);
      snout_bridge_.setTextureSize(64, 32);
      snout_bridge_.mirror = true;
      setRotation(snout_bridge_, 0.0030982F, 0F, 0F);
      PixelmonModelRenderer jaw_left = new PixelmonModelRenderer(this, 50, 15);
      jaw_left.addBox(-4F, 0.6F, -4.7F, 3, 2, 4);
      jaw_left.setTextureSize(64, 32);
      jaw_left.mirror = true;
      setRotation(jaw_left, 0.3839724F, -0.3665191F, -0.1396263F);
      PixelmonModelRenderer forehead = new PixelmonModelRenderer(this, 31, 1);
      forehead.addBox(-1.5F, 1.6F, -3.2F, 3, 3, 3);
      forehead.setTextureSize(64, 32);
      forehead.mirror = true;
      setRotation(forehead, -0.8566572F, 0F, 0F);
      PixelmonModelRenderer snout = new PixelmonModelRenderer(this, 36, 13);
      snout.addBox(-0.5F, 0.7F, -7.1F, 1, 1, 1);
      snout.setTextureSize(64, 32);
      snout.mirror = true;
      setRotation(snout, 0.3839724F, 0F, 0F);
      PixelmonModelRenderer jaw_line_right = new PixelmonModelRenderer(this, 50, 17);
      jaw_line_right.addBox(-3.99F, 0.7F, -1.133333F, 3, 2, 2);
      jaw_line_right.setTextureSize(64, 32);
      jaw_line_right.mirror = true;
      setRotation(jaw_line_right, -0.2108853F, -0.3665191F, -0.1396263F);
      PixelmonModelRenderer head_top_1 = new PixelmonModelRenderer(this, 21, 10);
      head_top_1.addBox(-2.5F, -0.5F, -2.1F, 5, 4, 2);
      head_top_1.setTextureSize(64, 32);
      head_top_1.mirror = true;
      setRotation(head_top_1, -1.326244F, 0F, 0F);
      PixelmonModelRenderer brow_left = new PixelmonModelRenderer(this, 19, 0);
      brow_left.addBox(1F, -3.2F, -4.1F, 2, 2, 3);
      brow_left.setTextureSize(64, 32);
      brow_left.mirror = true;
      setRotation(brow_left, 0.6995775F, 0.1586287F, 0.2511622F);
      PixelmonModelRenderer temple_right = new PixelmonModelRenderer(this, 54, 16);
      temple_right.addBox(-3.4F, -0.7F, -1.1F, 2, 3, 2);
      temple_right.setTextureSize(64, 32);
      temple_right.mirror = true;
      setRotation(temple_right, -0.2131574F, -0.2876128F, 0.2693392F);
      PixelmonModelRenderer temple_left = new PixelmonModelRenderer(this, 54, 16);
      temple_left.addBox(1.4F, -0.7F, -1.1F, 2, 3, 2);
      temple_left.setTextureSize(64, 32);
      temple_left.mirror = true;
      setRotation(temple_left, -0.2131574F, 0.2876179F, -0.2693384F);
      PixelmonModelRenderer jaw_line_left = new PixelmonModelRenderer(this, 50, 17);
      jaw_line_left.addBox(0.99F, 0.7F, -1.133333F, 3, 2, 2);
      jaw_line_left.setTextureSize(64, 32);
      jaw_line_left.mirror = true;
      setRotation(jaw_line_left, -0.2108853F, 0.3665191F, 0.1396263F);
      PixelmonModelRenderer jaw_left2 = new PixelmonModelRenderer(this, 50, 15);
      jaw_left2.addBox(1F, 0.6F, -4.7F, 3, 2, 4);
      jaw_left2.setTextureSize(64, 32);
      jaw_left2.mirror = true;
      setRotation(jaw_left2, 0.3839724F, 0.3665191F, 0.1396263F);
      PixelmonModelRenderer horn = new PixelmonModelRenderer(this, 56, 10);
      horn.addBox(-0.5F, -0.4F, -6.8F, 1, 1, 3);
      horn.setTextureSize(64, 32);
      horn.mirror = true;
      setRotation(horn, -0.115357F, 0F, 0F);
      PixelmonModelRenderer right_eye = new PixelmonModelRenderer(this, 56, 0);
      right_eye.addBox(-3.8F, -0.5F, -3.8F, 1, 2, 3);
      right_eye.setTextureSize(64, 32);
      right_eye.mirror = true;
      setRotation(right_eye, 0.2663372F, -0.418879F, 0F);
      PixelmonModelRenderer horntip = new PixelmonModelRenderer(this, 58, 8);
      horntip.addBox(-1F, -0.4F, -7.8F, 1, 1, 1);
      horntip.setTextureSize(64, 32);
      horntip.mirror = true;
      setRotation(horntip, -0.115357F, 0F, 0F);
      PixelmonModelRenderer tooth = new PixelmonModelRenderer(this, 57, 5);
      tooth.addBox(-0.99F, 1.4F, -6.8F, 2, 2, 1);
      tooth.setTextureSize(64, 32);
      tooth.mirror = true;
      setRotation(tooth, 0.3839724F, 0F, 0F);
      PixelmonModelRenderer left_ear_2 = new PixelmonModelRenderer(this, 32, 17);
      left_ear_2.addBox(1.89F, -8.2F, -2.8F, 1, 2, 3);
      left_ear_2.setTextureSize(64, 32);
      left_ear_2.mirror = true;
      setRotation(left_ear_2, -0.2792527F, 0.2094395F, 0.3490659F);
      PixelmonModelRenderer left_ear_3 = new PixelmonModelRenderer(this, 33, 17);
      left_ear_3.addBox(1.9F, -9.1F, -2F, 1, 1, 2);
      left_ear_3.setTextureSize(64, 32);
      left_ear_3.mirror = true;
      setRotation(left_ear_3, -0.2792527F, 0.2094395F, 0.3490659F);
      PixelmonModelRenderer left_ear_base = new PixelmonModelRenderer(this, 32, 18);
      left_ear_base.addBox(1.89F, -3.2F, -3F, 1, 2, 3);
      left_ear_base.setTextureSize(64, 32);
      left_ear_base.mirror = true;
      setRotation(left_ear_base, -0.2792527F, 0.2094395F, 0.3490659F);
      PixelmonModelRenderer left_ear_1 = new PixelmonModelRenderer(this, 30, 15);
      left_ear_1.addBox(1.89F, -6.2F, -3.5F, 1, 3, 4);
      left_ear_1.setTextureSize(64, 32);
      left_ear_1.mirror = true;
      setRotation(left_ear_1, -0.2792527F, 0.2094395F, 0.3490659F);
      PixelmonModelRenderer lefteartransparent = new PixelmonModelRenderer(this, 44, 0);
      lefteartransparent.addBox(1.99F, -11.2F, -4F, 1, 10, 5);
      lefteartransparent.setTextureSize(64, 32);
      lefteartransparent.mirror = true;
      setRotation(lefteartransparent, -0.2792527F, 0.2094395F, 0.3490659F);
      PixelmonModelRenderer right_ear_3 = new PixelmonModelRenderer(this, 33, 17);
      right_ear_3.addBox(-2.9F, -9.1F, -2F, 1, 1, 2);
      right_ear_3.setTextureSize(64, 32);
      right_ear_3.mirror = true;
      setRotation(right_ear_3, -0.2792527F, -0.2094395F, -0.3490659F);
      PixelmonModelRenderer right_ear_base = new PixelmonModelRenderer(this, 32, 18);
      right_ear_base.addBox(-2.9F, -3.2F, -3F, 1, 2, 3);
      right_ear_base.setTextureSize(64, 32);
      right_ear_base.mirror = true;
      setRotation(right_ear_base, -0.2792527F, -0.2094395F, -0.3490659F);
      PixelmonModelRenderer right_ear_2 = new PixelmonModelRenderer(this, 30, 15);
      right_ear_2.addBox(-2.9F, -8.2F, -2.8F, 1, 2, 3);
      right_ear_2.setTextureSize(64, 32);
      right_ear_2.mirror = true;
      setRotation(right_ear_2, -0.2792527F, -0.2094395F, -0.3490659F);
      PixelmonModelRenderer right_ear_1 = new PixelmonModelRenderer(this, 30, 15);
      right_ear_1.addBox(-2.9F, -6.2F, -3.5F, 1, 3, 4);
      right_ear_1.setTextureSize(64, 32);
      right_ear_1.mirror = true;
      setRotation(right_ear_1, -0.2792527F, -0.2094395F, -0.3490659F);
      PixelmonModelRenderer righteartransparent = new PixelmonModelRenderer(this, 44, 0);
      righteartransparent.addBox(-4F, -11.2F, -4F, 1, 10, 5);
      righteartransparent.setTextureSize(64, 32);
      righteartransparent.mirror = true;
      setRotation(righteartransparent, -0.2792527F, -0.2094395F, -0.3490659F);
      Head.addChild(left_eye);
      Head.addChild(head_top_2);
      Head.addChild(brow_right);
      Head.addChild(head_front);
      Head.addChild(head_front_2);
      Head.addChild(snout_2);
      Head.addChild(snout_bridge_);
      Head.addChild(jaw_left);
      Head.addChild(forehead);
      Head.addChild(snout);
      Head.addChild(jaw_line_right);
      Head.addChild(head_top_1);
      Head.addChild(brow_left);
      Head.addChild(temple_right);
      Head.addChild(temple_left);
      Head.addChild(jaw_line_left);
      Head.addChild(jaw_left2);
      Head.addChild(horn);
      Head.addChild(right_eye);
      Head.addChild(horntip);
      Head.addChild(tooth);
      Head.addChild(left_ear_2);
      Head.addChild(left_ear_3);
      Head.addChild(left_ear_base);
      Head.addChild(left_ear_1);
      Head.addChild(lefteartransparent);
      Head.addChild(right_ear_3);
      Head.addChild(right_ear_base);
      Head.addChild(right_ear_2);
      Head.addChild(right_ear_1);
      Head.addChild(righteartransparent);
      Body.addChild(Head);
      
      
      
      PixelmonModelRenderer leftspikes = new PixelmonModelRenderer(this, 0, 14);
      leftspikes.addBox(1F, -3.5F, 3F, 1, 4, 6);
      leftspikes.setTextureSize(64, 32);
      leftspikes.mirror = true;
      setRotation(leftspikes, -0.2138028F, 0.2094395F, 0F);
      PixelmonModelRenderer spinespikes = new PixelmonModelRenderer(this, 0, 0);
      spinespikes.addBox(-1F, -7F, 2F, 1, 7, 7);
      spinespikes.setTextureSize(64, 32);
      spinespikes.mirror = true;
      setRotation(spinespikes, -0.2617994F, 0F, 0F);
      PixelmonModelRenderer nido_back_1 = new PixelmonModelRenderer(this, 46, 22);
      nido_back_1.addBox(-2.5F, -0.4333333F, -4F, 5, 4, 4);
      nido_back_1.setTextureSize(64, 32);
      nido_back_1.mirror = true;
      setRotation(nido_back_1, 1.682332F, 0F, 0F);
      PixelmonModelRenderer throat = new PixelmonModelRenderer(this, 46, 25);
      throat.addBox(-2.5F, -0.1666667F, -4.6F, 5, 3, 4);
      throat.setTextureSize(64, 32);
      throat.mirror = true;
      setRotation(throat, 1.087474F, 0F, 0F);
      PixelmonModelRenderer neck = new PixelmonModelRenderer(this, 47, 22);
      neck.addBox(-2F, -2.5F, -1.833333F, 4, 4, 4);
      neck.setTextureSize(64, 32);
      neck.mirror = true;
      setRotation(neck, -2.176085F, 0F, 0F);
      PixelmonModelRenderer nido_back_2 = new PixelmonModelRenderer(this, 47, 24);
      nido_back_2.addBox(-2.5F, 3.1F, -1.3F, 5, 3, 3);
      nido_back_2.setTextureSize(64, 32);
      nido_back_2.mirror = true;
      setRotation(nido_back_2, 1.181557F, 0F, 0F);
      PixelmonModelRenderer nido_back_3 = new PixelmonModelRenderer(this, 47, 24);
      nido_back_3.addBox(-2.5F, 4.1F, 1.8F, 5, 3, 3);
      nido_back_3.setTextureSize(64, 32);
      nido_back_3.mirror = true;
      setRotation(nido_back_3, 0.5866991F, 0F, 0F);
      PixelmonModelRenderer nido_body_1 = new PixelmonModelRenderer(this, 25, 24);
      nido_body_1.addBox(-3F, 1.3F, -1.5F, 6, 3, 5);
      nido_body_1.setTextureSize(64, 32);
      nido_body_1.mirror = true;
      setRotation(nido_body_1, 0.111544F, 0F, 0F);
      PixelmonModelRenderer nido_body_2 = new PixelmonModelRenderer(this, 27, 24);
      nido_body_2.addBox(-2.99F, 3.7F, -2.4F, 6, 3, 3);
      nido_body_2.setTextureSize(64, 32);
      nido_body_2.mirror = true;
      setRotation(nido_body_2, 1.181557F, 0F, 0F);
      PixelmonModelRenderer chest = new PixelmonModelRenderer(this, 47, 25);
      chest.addBox(-2.5F, 1.1F, -5.4F, 5, 4, 3);
      chest.setTextureSize(64, 32);
      chest.mirror = true;
      setRotation(chest, 1.422082F, 0F, 0F);
      PixelmonModelRenderer belly = new PixelmonModelRenderer(this, 47, 27);
      belly.addBox(-2.5F, 4.766667F, 2.9F, 5, 2, 3);
      belly.setTextureSize(64, 32);
      belly.mirror = true;
      setRotation(belly, 0.1858931F, 0F, 0F);
      PixelmonModelRenderer crotch = new PixelmonModelRenderer(this, 49, 30);
      crotch.addBox(-2.5F, -3.9F, 7.4F, 5, 1, 1);
      crotch.setTextureSize(64, 32);
      crotch.mirror = true;
      setRotation(crotch, -1.031706F, 0F, 0F);
      PixelmonModelRenderer butt = new PixelmonModelRenderer(this, 46, 26);
      butt.addBox(-2.5F, 2.4F, 4.2F, 5, 2, 4);
      butt.setTextureSize(64, 32);
      butt.mirror = true;
      setRotation(butt, -0.1022412F, 0F, 0F);
      PixelmonModelRenderer rightspikes = new PixelmonModelRenderer(this, 0, 14);
      rightspikes.addBox(-3F, -3.5F, 3F, 1, 4, 6);
      rightspikes.setTextureSize(64, 32);
      rightspikes.mirror = true;
      setRotation(rightspikes, -0.2138028F, -0.2094395F, 0F);
      Body.addChild(leftspikes);
      Body.addChild(spinespikes);
      Body.addChild(nido_back_1);
      Body.addChild(throat);
      Body.addChild(neck);
      Body.addChild(nido_back_2);
      Body.addChild(nido_back_3);
      Body.addChild(nido_body_1);
      Body.addChild(nido_body_2);
      Body.addChild(chest);
      Body.addChild(belly);
      Body.addChild(crotch);
      Body.addChild(butt);
      Body.addChild(rightspikes);
      
      
      
      PixelmonModelRenderer FRLeg = new PixelmonModelRenderer(this, "Front Right Leg");
      FRLeg.setRotationPoint(-1.4F, 3, 1);
      PixelmonModelRenderer  right_forewrist = new PixelmonModelRenderer(this, 3, 26);
      right_forewrist.addBox(-2.5F, 0.8666667F, -0.1F, 2, 3, 2);
      right_forewrist.setTextureSize(64, 32);
      right_forewrist.mirror = true;
      setRotation(right_forewrist, -0.7990178F, 0.0363203F, 0F);
      PixelmonModelRenderer  right_front_toe_2 = new PixelmonModelRenderer(this, 17, 29);
      right_front_toe_2.addBox(-2.7F, 3F, -3.4F, 1, 1, 2);
      right_front_toe_2.setTextureSize(64, 32);
      right_front_toe_2.mirror = true;
      setRotation(right_front_toe_2, 0F, 0F, 0F);
      PixelmonModelRenderer  right_front_toe_1 = new PixelmonModelRenderer(this, 17, 29);
      right_front_toe_1.addBox(-1.6F, 3F, -3.4F, 1, 1, 2);
      right_front_toe_1.setTextureSize(64, 32);
      right_front_toe_1.mirror = true;
      setRotation(right_front_toe_1, 0F, 0F, 0F);
      PixelmonModelRenderer  right_foreleg_2 = new PixelmonModelRenderer(this, 1, 26);
      right_foreleg_2.addBox(-2.4F, 0.5F, -0.5F, 3, 2, 2);
      right_foreleg_2.setTextureSize(64, 32);
      right_foreleg_2.mirror = true;
      setRotation(right_foreleg_2, -0.5222198F, 0.1570796F, 0.1555263F);
      PixelmonModelRenderer  right_foreleg = new PixelmonModelRenderer(this, 0, 24);
      right_foreleg.addBox(-2.3F, 0F, -1F, 3, 3, 3);
      right_foreleg.setTextureSize(64, 32);
      right_foreleg.mirror = true;
      setRotation(right_foreleg, -0.5222198F, 0.1570796F, 0.1555263F);
      FRLeg.addChild(right_forewrist);
      FRLeg.addChild(right_front_toe_2);
      FRLeg.addChild(right_front_toe_1);
      FRLeg.addChild(right_foreleg_2);
      FRLeg.addChild(right_foreleg);
      Body.addChild(FRLeg);
      
      PixelmonModelRenderer FLLeg = new PixelmonModelRenderer(this, "Front Left Leg");
      FLLeg.setRotationPoint(1.4F, 3, 1);
      PixelmonModelRenderer   Left_foreleg = new PixelmonModelRenderer(this, 0, 24);
      Left_foreleg.addBox(-0.7F, 0F, -1F, 3, 3, 3);
      Left_foreleg.setTextureSize(64, 32);
      Left_foreleg.mirror = true;
      setRotation(Left_foreleg, -0.5222198F, -0.1570796F, -0.1555305F);
      PixelmonModelRenderer   left_forewrist = new PixelmonModelRenderer(this, 3, 26);
      left_forewrist.addBox(0.5F, 0.9F, -0.1F, 2, 3, 2);
      left_forewrist.setTextureSize(64, 32);
      left_forewrist.mirror = true;
      setRotation(left_forewrist, -0.7990178F, -0.036319F, 0F);
      PixelmonModelRenderer   Left_foreleg_2 = new PixelmonModelRenderer(this, 1, 26);
      Left_foreleg_2.addBox(-0.6F, 0.5F, -0.5F, 3, 2, 2);
      Left_foreleg_2.setTextureSize(64, 32);
      Left_foreleg_2.mirror = true;
      setRotation(Left_foreleg_2, -0.5222198F, -0.1570796F, -0.1555305F);
      PixelmonModelRenderer   left_front_toe_2 = new PixelmonModelRenderer(this, 17, 29);
      left_front_toe_2.addBox(0.6F, 3F, -3.4F, 1, 1, 2);
      left_front_toe_2.setTextureSize(64, 32);
      left_front_toe_2.mirror = true;
      setRotation(left_front_toe_2, 0F, 0F, 0F);
      PixelmonModelRenderer   left_front_toe_1 = new PixelmonModelRenderer(this, 17, 29);
      left_front_toe_1.addBox(1.7F, 3F, -3.4F, 1, 1, 2);
      left_front_toe_1.setTextureSize(64, 32);
      left_front_toe_1.mirror = true;
      setRotation(left_front_toe_1, 0F, 0F, 0F);
      FLLeg.addChild(Left_foreleg);
      FLLeg.addChild(left_forewrist);
      FLLeg.addChild(Left_foreleg_2);
      FLLeg.addChild(left_front_toe_2);
      FLLeg.addChild(left_front_toe_1);
      Body.addChild(FLLeg);
      
      
      
      PixelmonModelRenderer BLLeg = new PixelmonModelRenderer(this, "Back Left Leg");
      BLLeg.setRotationPoint(2.6F, 3, 0);
      PixelmonModelRenderer   left_hind_leg = new PixelmonModelRenderer(this, 18, 22);
      left_hind_leg.addBox(0F, -0.8F, 0.7F, 2, 4, 2);
      left_hind_leg.setTextureSize(64, 32);
      left_hind_leg.mirror = true;
      setRotation(left_hind_leg, -0.6414922F, 0F, 0F);
      PixelmonModelRenderer   left_hind_toe_1 = new PixelmonModelRenderer(this, 17, 29);
      left_hind_toe_1.addBox(1F, 3F, -2F, 1, 1, 2);
      left_hind_toe_1.setTextureSize(64, 32);
      left_hind_toe_1.mirror = true;
      setRotation(left_hind_toe_1, 0F, 0F, 0F);
      PixelmonModelRenderer   Left_thigh_1 = new PixelmonModelRenderer(this, 15, 16);
      Left_thigh_1.addBox(-1F, -1.466667F, -1F, 3, 4, 4);
      Left_thigh_1.setTextureSize(64, 32);
      Left_thigh_1.mirror = true;
      setRotation(Left_thigh_1, -0.5995031F, 0F, -0.296706F);
      PixelmonModelRenderer   Left_thigh_2 = new PixelmonModelRenderer(this, 16, 18);
      Left_thigh_2.addBox(-0.8F, -1F, -0.5F, 3, 3, 3);
      Left_thigh_2.setTextureSize(64, 32);
      Left_thigh_2.mirror = true;
      setRotation(Left_thigh_2, -0.5995031F, 0F, -0.296706F);
      PixelmonModelRenderer   left_hind_toe_2 = new PixelmonModelRenderer(this, 17, 29);
      left_hind_toe_2.addBox(-0.1F, 3F, -2F, 1, 1, 2);
      left_hind_toe_2.setTextureSize(64, 32);
      left_hind_toe_2.mirror = true;
      setRotation(left_hind_toe_2, 0F, 0F, 0F);
      BLLeg.addChild(left_hind_leg);
      BLLeg.addChild(left_hind_toe_1);
      BLLeg.addChild(Left_thigh_1);
      BLLeg.addChild(Left_thigh_2);
      BLLeg.addChild(left_hind_toe_2);
      Body.addChild(BLLeg);
      
      
      PixelmonModelRenderer BRLeg = new PixelmonModelRenderer(this, "Back Right leg");
      BRLeg.setRotationPoint(-2.4F, 3, 0);
      PixelmonModelRenderer   right_thigh_1 = new PixelmonModelRenderer(this, 15, 16);
      right_thigh_1.addBox(-2F, -1.466667F, -1F, 3, 4, 4);
      right_thigh_1.setTextureSize(64, 32);
      right_thigh_1.mirror = true;
      setRotation(right_thigh_1, -0.5995051F, 0F, 0.296706F);
      PixelmonModelRenderer   right_thigh_2 = new PixelmonModelRenderer(this, 16, 18);
      right_thigh_2.addBox(-2.2F, -1F, -0.5F, 3, 3, 3);
      right_thigh_2.setTextureSize(64, 32);
      right_thigh_2.mirror = true;
      setRotation(right_thigh_2, -0.5995051F, 0F, 0.296706F);
      PixelmonModelRenderer   right_hind_leg = new PixelmonModelRenderer(this, 18, 22);
      right_hind_leg.addBox(-2F, -0.8F, 0.7F, 2, 4, 2);
      right_hind_leg.setTextureSize(64, 32);
      right_hind_leg.mirror = true;
      setRotation(right_hind_leg, -0.6414922F, 0F, 0F);
      PixelmonModelRenderer   right_hind_toe_2 = new PixelmonModelRenderer(this, 17, 29);
      right_hind_toe_2.addBox(-2F, 3F, -2F, 1, 1, 2);
      right_hind_toe_2.setTextureSize(64, 32);
      right_hind_toe_2.mirror = true;
      setRotation(right_hind_toe_2, 0F, 0F, 0F);
      PixelmonModelRenderer   right_hind_toe_1 = new PixelmonModelRenderer(this, 17, 29);
      right_hind_toe_1.addBox(-0.9F, 3F, -2F, 1, 1, 2);
      right_hind_toe_1.setTextureSize(64, 32);
      right_hind_toe_1.mirror = true;
      setRotation(right_hind_toe_1, 0F, 0F, 0F);
      BRLeg.addChild(right_thigh_1);
      BRLeg.addChild(right_thigh_2);
      BRLeg.addChild(right_hind_leg);
      BRLeg.addChild(right_hind_toe_2);
      BRLeg.addChild(right_hind_toe_1);
      Body.addChild(BRLeg);
      
      
      ModuleHead headModule = new ModuleHead(Head);
		float legspeed = 0.8F;
		float legRotationLimit = 1.1F;

		ModuleLeg frontlegLModule = new ModuleLeg(FLLeg, EnumLeg.FrontLeft,
				EnumPhase.OutPhase, legRotationLimit, legspeed);
		ModuleLeg frontlegRModule = new ModuleLeg(FRLeg, EnumLeg.FrontRight,
				EnumPhase.OutPhase, legRotationLimit, legspeed);
		ModuleLeg backlegLModule = new ModuleLeg(BLLeg, EnumLeg.BackLeft,
				EnumPhase.OutPhase, legRotationLimit, legspeed);
		ModuleLeg backlegRModule = new ModuleLeg(BRLeg, EnumLeg.BackRight,
				EnumPhase.OutPhase, legRotationLimit, legspeed);

		skeleton = new SkeletonQuadruped(Body, headModule, frontlegLModule,
				frontlegRModule, backlegLModule, backlegRModule, null);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Body.render(f5);
  }
  
  private void setRotation(PixelmonModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
  }

}
