// Date: 2/11/2013 1:00:29 AM
// Template version 11
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package pixelmon.client.models.pokemon;

import net.minecraft.entity.Entity;
import pixelmon.client.models.PixelmonModelBase;
import pixelmon.client.models.PixelmonModelRenderer;
import pixelmon.client.models.animations.EnumLeg;
import pixelmon.client.models.animations.EnumPhase;
import pixelmon.client.models.animations.EnumRotation;
import pixelmon.client.models.animations.ModuleHead;
import pixelmon.client.models.animations.ModuleLeg;
import pixelmon.client.models.animations.quadruped.SkeletonQuadruped;

public class ModelNidoranfemale extends PixelmonModelBase {
	// fields
	PixelmonModelRenderer Body;

	public ModelNidoranfemale() {
		textureWidth = 128;
		textureHeight = 64;

		Body = new PixelmonModelRenderer(this, "Body");
		Body.setRotationPoint(2.5F, 14, -1);
		PixelmonModelRenderer Body_1 = new PixelmonModelRenderer(this, 36, 44);
		Body_1.addBox(-5.5F, -4F, -6F, 11, 8, 12);
		Body_1.setTextureSize(128, 64);
		Body_1.mirror = true;
		setRotation(Body_1, -0.1047198F, 0F, 0F);
		Body.addChild(Body_1);
		PixelmonModelRenderer Body_2 = new PixelmonModelRenderer(this, 0, 0);
		Body_2.addBox(-5F, -5F, -5.5F, 10, 10, 11);
		Body_2.setTextureSize(128, 64);
		Body_2.mirror = true;
		setRotation(Body_2, -0.122173F, 0F, 0F);
		Body.addChild(Body_2);
		PixelmonModelRenderer Spike_2 = new PixelmonModelRenderer(this, 82, 56);
		Spike_2.addBox(-1F, -10F, -3F, 2, 6, 2);
		Spike_2.setTextureSize(128, 64);
		Spike_2.mirror = true;
		setRotation(Spike_2, -0.4014257F, 0F, 0F);
		Body.addChild(Spike_2);
		PixelmonModelRenderer Spike_3 = new PixelmonModelRenderer(this, 82, 56);
		Spike_3.addBox(-1F, -11F, 0F, 2, 6, 2);
		Spike_3.setTextureSize(128, 64);
		Spike_3.mirror = true;
		setRotation(Spike_3, -0.6283185F, 0F, 0F);
		Body.addChild(Spike_3);

		PixelmonModelRenderer FRLeg = new PixelmonModelRenderer(this, "FRLeg");
		FRLeg.setRotationPoint(-4, 4, -3.5F);
		PixelmonModelRenderer Leg_1 = new PixelmonModelRenderer(this, 0, 0);
		Leg_1.addBox(-1.8F, -1F, -2.3F, 4, 6, 4);
		Leg_1.setTextureSize(128, 64);
		Leg_1.mirror = true;
		setRotation(Leg_1, 0F, 0F, 0F);
		FRLeg.addChild(Leg_1);
		PixelmonModelRenderer Toe_Claw_1 = new PixelmonModelRenderer(this, 16,
				43);
		Toe_Claw_1.addBox(0.5F, 4F, -2.5F, 1, 1, 1);
		Toe_Claw_1.setTextureSize(128, 64);
		Toe_Claw_1.mirror = true;
		setRotation(Toe_Claw_1, 0F, 0.7853982F, 0F);
		FRLeg.addChild(Toe_Claw_1);
		PixelmonModelRenderer Toe_Claw_11 = new PixelmonModelRenderer(this, 16,
				43);
		Toe_Claw_11.addBox(2F, 4F, -1F, 1, 1, 1);
		Toe_Claw_11.setTextureSize(128, 64);
		Toe_Claw_11.mirror = true;
		setRotation(Toe_Claw_11, 0F, 0.7853982F, 0F);
		FRLeg.addChild(Toe_Claw_11);
		Body.addChild(FRLeg);

		PixelmonModelRenderer FLLeg = new PixelmonModelRenderer(this, "FLLeg");
		FLLeg.setRotationPoint(4F, 4, -3.5F);
		PixelmonModelRenderer Leg_2 = new PixelmonModelRenderer(this, 0, 0);
		Leg_2.addBox(-2.2F, -1F, -2.3F, 4, 6, 4);
		Leg_2.setTextureSize(128, 64);
		Leg_2.mirror = true;
		setRotation(Leg_2, 0F, 0F, 0F);
		FLLeg.addChild(Leg_2);
		PixelmonModelRenderer Toe_Claw_2 = new PixelmonModelRenderer(this, 16,
				43);
		Toe_Claw_2.addBox(0F, 4F, -3F, 1, 1, 1);
		Toe_Claw_2.setTextureSize(128, 64);
		Toe_Claw_2.mirror = true;
		setRotation(Toe_Claw_2, 0F, 0.7853982F, 0F);
		FLLeg.addChild(Toe_Claw_2);
		PixelmonModelRenderer Toe_Claw_21 = new PixelmonModelRenderer(this, 16,
				43);
		Toe_Claw_21.addBox(1.5F, 4F, -1.5F, 1, 1, 1);
		Toe_Claw_21.setTextureSize(128, 64);
		Toe_Claw_21.mirror = true;
		setRotation(Toe_Claw_21, 0F, 0.7853982F, 0F);
		FLLeg.addChild(Toe_Claw_21);
		Body.addChild(FLLeg);

		PixelmonModelRenderer BLLeg = new PixelmonModelRenderer(this, "BLLeg");
		BLLeg.setRotationPoint(4.5F, 4, 4.5F);
		PixelmonModelRenderer Leg_3 = new PixelmonModelRenderer(this, 0, 0);
		Leg_3.addBox(-2.2F, -1F, -3F, 4, 6, 4);
		Leg_3.setTextureSize(128, 64);
		Leg_3.mirror = true;
		setRotation(Leg_3, 0F, 0F, 0F);
		BLLeg.addChild(Leg_3);
		PixelmonModelRenderer Toe_Claw_3 = new PixelmonModelRenderer(this, 16,
				43);
		Toe_Claw_3.addBox(0F, 4F, -3.7F, 1, 1, 1);
		Toe_Claw_3.setTextureSize(128, 64);
		Toe_Claw_3.mirror = true;
		setRotation(Toe_Claw_3, 0F, 0.7853982F, 0F);
		BLLeg.addChild(Toe_Claw_3);
		PixelmonModelRenderer Toe_Claw_31 = new PixelmonModelRenderer(this, 16,
				43);
		Toe_Claw_31.addBox(1.5F, 4F, -3.3F, 1, 1, 1);
		Toe_Claw_31.setTextureSize(128, 64);
		Toe_Claw_31.mirror = true;
		setRotation(Toe_Claw_31, 0F, 0.7853982F, 0F);
		BLLeg.addChild(Toe_Claw_31);
		Body.addChild(BLLeg);

		PixelmonModelRenderer BRLeg = new PixelmonModelRenderer(this, "BRLeg");
		BRLeg.setRotationPoint(-4, 4, 4.5F);
		PixelmonModelRenderer Leg_4 = new PixelmonModelRenderer(this, 0, 0);
		Leg_4.addBox(-1.8F, -1F, -3F, 4, 6, 4);
		Leg_4.setTextureSize(128, 64);
		Leg_4.mirror = true;
		setRotation(Leg_4, 0F, 0F, 0F);
		BRLeg.addChild(Leg_4);
		PixelmonModelRenderer Toe_Claw_4 = new PixelmonModelRenderer(this, 16,
				43);
		Toe_Claw_4.addBox(0.5F, 4F, -3.2F, 1, 1, 1);
		Toe_Claw_4.setTextureSize(128, 64);
		Toe_Claw_4.mirror = true;
		setRotation(Toe_Claw_4, 0F, 0.7853982F, 0F);
		BRLeg.addChild(Toe_Claw_4);
		PixelmonModelRenderer Toe_Claw_41 = new PixelmonModelRenderer(this, 16,
				43);
		Toe_Claw_41.addBox(1.8F, 4F, -1.8F, 1, 1, 1);
		Toe_Claw_41.setTextureSize(128, 64);
		Toe_Claw_41.mirror = true;
		setRotation(Toe_Claw_41, 0F, 0.7853982F, 0F);
		BRLeg.addChild(Toe_Claw_41);
		Body.addChild(BRLeg);

		PixelmonModelRenderer Head = new PixelmonModelRenderer(this, "Head");
		Head.setRotationPoint(0, -2, -3);
		PixelmonModelRenderer Head_1 = new PixelmonModelRenderer(this, 0, 46);
		Head_1.addBox(-4.5F, -3F, -9F, 9, 6, 9);
		Head_1.setTextureSize(128, 64);
		Head_1.mirror = true;
		setRotation(Head_1, -0.2094395F, 0F, 0F);
		Head.addChild(Head_1);
		PixelmonModelRenderer Top_head_1 = new PixelmonModelRenderer(this, 0, 0);
		Top_head_1.addBox(-4.5F, -8.1F, -4.8F, 9, 2, 2);
		Top_head_1.setTextureSize(128, 64);
		Top_head_1.mirror = true;
		setRotation(Top_head_1, 0.5061455F, 0F, 0F);
		Head.addChild(Top_head_1);
		PixelmonModelRenderer Top_Head_2 = new PixelmonModelRenderer(this, 0, 0);
		Top_Head_2.addBox(-4.5F, -4.9F, -0.9F, 9, 2, 2);
		Top_Head_2.setTextureSize(128, 64);
		Top_Head_2.mirror = true;
		setRotation(Top_Head_2, 0.5061455F, 0F, 0F);
		Head.addChild(Top_Head_2);
		PixelmonModelRenderer Top_Head_3 = new PixelmonModelRenderer(this, 0, 0);
		Top_Head_3.addBox(-4.5F, -4.5F, -7.2F, 9, 2, 5);
		Top_Head_3.setTextureSize(128, 64);
		Top_Head_3.mirror = true;
		setRotation(Top_Head_3, -0.1745329F, 0F, 0F);
		Head.addChild(Top_Head_3);
		PixelmonModelRenderer Bot_Head_1 = new PixelmonModelRenderer(this, 0, 0);
		Bot_Head_1.addBox(-4.5F, -4F, -8.6F, 9, 2, 2);
		Bot_Head_1.setTextureSize(128, 64);
		Bot_Head_1.mirror = true;
		setRotation(Bot_Head_1, 0.5410521F, 0F, 0F);
		Head.addChild(Bot_Head_1);
		PixelmonModelRenderer Bot_Head_2 = new PixelmonModelRenderer(this, 0, 0);
		Bot_Head_2.addBox(-4.5F, -0.7F, -4.3F, 9, 2, 2);
		Bot_Head_2.setTextureSize(128, 64);
		Bot_Head_2.mirror = true;
		setRotation(Bot_Head_2, 0.4537856F, 0F, 0F);
		Head.addChild(Bot_Head_2);
		PixelmonModelRenderer Bot_Head_3 = new PixelmonModelRenderer(this, 0, 0);
		Bot_Head_3.addBox(-4.5F, 1.2F, -8.2F, 9, 2, 5);
		Bot_Head_3.setTextureSize(128, 64);
		Bot_Head_3.mirror = true;
		setRotation(Bot_Head_3, -0.0523599F, 0F, 0F);
		Head.addChild(Bot_Head_3);
		PixelmonModelRenderer Whisker_1 = new PixelmonModelRenderer(this, 0, 45);
		Whisker_1.addBox(-7F, -3F, -10F, 5, 1, 0);
		Whisker_1.setTextureSize(128, 64);
		Whisker_1.mirror = true;
		setRotation(Whisker_1, 0.1047198F, 0.0349066F, 0.1919862F);
		Head.addChild(Whisker_1);
		PixelmonModelRenderer Whisker_2 = new PixelmonModelRenderer(this, 0, 45);
		Whisker_2.addBox(-7F, -2F, -10F, 5, 1, 0);
		Whisker_2.setTextureSize(128, 64);
		Whisker_2.mirror = true;
		setRotation(Whisker_2, 0.1047198F, 0.0349066F, -0.2443461F);
		Head.addChild(Whisker_2);
		PixelmonModelRenderer Whisker_3 = new PixelmonModelRenderer(this, 0, 45);
		Whisker_3.addBox(2.5F, -3F, -10F, 5, 1, 0);
		Whisker_3.setTextureSize(128, 64);
		Whisker_3.mirror = true;
		setRotation(Whisker_3, 0.1047198F, 0F, -0.1919862F);
		Head.addChild(Whisker_3);
		PixelmonModelRenderer Whisker_4 = new PixelmonModelRenderer(this, 0, 45);
		Whisker_4.addBox(2.5F, -1.5F, -10F, 5, 1, 0);
		Whisker_4.setTextureSize(128, 64);
		Whisker_4.mirror = true;
		setRotation(Whisker_4, 0.1047198F, 0.0349066F, 0.1396263F);
		Head.addChild(Whisker_4);
		PixelmonModelRenderer Nose_1 = new PixelmonModelRenderer(this, 0, 0);
		Nose_1.addBox(-1.5F, -9.3F, -6F, 3, 3, 3);
		Nose_1.setTextureSize(128, 64);
		Nose_1.mirror = true;
		setRotation(Nose_1, 1.047198F, 0F, 0F);
		Head.addChild(Nose_1);
		PixelmonModelRenderer Nose_2 = new PixelmonModelRenderer(this, 0, 0);
		Nose_2.addBox(-1.5F, 7F, -5F, 3, 3, 2);
		Nose_2.setTextureSize(128, 64);
		Nose_2.mirror = true;
		setRotation(Nose_2, -1.27409F, 0F, 0F);
		Head.addChild(Nose_2);
		PixelmonModelRenderer Nose_3 = new PixelmonModelRenderer(this, 0, 0);
		Nose_3.addBox(-1.5F, -1.5F, -11.1F, 3, 2, 1);
		Nose_3.setTextureSize(128, 64);
		Nose_3.mirror = true;
		setRotation(Nose_3, 0F, 0F, 0F);
		Head.addChild(Nose_3);
		PixelmonModelRenderer Nose_4 = new PixelmonModelRenderer(this, 0, 0);
		Nose_4.addBox(-1.5F, -1.8F, -11.1F, 3, 2, 1);
		Nose_4.setTextureSize(128, 64);
		Nose_4.mirror = true;
		setRotation(Nose_4, 0F, 0F, 0F);
		Head.addChild(Nose_4);
		PixelmonModelRenderer L_Ear_1 = new PixelmonModelRenderer(this, 1, 37);
		L_Ear_1.addBox(-1F, -9F, -5F, 6, 7, 1);
		L_Ear_1.setTextureSize(128, 64);
		L_Ear_1.mirror = true;
		setRotation(L_Ear_1, 0F, -0.8726646F, 0.2443461F);
		Head.addChild(L_Ear_1);
		PixelmonModelRenderer R_Ear_1 = new PixelmonModelRenderer(this, 1, 29);
		R_Ear_1.addBox(-2F, -8.8F, 4F, 6, 7, 1);
		R_Ear_1.setTextureSize(128, 64);
		R_Ear_1.mirror = true;
		setRotation(R_Ear_1, 0F, -2.076942F, 0.122173F);
		Head.addChild(R_Ear_1);
		PixelmonModelRenderer Tooth_1 = new PixelmonModelRenderer(this, 0, 26);
		Tooth_1.addBox(-1.1F, -0.5F, -10.5F, 1, 2, 0);
		Tooth_1.setTextureSize(128, 64);
		Tooth_1.mirror = true;
		setRotation(Tooth_1, 0F, 0F, 0F);
		Head.addChild(Tooth_1);
		PixelmonModelRenderer Tooth_2 = new PixelmonModelRenderer(this, 0, 26);
		Tooth_2.addBox(0.1F, -0.5F, -10.5F, 1, 2, 0);
		Tooth_2.setTextureSize(128, 64);
		Tooth_2.mirror = true;
		setRotation(Tooth_2, 0F, 0F, 0F);
		Head.addChild(Tooth_2);
		Body.addChild(Head);

		ModuleHead headModule = new ModuleHead(Head);
		float legspeed = 0.8F;
		float legRotationLimit = 1.1F;

		ModuleLeg frontlegLModule = new ModuleLeg(FLLeg, EnumLeg.FrontLeft,
				EnumPhase.OutPhase, EnumRotation.x, legRotationLimit, legspeed);
		ModuleLeg frontlegRModule = new ModuleLeg(FRLeg, EnumLeg.FrontRight,
				EnumPhase.OutPhase, EnumRotation.x, legRotationLimit, legspeed);
		ModuleLeg backlegLModule = new ModuleLeg(BLLeg, EnumLeg.BackLeft,
				EnumPhase.OutPhase, EnumRotation.x, legRotationLimit, legspeed);
		ModuleLeg backlegRModule = new ModuleLeg(BRLeg, EnumLeg.BackRight,
				EnumPhase.OutPhase, EnumRotation.x, legRotationLimit, legspeed);

		skeleton = new SkeletonQuadruped(Body, headModule, frontlegLModule,
				frontlegRModule, backlegLModule, backlegRModule, null);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3,
			float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		Body.render(f5);
	}

	private void setRotation(PixelmonModelRenderer model, float x, float y,
			float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

}
