// Date: 2/5/2013 11:45:26 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package pixelmon.client.models.pokemon;

import net.minecraft.entity.Entity;
import pixelmon.client.models.PixelmonModelBase;
import pixelmon.client.models.PixelmonModelRenderer;
import pixelmon.client.models.animations.EnumArm;
import pixelmon.client.models.animations.EnumLeg;
import pixelmon.client.models.animations.EnumPhase;
import pixelmon.client.models.animations.ModuleArm;
import pixelmon.client.models.animations.ModuleHead;
import pixelmon.client.models.animations.ModuleLeg;
import pixelmon.client.models.animations.biped.SkeletonBiped;

public class ModelRaticate extends PixelmonModelBase {
	// fields

	PixelmonModelRenderer Body;

	public ModelRaticate() {
		textureWidth = 128;
		textureHeight = 64;

		Body = new PixelmonModelRenderer(this, "Body");
		Body.setRotationPoint(0, 17, -1);
		PixelmonModelRenderer body_1 = new PixelmonModelRenderer(this, 0, 51);
		body_1.addBox(-3.5F, 0F, -2F, 7, 6, 7);
		body_1.setTextureSize(128, 64);
		body_1.mirror = true;
		setRotation(body_1, 0.418879F, 0F, 0F);
		Body.addChild(body_1);
		PixelmonModelRenderer body_2 = new PixelmonModelRenderer(this, 0, 42);
		body_2.addBox(-2.5F, 4.733333F, -0.8666667F, 5, 2, 6);
		body_2.setTextureSize(128, 64);
		body_2.mirror = true;
		setRotation(body_2, 0.296706F, 0F, 0F);
		Body.addChild(body_2);
		PixelmonModelRenderer body_3 = new PixelmonModelRenderer(this, 0, 31);
		body_3.addBox(-3F, -0.9333333F, -2.066667F, 6, 3, 7);
		body_3.setTextureSize(128, 64);
		body_3.mirror = true;
		setRotation(body_3, 0.6806784F, 0F, 0F);
		Body.addChild(body_3);
		PixelmonModelRenderer body_4 = new PixelmonModelRenderer(this, 0, 22);
		body_4.addBox(-3F, 0.06666667F, -2.533333F, 6, 6, 2);
		body_4.setTextureSize(128, 64);
		body_4.mirror = true;
		setRotation(body_4, 0.2617994F, 0F, 0F);
		Body.addChild(body_4);
		PixelmonModelRenderer neck = new PixelmonModelRenderer(this, 29, 55);
		neck.addBox(-2.5F, -1.533333F, -0.4F, 5, 4, 5);
		neck.setTextureSize(128, 64);
		neck.mirror = true;
		setRotation(neck, 1.37881F, 0F, 0F);
		Body.addChild(neck);

		PixelmonModelRenderer Head = new PixelmonModelRenderer(this, "Head");
		Head.setRotationPoint(0, -2, -1);
		PixelmonModelRenderer head = new PixelmonModelRenderer(this, 50, 56);
		head.addBox(-2F, -2.8F, -3.133333F, 4, 4, 4);
		head.setTextureSize(128, 64);
		head.mirror = true;
		setRotation(head, 0.6806784F, 0F, 0F);
		Head.addChild(head);
		PixelmonModelRenderer head_2 = new PixelmonModelRenderer(this, 112, 0);
		head_2.addBox(-2F, -3.6F, -3.666667F, 4, 1, 4);
		head_2.setTextureSize(128, 64);
		head_2.mirror = true;
		setRotation(head_2, 0.6457718F, 0F, 0F);
		Head.addChild(head_2);
		PixelmonModelRenderer head_3 = new PixelmonModelRenderer(this, 103, 56);
		head_3.addBox(1.8F, -2.8F, -3.133333F, 2, 4, 4);
		head_3.setTextureSize(128, 64);
		head_3.mirror = true;
		setRotation(head_3, 0.715585F, 0.418879F, 0F);
		head_3.mirror = false;
		Head.addChild(head_3);
		PixelmonModelRenderer head_4 = new PixelmonModelRenderer(this, 116, 56);
		head_4.addBox(-3.8F, -2.8F, -3.133333F, 2, 4, 4);
		head_4.setTextureSize(128, 64);
		head_4.mirror = true;
		setRotation(head_4, 0.715585F, -0.418879F, 0F);
		Head.addChild(head_4);
		PixelmonModelRenderer nose = new PixelmonModelRenderer(this, 103, 0);
		nose.addBox(-1F, -3.9F, -4F, 2, 1, 2);
		nose.setTextureSize(128, 64);
		nose.mirror = true;
		setRotation(nose, 0.8028515F, 0F, 0F);
		Head.addChild(nose);
		PixelmonModelRenderer mouth = new PixelmonModelRenderer(this, 49, 0);
		mouth.addBox(-2F, -1.466667F, -4.933333F, 4, 4, 4);
		mouth.setTextureSize(128, 64);
		mouth.mirror = true;
		setRotation(mouth, 0.3490659F, 0F, 0F);
		Head.addChild(mouth);
		PixelmonModelRenderer teeth_ = new PixelmonModelRenderer(this, 42, 0);
		teeth_.addBox(-1.5F, -2.6F, -4.533333F, 3, 4, 0);
		teeth_.setTextureSize(128, 64);
		teeth_.mirror = true;
		setRotation(teeth_, 0.5061455F, 0F, 0F);
		Head.addChild(teeth_);
		PixelmonModelRenderer mouth_inside = new PixelmonModelRenderer(this,
				54, 9);
		mouth_inside.addBox(-1.533333F, -1.066667F, -4.266667F, 3, 3, 1);
		mouth_inside.setTextureSize(128, 64);
		mouth_inside.mirror = true;
		setRotation(mouth_inside, 0.3490659F, 0F, 0F);
		Head.addChild(mouth_inside);
		PixelmonModelRenderer fur_tufts_1 = new PixelmonModelRenderer(this, 23,
				0);
		fur_tufts_1.addBox(-2F, -3.6F, -0.4666667F, 4, 0, 3);
		fur_tufts_1.setTextureSize(128, 64);
		fur_tufts_1.mirror = true;
		setRotation(fur_tufts_1, 0.8203047F, 0F, 0F);
		Head.addChild(fur_tufts_1);
		PixelmonModelRenderer L_ear = new PixelmonModelRenderer(this, 28, 18);
		L_ear.addBox(2.966667F, -2.8F, 0.7333333F, 0, 6, 6);
		L_ear.setTextureSize(128, 64);
		L_ear.mirror = true;
		setRotation(L_ear, 0.7330383F, 0.7853982F, 0F);
		Head.addChild(L_ear);
		PixelmonModelRenderer R_ear = new PixelmonModelRenderer(this, 28, 18);
		R_ear.addBox(-3.033333F, -2.8F, 0.7333333F, 0, 6, 6);
		R_ear.setTextureSize(128, 64);
		R_ear.mirror = true;
		setRotation(R_ear, 0.7330383F, -0.7853982F, 0F);
		Head.addChild(R_ear);
		PixelmonModelRenderer whisker_L = new PixelmonModelRenderer(this, -5,
				15);
		whisker_L.addBox(1F, -2.666667F, -4.733333F, 5, 5, 0);
		whisker_L.setTextureSize(128, 64);
		whisker_L.mirror = true;
		setRotation(whisker_L, 0.3490659F, -0.2268928F, 0.0349066F);
		Head.addChild(whisker_L);
		PixelmonModelRenderer whisker_R = new PixelmonModelRenderer(this, 0, 15);
		whisker_R.addBox(-6F, -2.666667F, -4.733333F, 5, 5, 0);
		whisker_R.setTextureSize(128, 64);
		whisker_R.mirror = true;
		setRotation(whisker_R, 0.3490659F, 0.2268928F, -0.0349066F);
		Head.addChild(whisker_R);
		Body.addChild(Head);

		PixelmonModelRenderer Tail = new PixelmonModelRenderer(this, "Tail");
		Tail.setRotationPoint(0, 4, 6);
		PixelmonModelRenderer tail_1 = new PixelmonModelRenderer(this, 0, 6);
		tail_1.addBox(-1.5F, -1.466667F, -1.933333F, 3, 3, 3);
		tail_1.setTextureSize(128, 64);
		tail_1.mirror = true;
		setRotation(tail_1, -0.2617994F, 0F, 0F);
		Tail.addChild(tail_1);
		PixelmonModelRenderer tail_2 = new PixelmonModelRenderer(this, 13, 7);
		tail_2.addBox(-1F, -1F, 0.06666667F, 2, 2, 3);
		tail_2.setTextureSize(128, 64);
		tail_2.mirror = true;
		setRotation(tail_2, -0.1047198F, 0F, 0F);
		Tail.addChild(tail_2);
		PixelmonModelRenderer tail_3 = new PixelmonModelRenderer(this, 0, 0);
		tail_3.addBox(-0.5F, -0.5333334F, 2.6F, 1, 1, 2);
		tail_3.setTextureSize(128, 64);
		tail_3.mirror = true;
		setRotation(tail_3, -0.0523599F, 0F, 0F);
		Tail.addChild(tail_3);
		PixelmonModelRenderer tail_4 = new PixelmonModelRenderer(this, 0, 0);
		tail_4.addBox(-0.5F, 0.1F, 4.4F, 1, 1, 2);
		tail_4.setTextureSize(128, 64);
		tail_4.mirror = true;
		setRotation(tail_4, 0.0872665F, 0F, 0F);
		Tail.addChild(tail_4);
		PixelmonModelRenderer tail_5 = new PixelmonModelRenderer(this, 0, 0);
		tail_5.addBox(-0.5F, 0.9F, 5.866667F, 1, 1, 2);
		tail_5.setTextureSize(128, 64);
		tail_5.mirror = true;
		setRotation(tail_5, 0.2268928F, 0F, 0F);
		Tail.addChild(tail_5);
		PixelmonModelRenderer tail_6 = new PixelmonModelRenderer(this, 0, 0);
		tail_6.addBox(-0.5F, 2.066667F, 7.4F, 1, 1, 2);
		tail_6.setTextureSize(128, 64);
		tail_6.mirror = true;
		setRotation(tail_6, 0.3839724F, 0F, 0F);
		Tail.addChild(tail_6);
		PixelmonModelRenderer tail_7 = new PixelmonModelRenderer(this, 0, 0);
		tail_7.addBox(-0.5F, 3.266667F, 8.4F, 1, 1, 2);
		tail_7.setTextureSize(128, 64);
		tail_7.mirror = true;
		setRotation(tail_7, 0.5235988F, 0F, 0F);
		Tail.addChild(tail_7);
		PixelmonModelRenderer tail_8 = new PixelmonModelRenderer(this, 0, 0);
		tail_8.addBox(-0.5F, 4.7F, 9.4F, 1, 1, 2);
		tail_8.setTextureSize(128, 64);
		tail_8.mirror = true;
		setRotation(tail_8, 0.6632251F, 0F, 0F);
		Tail.addChild(tail_8);
		Body.addChild(Tail);

		PixelmonModelRenderer LeftArm = new PixelmonModelRenderer(this,
				"Left Arm");
		LeftArm.setRotationPoint(3, 2, -2);
		PixelmonModelRenderer L_hand = new PixelmonModelRenderer(this, 28, 35);
		L_hand.addBox(0.3333333F, 0F, -1F, 1, 2, 2);
		L_hand.setTextureSize(128, 64);
		L_hand.mirror = true;
		setRotation(L_hand, 0F, 0.5759587F, 0.7330383F);
		LeftArm.addChild(L_hand);
		PixelmonModelRenderer L_finger_1 = new PixelmonModelRenderer(this, 33,
				33);
		L_finger_1.addBox(0.3333333F, -1.333333F, -1F, 1, 2, 1);
		L_finger_1.setTextureSize(128, 64);
		L_finger_1.mirror = true;
		setRotation(L_finger_1, 0.4014257F, 0.4886922F, 0.9773844F);
		LeftArm.addChild(L_finger_1);
		PixelmonModelRenderer L_finger_2 = new PixelmonModelRenderer(this, 33,
				33);
		L_finger_2.addBox(0.3333333F, -1.333333F, -0.2666667F, 1, 2, 1);
		L_finger_2.setTextureSize(128, 64);
		L_finger_2.mirror = true;
		setRotation(L_finger_2, 0.0523599F, 0.4014257F, 0.9075712F);
		LeftArm.addChild(L_finger_2);
		PixelmonModelRenderer L_finger_3 = new PixelmonModelRenderer(this, 33,
				33);
		L_finger_3.addBox(0.4F, -2.066667F, 0.4666667F, 1, 2, 1);
		L_finger_3.setTextureSize(128, 64);
		L_finger_3.mirror = true;
		setRotation(L_finger_3, -1.22173F, 1.047198F, 1.204277F);
		LeftArm.addChild(L_finger_3);
		Body.addChild(LeftArm);

		PixelmonModelRenderer RightArm = new PixelmonModelRenderer(this,
				"Right Arm");
		RightArm.setRotationPoint(-3, 2, -2);
		PixelmonModelRenderer R_hand = new PixelmonModelRenderer(this, 28, 35);
		R_hand.addBox(-1.333333F, 0F, -1F, 1, 2, 2);
		R_hand.setTextureSize(128, 64);
		R_hand.mirror = true;
		setRotation(R_hand, 0F, -0.5759587F, -0.7330383F);
		RightArm.addChild(R_hand);
		PixelmonModelRenderer R_finger_1 = new PixelmonModelRenderer(this, 33,
				33);
		R_finger_1.addBox(-1.3F, -1.333333F, -1F, 1, 2, 1);
		R_finger_1.setTextureSize(128, 64);
		R_finger_1.mirror = true;
		setRotation(R_finger_1, 0.4014257F, -0.4886922F, -0.9773844F);
		RightArm.addChild(R_finger_1);
		PixelmonModelRenderer R_finger_2 = new PixelmonModelRenderer(this, 33,
				33);
		R_finger_2.addBox(-1.3F, -1.333333F, -0.2666667F, 1, 2, 1);
		R_finger_2.setTextureSize(128, 64);
		R_finger_2.mirror = true;
		setRotation(R_finger_2, 0.0523599F, -0.4014257F, -0.9075712F);
		RightArm.addChild(R_finger_2);
		PixelmonModelRenderer R_finger_3 = new PixelmonModelRenderer(this, 33,
				33);
		R_finger_3.addBox(-1.4F, -2.066667F, 0.4666667F, 1, 2, 1);
		R_finger_3.setTextureSize(128, 64);
		R_finger_3.mirror = true;
		setRotation(R_finger_3, -1.22173F, -1.047198F, -1.204277F);
		RightArm.addChild(R_finger_3);
		Body.addChild(RightArm);

		PixelmonModelRenderer LeftLeg = new PixelmonModelRenderer(this,
				"Left Leg");
		LeftLeg.setRotationPoint(3, 6, 0);
		PixelmonModelRenderer L_foot = new PixelmonModelRenderer(this, 33, 44);
		L_foot.addBox(-2F, 0F, -2F, 3, 1, 4);
		L_foot.setTextureSize(128, 64);
		L_foot.mirror = true;
		setRotation(L_foot, 0F, -0.3839724F, 0F);
		LeftLeg.addChild(L_foot);
		PixelmonModelRenderer L_toe_1 = new PixelmonModelRenderer(this, 26, 43);
		L_toe_1.addBox(-0.6F, 0F, -3F, 1, 1, 2);
		L_toe_1.setTextureSize(128, 64);
		L_toe_1.mirror = true;
		setRotation(L_toe_1, 0F, -0.7330383F, 0F);
		LeftLeg.addChild(L_toe_1);
		PixelmonModelRenderer L_toe_2 = new PixelmonModelRenderer(this, 26, 43);
		L_toe_2.addBox(-1.133333F, 0F, -3.466667F, 1, 1, 2);
		L_toe_2.setTextureSize(128, 64);
		L_toe_2.mirror = true;
		setRotation(L_toe_2, 0F, -0.418879F, 0F);
		LeftLeg.addChild(L_toe_2);
		PixelmonModelRenderer L_toe_3 = new PixelmonModelRenderer(this, 26, 43);
		L_toe_3.addBox(-1.666667F, 0F, -3.466667F, 1, 1, 2);
		L_toe_3.setTextureSize(128, 64);
		L_toe_3.mirror = true;
		setRotation(L_toe_3, 0F, -0.0872665F, 0F);
		LeftLeg.addChild(L_toe_3);
		Body.addChild(LeftLeg);

		PixelmonModelRenderer RightLeg = new PixelmonModelRenderer(this,
				"Right Leg");
		RightLeg.setRotationPoint(-3, 6, 0);
		PixelmonModelRenderer R_foot = new PixelmonModelRenderer(this, 33, 44);
		R_foot.addBox(-1F, 0F, -2F, 3, 1, 4);
		R_foot.setTextureSize(128, 64);
		R_foot.mirror = true;
		setRotation(R_foot, 0F, 0.3839724F, 0F);
		RightLeg.addChild(R_foot);
		PixelmonModelRenderer R_toe_1 = new PixelmonModelRenderer(this, 26, 43);
		R_toe_1.addBox(-0.6F, 0F, -3F, 1, 1, 2);
		R_toe_1.setTextureSize(128, 64);
		R_toe_1.mirror = true;
		setRotation(R_toe_1, 0F, 0.7330383F, 0F);
		RightLeg.addChild(R_toe_1);
		PixelmonModelRenderer R_toe_2 = new PixelmonModelRenderer(this, 26, 43);
		R_toe_2.addBox(-0.1333333F, 0F, -3.466667F, 1, 1, 2);
		R_toe_2.setTextureSize(128, 64);
		R_toe_2.mirror = true;
		setRotation(R_toe_2, 0F, 0.418879F, 0F);
		RightLeg.addChild(R_toe_2);
		PixelmonModelRenderer R_toe_3 = new PixelmonModelRenderer(this, 26, 43);
		R_toe_3.addBox(0.3333333F, 0F, -3.466667F, 1, 1, 2);
		R_toe_3.setTextureSize(128, 64);
		R_toe_3.mirror = true;
		setRotation(R_toe_3, 0F, 0.0872665F, 0F);
		RightLeg.addChild(R_toe_3);
		Body.addChild(RightLeg);

		ModuleHead headModule = new ModuleHead(Head);

		ModuleArm leftArmModule = new ModuleArm(LeftArm, EnumArm.Left);
		ModuleArm rightArmModule = new ModuleArm(RightArm, EnumArm.Right);

		float legspeed = 0.65F;
		float legRotationLimit = 1.4F;

		ModuleLeg leftLegModule = new ModuleLeg(LeftLeg, EnumLeg.FrontLeft,
				EnumPhase.InPhase, legRotationLimit, legspeed);
		ModuleLeg rightLegModule = new ModuleLeg(RightLeg, EnumLeg.FrontRight,
				EnumPhase.InPhase, legRotationLimit, legspeed);

		skeleton = new SkeletonBiped(Body, headModule, leftArmModule,
				rightArmModule, leftLegModule, rightLegModule, null);

	}

	public void render(Entity entity, float f, float f1, float f2, float f3,
			float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		Body.render(f5);

	}

	private void setRotation(PixelmonModelRenderer model, float x, float y,
			float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

}
