// Date: 5/20/2013 10:46:14 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package pixelmon.client.models.pokemon;

import net.minecraft.entity.Entity;
import pixelmon.client.models.PixelmonModelBase;
import pixelmon.client.models.PixelmonModelRenderer;
import pixelmon.client.models.animations.EnumLeg;
import pixelmon.client.models.animations.EnumPhase;
import pixelmon.client.models.animations.EnumRotation;
import pixelmon.client.models.animations.ModuleHead;
import pixelmon.client.models.animations.ModuleLeg;
import pixelmon.client.models.animations.ModuleTailBasic;
import pixelmon.client.models.animations.quadruped.SkeletonQuadruped;

public class ModelPonyta extends PixelmonModelBase
{
  //fields
    
    PixelmonModelRenderer Body;
  
  public ModelPonyta()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Body = new PixelmonModelRenderer(this, "Body");
      Body.setRotationPoint(0, 9.9F, -2);
      PixelmonModelRenderer  body_1 = new PixelmonModelRenderer(this, 0, 50);
      body_1.addBox(-4F, -1F, -3.466667F, 8, 7, 7);
      body_1.setTextureSize(128, 64);
      body_1.mirror = true;
      setRotation(body_1, -0.0523599F, 0F, 0F);
      PixelmonModelRenderer  body_2 = new PixelmonModelRenderer(this, 0, 36);
      body_2.addBox(-3.5F, -0.5333334F, 1.733333F, 7, 6, 7);
      body_2.setTextureSize(128, 64);
      body_2.mirror = true;
      setRotation(body_2, 0.0174533F, 0F, 0F);
      PixelmonModelRenderer  neck_flame = new PixelmonModelRenderer(this, 46, 18);
      neck_flame.addBox(-1F, -9.066667F, 2.4F, 1, 10, 5);
      neck_flame.setRotationPoint(0F, 0F, -5F);
      neck_flame.setTextureSize(128, 64);
      neck_flame.mirror = true;
      setRotation(neck_flame, 0.2617994F, 0F, 0F);
      PixelmonModelRenderer  back_flame = new PixelmonModelRenderer(this, 60, 22);
      back_flame.addBox(-1F, -3.533333F, 1.733333F, 1, 6, 7);
      back_flame.setTextureSize(128, 64);
      back_flame.mirror = true;
      setRotation(back_flame, 0.0872665F, 0F, 0F);
      Body.addChild(body_1);
      Body.addChild(body_2);
      Body.addChild(neck_flame);
      Body.addChild(back_flame);
      
      
      PixelmonModelRenderer BLLeg = new PixelmonModelRenderer(this, "Back Left Leg");
      BLLeg.setRotationPoint(3, 5.1F, 7);
      PixelmonModelRenderer  back_leg_L_1 = new PixelmonModelRenderer(this, 114, 0);
      back_leg_L_1.addBox(-1.866667F, -2F, -2F, 3, 6, 4);
      back_leg_L_1.setTextureSize(128, 64);
      back_leg_L_1.mirror = true;
      setRotation(back_leg_L_1, 0.1047198F, 0F, 0F);
      PixelmonModelRenderer  back_leg_L_2 = new PixelmonModelRenderer(this, 105, 0);
      back_leg_L_2.addBox(-1.533333F, 2F, 0.8666667F, 2, 7, 2);
      back_leg_L_2.setTextureSize(128, 64);
      back_leg_L_2.mirror = true;
      setRotation(back_leg_L_2, -0.0523599F, 0F, 0F);
      PixelmonModelRenderer  back_hoof_L_ = new PixelmonModelRenderer(this, 120, 11);
      back_hoof_L_.addBox(-1.4F, 8F, -0.6F, 2, 1, 2);
      back_hoof_L_.setTextureSize(128, 64);
      back_hoof_L_.mirror = true;
      setRotation(back_hoof_L_, 0F, 0F, 0F);
      PixelmonModelRenderer  back_hoof_top_L_ = new PixelmonModelRenderer(this, 113, 11);
      back_hoof_top_L_.addBox(-1.4F, 7.066667F, -3.733333F, 2, 1, 1);
      back_hoof_top_L_.setTextureSize(128, 64);
      back_hoof_top_L_.mirror = true;
      setRotation(back_hoof_top_L_, 0.418879F, 0F, 0F);
      PixelmonModelRenderer  back_leg_L_flame = new PixelmonModelRenderer(this, 0, 0);
      back_leg_L_flame.addBox(-1F, -2F, 1F, 1, 6, 4);
      back_leg_L_flame.setTextureSize(128, 64);
      back_leg_L_flame.mirror = true;
      setRotation(back_leg_L_flame, 0.1047198F, 0.1570796F, 0F);
      BLLeg.addChild(back_leg_L_1);
      BLLeg.addChild(back_leg_L_2);
      BLLeg.addChild(back_hoof_L_);
      BLLeg.addChild(back_hoof_top_L_);
      BLLeg.addChild(back_leg_L_flame);
      Body.addChild(BLLeg);
      
      
      PixelmonModelRenderer BRLeg = new PixelmonModelRenderer(this, "BRLeg");
      BRLeg.setRotationPoint(-3, 5.1F, 7);
      PixelmonModelRenderer  back_leg_R_1 = new PixelmonModelRenderer(this, 114, 0);
      back_leg_R_1.addBox(-1.1F, -2F, -2F, 3, 6, 4);
      back_leg_R_1.setTextureSize(128, 64);
      back_leg_R_1.mirror = true;
      setRotation(back_leg_R_1, 0.1047198F, 0F, 0F);
      PixelmonModelRenderer  back_leg_R_2 = new PixelmonModelRenderer(this, 105, 0);
      back_leg_R_2.addBox(-0.5333334F, 2F, 0.8666667F, 2, 7, 2);
      back_leg_R_2.setTextureSize(128, 64);
      back_leg_R_2.mirror = true;
      setRotation(back_leg_R_2, -0.0523599F, 0F, 0F);
      PixelmonModelRenderer  back_hoof_R = new PixelmonModelRenderer(this, 120, 11);
      back_hoof_R.addBox(-0.6F, 8F, -0.6F, 2, 1, 2);
      back_hoof_R.setTextureSize(128, 64);
      back_hoof_R.mirror = true;
      setRotation(back_hoof_R, 0F, 0F, 0F);
      PixelmonModelRenderer  back_hoof_top_R = new PixelmonModelRenderer(this, 113, 11);
      back_hoof_top_R.addBox(-0.6F, 7.066667F, -3.733333F, 2, 1, 1);
      back_hoof_top_R.setTextureSize(128, 64);
      back_hoof_top_R.mirror = true;
      setRotation(back_hoof_top_R, 0.418879F, 0F, 0F);
      PixelmonModelRenderer  back_leg_R_flame = new PixelmonModelRenderer(this, 0, 0);
      back_leg_R_flame.addBox(-1F, -2F, 1F, 1, 6, 4);
      back_leg_R_flame.setTextureSize(128, 64);
      back_leg_R_flame.mirror = true;
      setRotation(back_leg_R_flame, 0.1047198F, -0.1570796F, 0F);
      BRLeg.addChild(back_leg_R_1);
      BRLeg.addChild(back_leg_R_2);
      BRLeg.addChild(back_hoof_R);
      BRLeg.addChild(back_hoof_top_R);
      BRLeg.addChild(back_leg_R_flame);
      Body.addChild(BRLeg);
      
      PixelmonModelRenderer FLLeg = new PixelmonModelRenderer(this, "FLLeg");
      FLLeg.setRotationPoint(4, 5.1F, -1.87F);
      PixelmonModelRenderer  front_leg_L1 = new PixelmonModelRenderer(this, 116, 15);
      front_leg_L1.addBox(-2F, -3F, -2F, 3, 6, 3);
      front_leg_L1.setTextureSize(128, 64);
      front_leg_L1.mirror = true;
      setRotation(front_leg_L1, 0.0174533F, 0F, 0F);
      PixelmonModelRenderer  front_leg_L2 = new PixelmonModelRenderer(this, 120, 25);
      front_leg_L2.addBox(-1.333333F, 2.533333F, -1.266667F, 2, 6, 2);
      front_leg_L2.setTextureSize(128, 64);
      front_leg_L2.mirror = true;
      setRotation(front_leg_L2, -0.0523599F, 0F, 0F);
      PixelmonModelRenderer  front_hoof_L_ = new PixelmonModelRenderer(this, 120, 11);
      front_hoof_L_.addBox(-1.2F, 8F, -2.2F, 2, 1, 2);
      front_hoof_L_.setTextureSize(128, 64);
      front_hoof_L_.mirror = true;
      setRotation(front_hoof_L_, 0F, 0F, 0F);
      PixelmonModelRenderer  front_hoof_top_L_ = new PixelmonModelRenderer(this, 113, 11);
      front_hoof_top_L_.addBox(-1.2F, 6.466667F, -5.066667F, 2, 1, 1);
      front_hoof_top_L_.setTextureSize(128, 64);
      front_hoof_top_L_.mirror = true;
      setRotation(front_hoof_top_L_, 0.4014257F, 0F, 0F);
      PixelmonModelRenderer  front_leg_L_flame = new PixelmonModelRenderer(this, 0, 11);
      front_leg_L_flame.addBox(-0.5F, -3F, -0.6666667F, 1, 6, 4);
      front_leg_L_flame.setTextureSize(128, 64);
      front_leg_L_flame.mirror = true;
      setRotation(front_leg_L_flame, 0.0174533F, 0.1919862F, 0F);
      FLLeg.addChild(front_leg_L1);
      FLLeg.addChild(front_leg_L2);
      FLLeg.addChild(front_hoof_L_);
      FLLeg.addChild(front_hoof_top_L_);
      FLLeg.addChild(front_leg_L_flame);
      Body.addChild(FLLeg);
      
      
      PixelmonModelRenderer FRLeg = new PixelmonModelRenderer(this, "Front Right Leg");
      FRLeg.setRotationPoint(-4, 5.1F, -1.67F);
      PixelmonModelRenderer  front_leg_R_1 = new PixelmonModelRenderer(this, 116, 15);
      front_leg_R_1.addBox(-1F, -3F, -2F, 3, 6, 3);
      front_leg_R_1.setTextureSize(128, 64);
      front_leg_R_1.mirror = true;
      setRotation(front_leg_R_1, 0.0174533F, 0F, 0F);
      PixelmonModelRenderer  front_leg_R_2 = new PixelmonModelRenderer(this, 120, 25);
      front_leg_R_2.addBox(-0.7F, 2.533333F, -1.266667F, 2, 6, 2);
      front_leg_R_2.setTextureSize(128, 64);
      front_leg_R_2.mirror = true;
      setRotation(front_leg_R_2, -0.0523599F, 0F, 0F);
      PixelmonModelRenderer  front_hoof_R = new PixelmonModelRenderer(this, 120, 11);
      front_hoof_R.addBox(-0.8F, 8F, -2.2F, 2, 1, 2);
      front_hoof_R.setTextureSize(128, 64);
      front_hoof_R.mirror = true;
      setRotation(front_hoof_R, 0F, 0F, 0F);
      PixelmonModelRenderer  front_hoof_top_R = new PixelmonModelRenderer(this, 113, 11);
      front_hoof_top_R.addBox(-0.8F, 6.466667F, -5.066667F, 2, 1, 1);
      front_hoof_top_R.setTextureSize(128, 64);
      front_hoof_top_R.mirror = true;
      setRotation(front_hoof_top_R, 0.4014257F, 0F, 0F);
      PixelmonModelRenderer  front_leg_R_flame = new PixelmonModelRenderer(this, 0, 11);
      front_leg_R_flame.addBox(-1.5F, -3F, 0.3333333F, 1, 6, 4);
      front_leg_R_flame.setTextureSize(128, 64);
      front_leg_R_flame.mirror = true;
      setRotation(front_leg_R_flame, 0.0174533F, -0.1919862F, 0F);
      FRLeg.addChild(front_leg_R_1);
      FRLeg.addChild(front_leg_R_2);
      FRLeg.addChild(front_hoof_R);
      FRLeg.addChild(front_hoof_top_R);
      FRLeg.addChild(front_leg_R_flame);
      Body.addChild(FRLeg);
      
      
      
      PixelmonModelRenderer  neck_base = new PixelmonModelRenderer(this, 31, 55);
      neck_base.addBox(-3.5F, 1.2F, -0.4666667F, 7, 6, 3);
      neck_base.setTextureSize(128, 64);
      neck_base.mirror = true;
      setRotation(neck_base, -0.7679449F, 0F, 0F);
      PixelmonModelRenderer  neck_1 = new PixelmonModelRenderer(this, 31, 46);
      neck_1.addBox(-3F, 1.533333F, -0.4666667F, 6, 5, 3);
      neck_1.setTextureSize(128, 64);
      neck_1.mirror = true;
      setRotation(neck_1, -1.151917F, 0F, 0F);
      PixelmonModelRenderer  neck_2 = new PixelmonModelRenderer(this, 31, 34);
      neck_2.addBox(-2.5F, -5.266667F, -1.266667F, 5, 7, 4);
      neck_2.setRotationPoint(0F, 0F, -5F);
      neck_2.setTextureSize(128, 64);
      neck_2.mirror = true;
      setRotation(neck_2, 0.3316126F, 0F, 0F);
      Body.addChild(neck_base);
      Body.addChild(neck_1);
      Body.addChild(neck_2);
      
      
      
      PixelmonModelRenderer Head = new PixelmonModelRenderer(this, "Head");
      Head.setRotationPoint(0, -4.9F, -5);
      PixelmonModelRenderer  head = new PixelmonModelRenderer(this, 27, 0);
      head.addBox(-3F, -3F, -3F, 6, 5, 5);
      head.setTextureSize(128, 64);
      head.mirror = true;
      setRotation(head, 0.3839724F, 0F, 0F);
      PixelmonModelRenderer  snout_1 = new PixelmonModelRenderer(this, 50, 0);
      snout_1.addBox(-2F, -1.266667F, -6.2F, 4, 3, 5);
      snout_1.setTextureSize(128, 64);
      snout_1.mirror = true;
      setRotation(snout_1, 0.4712389F, 0F, 0F);
      PixelmonModelRenderer  snout_top = new PixelmonModelRenderer(this, 69, 0);
      snout_top.addBox(-2F, -3.2F, -5.266667F, 4, 1, 5);
      snout_top.setTextureSize(128, 64);
      snout_top.mirror = true;
      setRotation(snout_top, 0.8203047F, 0F, 0F);
      PixelmonModelRenderer  ear_L = new PixelmonModelRenderer(this, 0, 25);
      ear_L.addBox(0.9333333F, -3.4F, 1.7F, 1, 5, 5);
      ear_L.setTextureSize(128, 64);
      ear_L.mirror = true;
      setRotation(ear_L, 0.3839724F, 0.3839724F, 0.122173F);
      PixelmonModelRenderer  ear_R = new PixelmonModelRenderer(this, 13, 25);
      ear_R.addBox(-1.9F, -3.4F, 1.7F, 1, 5, 5);
      ear_R.setTextureSize(128, 64);
      ear_R.mirror = true;
      setRotation(ear_R, 0.3839724F, -0.3839724F, -0.122173F);
      PixelmonModelRenderer  head_flame_main = new PixelmonModelRenderer(this, 27, 26);
      head_flame_main.addBox(-2.5F, -5.666667F, -1.666667F, 5, 3, 4);
      head_flame_main.setTextureSize(128, 64);
      head_flame_main.mirror = true;
      setRotation(head_flame_main, 0.4886922F, 0F, 0F);
      PixelmonModelRenderer  head_flame_front = new PixelmonModelRenderer(this, 27, 21);
      head_flame_front.addBox(-2F, -5.133333F, -0.6F, 4, 2, 2);
      head_flame_front.setTextureSize(128, 64);
      head_flame_front.mirror = true;
      setRotation(head_flame_front, 1.029744F, 0F, 0F);
      PixelmonModelRenderer  head_flame_front_tip = new PixelmonModelRenderer(this, 27, 15);
      head_flame_front_tip.addBox(-2.8F, -4.466667F, -2.4F, 4, 1, 4);
      head_flame_front_tip.setTextureSize(128, 64);
      head_flame_front_tip.mirror = true;
      setRotation(head_flame_front_tip, 1.169371F, -0.3839724F, -0.1570796F);
      PixelmonModelRenderer  head_flame_back = new PixelmonModelRenderer(this, 44, 13);
      head_flame_back.addBox(-2F, -5.4F, -2.266667F, 4, 3, 2);
      head_flame_back.setTextureSize(128, 64);
      head_flame_back.mirror = true;
      setRotation(head_flame_back, -0.1919862F, 0F, 0F);
      PixelmonModelRenderer  head_flame_back_tip = new PixelmonModelRenderer(this, 58, 9);
      head_flame_back_tip.addBox(1.2F, -8.333333F, -0.4F, 1, 6, 6);
      head_flame_back_tip.setTextureSize(128, 64);
      head_flame_back_tip.mirror = true;
      setRotation(head_flame_back_tip, 0.2617994F, 0.6108652F, -0.5759587F);
      PixelmonModelRenderer  tail_flame = new PixelmonModelRenderer(this, 78, 42);
      Head.addChild(head);
      Head.addChild(snout_1);
      Head.addChild(snout_top);
      Head.addChild(ear_L);
      Head.addChild(ear_R);
      Head.addChild(head_flame_main);
      Head.addChild(head_flame_front);
      Head.addChild(head_flame_front_tip);
      Head.addChild(head_flame_back);
      Head.addChild(head_flame_back_tip);
      Body.addChild(Head);
      
      
      
      tail_flame.addBox(-1F, -10F, -2F, 1, 10, 12);
      tail_flame.setRotationPoint(0F, 2.1F, 9F);
      tail_flame.setTextureSize(128, 64);
      tail_flame.mirror = true;
      setRotation(tail_flame, -0.2094395F, 0F, 0F);
      Body.addChild(tail_flame);
      
      ModuleHead headModule = new ModuleHead(Head);

		float legspeed = 0.8F;
		float legRotationLimit = 1.1F;

		ModuleLeg frontlegLModule = new ModuleLeg(FLLeg, EnumLeg.FrontLeft,
				EnumPhase.OutPhase, EnumRotation.x, legRotationLimit, legspeed);
		ModuleLeg frontlegRModule = new ModuleLeg(FRLeg, EnumLeg.FrontRight,
				EnumPhase.OutPhase, EnumRotation.x, legRotationLimit, legspeed);
		ModuleLeg backlegLModule = new ModuleLeg(BLLeg, EnumLeg.BackLeft,
				EnumPhase.OutPhase, EnumRotation.x, legRotationLimit, legspeed);
		ModuleLeg backlegRModule = new ModuleLeg(BRLeg, EnumLeg.BackRight,
				EnumPhase.OutPhase, EnumRotation.x, legRotationLimit, legspeed);
		ModuleTailBasic tailModule = new ModuleTailBasic(tail_flame, .2F, .05F, legspeed);

		skeleton = new SkeletonQuadruped(Body, headModule, frontlegLModule,
				frontlegRModule, backlegLModule, backlegRModule, tailModule);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Body.render(f5);
  }
  
  private void setRotation(PixelmonModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
  }

}
