// Date: 4/23/2013 4:55:38 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package pixelmon.client.models.pokemon;


import pixelmon.client.models.PixelmonModelRenderer;
import net.minecraft.entity.Entity;
import pixelmon.client.models.PixelmonModelBase;
import pixelmon.client.models.animations.SkeletonBase;

public class ModelExeggcute extends PixelmonModelBase
{
  //fields
    PixelmonModelRenderer Body;
    
    
  public ModelExeggcute()
  {
    textureWidth = 128;
    textureHeight = 128;
    
    
      Body = new PixelmonModelRenderer(this, "Body");
      Body.setRotationPoint(0, 20, 0);
      PixelmonModelRenderer yolk1 = new PixelmonModelRenderer(this, 4, 73);
      yolk1.addBox(0F, 0F, 0F, 6, 5, 4);
      yolk1.setRotationPoint(-7.5F, -2.5F, 4.5F);
      yolk1.setTextureSize(128, 128);
      yolk1.mirror = true;
      setRotation(yolk1, -0.0872665F, 0F, 0F);
      PixelmonModelRenderer yolk2 = new PixelmonModelRenderer(this, 8, 73);
      yolk2.addBox(0F, 0F, 0F, 5, 7, 5);
      yolk2.setRotationPoint(-7F, -3F, 4F);
      yolk2.setTextureSize(128, 128);
      yolk2.mirror = true;
      setRotation(yolk2, -0.0872665F, 0F, 0F);
      PixelmonModelRenderer yolk3 = new PixelmonModelRenderer(this, 28, 72);
      yolk3.addBox(0F, 0F, 0F, 7, 6, 3);
      yolk3.setRotationPoint(-8F, -3F, 5F);
      yolk3.setTextureSize(128, 128);
      yolk3.mirror = true;
      setRotation(yolk3, -0.0872665F, 0F, 0F);
      PixelmonModelRenderer yolk4 = new PixelmonModelRenderer(this, 0, 72);
      yolk4.addBox(0F, 0F, 0F, 5, 6, 6);
      yolk4.setRotationPoint(-6.5F, -2.5F, 3.5F);
      yolk4.setTextureSize(128, 128);
      yolk4.mirror = true;
      setRotation(yolk4, -0.0872665F, 0F, 0F);
      PixelmonModelRenderer yolk5 = new PixelmonModelRenderer(this, 0, 0);
      yolk5.addBox(0F, 0F, 0F, 4, 1, 1);
      yolk5.setRotationPoint(-6.5F, -4F, 4F);
      yolk5.setTextureSize(128, 128);
      yolk5.mirror = true;
      setRotation(yolk5, -0.0872665F, 0F, 0F);
      PixelmonModelRenderer yolk6 = new PixelmonModelRenderer(this, 0, 0);
      yolk6.addBox(0F, 0F, 0F, 4, 1, 1);
      yolk6.setRotationPoint(-6.5F, -3.7F, 8F);
      yolk6.setTextureSize(128, 128);
      yolk6.mirror = true;
      setRotation(yolk6, -0.0872665F, 0F, 0F);
      PixelmonModelRenderer yolk7 = new PixelmonModelRenderer(this, 0, 0);
      yolk7.addBox(0F, 0F, 0F, 1, 1, 3);
      yolk7.setRotationPoint(-7F, -4F, 5F);
      yolk7.setTextureSize(128, 128);
      yolk7.mirror = true;
      setRotation(yolk7, -0.0872665F, 0F, 0F);
      PixelmonModelRenderer yolk8 = new PixelmonModelRenderer(this, 0, 0);
      yolk8.addBox(0F, 0F, 0F, 1, 1, 3);
      yolk8.setRotationPoint(-3F, -4, 5F);
      yolk8.setTextureSize(128, 128);
      yolk8.mirror = true;
      setRotation(yolk8, -0.0872665F, 0F, 0F);
      PixelmonModelRenderer yolk9 = new PixelmonModelRenderer(this, 24, 0);
      yolk9.addBox(0F, 0F, 0F, 1, 1, 1);
      yolk9.setRotationPoint(-5F, -4F, 6F);
      yolk9.setTextureSize(128, 128);
      yolk9.mirror = true;
      setRotation(yolk9, -0.0872665F, 0F, 0F);
      PixelmonModelRenderer yolk10 = new PixelmonModelRenderer(this, 24, 0);
      yolk10.addBox(0F, 0F, 0F, 1, 1, 1);
      yolk10.setRotationPoint(-5F, -5F, 6F);
      yolk10.setTextureSize(128, 128);
      yolk10.mirror = true;
      setRotation(yolk10, -0.0872665F, 0F, 0F);
      PixelmonModelRenderer yolk11 = new PixelmonModelRenderer(this, 24, 0);
      yolk11.addBox(0F, 0F, 0F, 1, 1, 3);
      yolk11.setRotationPoint(-4F, -4F, 5F);
      yolk11.setTextureSize(128, 128);
      yolk11.mirror = true;
      setRotation(yolk11, -0.0872665F, 0F, 0F);
      PixelmonModelRenderer yolk12 = new PixelmonModelRenderer(this, 24, 0);
      yolk12.addBox(0F, 0F, 0F, 1, 1, 1);
      yolk12.setRotationPoint(-5F, -4F, 5F);
      yolk12.setTextureSize(128, 128);
      yolk12.mirror = true;
      setRotation(yolk12, -0.0872665F, 0F, 0F);
      PixelmonModelRenderer yolk13 = new PixelmonModelRenderer(this, 24, 0);
      yolk13.addBox(0F, 0F, 0F, 1, 1, 1);
      yolk13.setRotationPoint(-5F, -3.8F, 7F);
      yolk13.setTextureSize(128, 128);
      yolk13.mirror = true;
      setRotation(yolk13, -0.0872665F, 0F, 0F);
      PixelmonModelRenderer yolk14 = new PixelmonModelRenderer(this, 24, 0);
      yolk14.addBox(0F, 0F, 0F, 1, 1, 3);
      yolk14.setRotationPoint(-6F, -4F, 5F);
      yolk14.setTextureSize(128, 128);
      yolk14.mirror = true;
      setRotation(yolk14, -0.0872665F, 0F, 0F);
      PixelmonModelRenderer yolk15 = new PixelmonModelRenderer(this, 0, 0);
      yolk15.addBox(0F, 0F, 0F, 4, 1, 1);
      yolk15.setRotationPoint(-6.5F, -3.7F, 8F);
      yolk15.setTextureSize(128, 128);
      yolk15.mirror = true;
      setRotation(yolk15, -0.0872665F, 0F, 0F);
      PixelmonModelRenderer yolk16 = new PixelmonModelRenderer(this, 24, 0);
      yolk16.addBox(0F, 0F, 0F, 2, 1, 2);
      yolk16.setRotationPoint(-5.5F, -4.5F, 5.5F);
      yolk16.setTextureSize(128, 128);
      yolk16.mirror = true;
      setRotation(yolk16, -0.0872665F, 0F, 0F);
      
      
      
      
      PixelmonModelRenderer fester1 = new PixelmonModelRenderer(this, 20, 37);
      fester1.addBox(0F, 0F, 0F, 7, 6, 3);
      fester1.setRotationPoint(2F, -4.5F, 6F);
      fester1.setTextureSize(128, 128);
      fester1.mirror = true;
      setRotation(fester1, -0.2185338F, -0.0872665F, 0F);
      PixelmonModelRenderer fester2 = new PixelmonModelRenderer(this, 20, 35);
      fester2.addBox(0F, 0F, 0F, 6, 7, 4);
      fester2.setRotationPoint(2.5F, -5F, 5.5F);
      fester2.setTextureSize(128, 128);
      fester2.mirror = true;
      setRotation(fester2, -0.2185338F, -0.0872665F, 0F);
      PixelmonModelRenderer fester3 = new PixelmonModelRenderer(this, 20, 33);
      fester3.addBox(0F, 0F, 0F, 5, 8, 5);
      fester3.setRotationPoint(3F, -5.5F, 5F);
      fester3.setTextureSize(128, 128);
      fester3.mirror = true;
      setRotation(fester3, -0.2185276F, -0.0872704F, 0F);
      PixelmonModelRenderer fester4 = new PixelmonModelRenderer(this, 0, 20);
      fester4.addBox(0F, 0F, 0F, 4, 7, 6);
      fester4.setRotationPoint(3.5F, -5F, 4.5F);
      fester4.setTextureSize(128, 128);
      fester4.mirror = true;
      setRotation(fester4, -0.2185338F, -0.0872665F, 0F);
      
      
      
      
      PixelmonModelRenderer gary1 = new PixelmonModelRenderer(this, 20, 35);
      gary1.addBox(0F, 0F, 0F, 6, 7, 4);
      gary1.setRotationPoint(3.5F, -3.5F, -8.5F);
      gary1.setTextureSize(128, 128);
      gary1.mirror = true;
      setRotation(gary1, 0F, 0F, 0.1593517F);
      PixelmonModelRenderer gary2 = new PixelmonModelRenderer(this, 0, 46);
      gary2.addBox(0F, 0F, 0F, 4, 7, 6);
      gary2.setRotationPoint(4.5F, -3.5F, -9.5F);
      gary2.setTextureSize(128, 128);
      gary2.mirror = true;
      setRotation(gary2, 0F, 0F, 0.1593517F);
      PixelmonModelRenderer gary3 = new PixelmonModelRenderer(this, 20, 37);
      gary3.addBox(0F, 0F, 0F, 7, 6, 3);
      gary3.setRotationPoint(3F, -3F, -8F);
      gary3.setTextureSize(128, 128);
      gary3.mirror = true;
      setRotation(gary3, 0F, 0F, 0.1593517F);
      PixelmonModelRenderer gary4 = new PixelmonModelRenderer(this, 20, 33);
      gary4.addBox(0F, 0F, 0F, 5, 8, 5);
      gary4.setRotationPoint(4F, -4F, -9F);
      gary4.setTextureSize(128, 128);
      gary4.mirror = true;
      setRotation(gary4, 0F, 0F, 0.1593517F);
      
      
      
      
      PixelmonModelRenderer  madeline1 = new PixelmonModelRenderer(this, 17, 37);
      madeline1.addBox(0F, 0F, 0F, 7, 6, 3);
      madeline1.setRotationPoint(-11F,-3F, -5F);
      madeline1.setTextureSize(128, 128);
      madeline1.mirror = true;
      setRotation(madeline1, 0F, 0.2382529F, 0F);
      PixelmonModelRenderer madeline2 = new PixelmonModelRenderer(this, 18, 35);
      madeline2.addBox(0F, 0F, 0F, 6, 7, 4);
      madeline2.setRotationPoint(-10.5F, -3.5F, -5.5F);
      madeline2.setTextureSize(128, 128);
      madeline2.mirror = true;
      setRotation(madeline2, 0F, 0.2382529F, 0F);
      PixelmonModelRenderer  madeline3 = new PixelmonModelRenderer(this, 20, 33);
      madeline3.addBox(0F, 0F, 0F, 5, 8, 5);
      madeline3.setRotationPoint(-10F, -4, -6F);
      madeline3.setTextureSize(128, 128);
      madeline3.mirror = true;
      setRotation(madeline3, 0F, 0.2382529F, 0F);
      PixelmonModelRenderer  madeline4 = new PixelmonModelRenderer(this, 0, 33);
      madeline4.addBox(0F, 0F, 0F, 4, 7, 6);
      madeline4.setRotationPoint(-9.5F, -3.5F, -6.5F);
      madeline4.setTextureSize(128, 128);
      madeline4.mirror = true;
      setRotation(madeline4, 0F, 0.2382529F, 0F);
      
      
      
      
      PixelmonModelRenderer ein = new PixelmonModelRenderer(this, 20, 35);
      ein.addBox(0F, 0F, 0F, 6, 7, 4);
      ein.setRotationPoint(-3F, -3.5F, -1.5F);
      ein.setTextureSize(128, 128);
      ein.mirror = true;
      setRotation(ein, -0.0872665F, 0F, 0F);
      PixelmonModelRenderer one = new PixelmonModelRenderer(this, 0, 59);
      one.addBox(-2F, -3.5F, -3F, 4, 7, 6);
      one.setTextureSize(128, 128);
      one.mirror = true;
      setRotation(one, -0.0872665F, 0F, 0F);
      PixelmonModelRenderer  uno = new PixelmonModelRenderer(this, 20, 37);
      uno.addBox(0F, 0F, 0F, 7, 6, 3);
      uno.setRotationPoint(-3.5F, -3F, -1F);
      uno.setTextureSize(128, 128);
      uno.mirror = true;
      setRotation(uno, -0.0872665F, 0F, 0F);
      PixelmonModelRenderer une = new PixelmonModelRenderer(this, 20, 31);
      une.addBox(0F, 0F, 0F, 5, 8, 5);
      une.setRotationPoint(-2.5F, -4F, -2F);
      une.setTextureSize(128, 128);
      une.mirror = true;
      setRotation(une, -0.0872665F, 0F, 0F);
      
      
      
      
      PixelmonModelRenderer bob1 = new PixelmonModelRenderer(this, 20, 35);
      bob1.addBox(0F, 0F, 0F, 6, 7, 4);
      bob1.setRotationPoint(7.3F, -3.5F, -3.5F);
      bob1.setTextureSize(128, 128);
      bob1.mirror = true;
      setRotation(bob1, 0F, -0.480327F, -0.1312612F);
      PixelmonModelRenderer bob2 = new PixelmonModelRenderer(this, 0, 33);
      bob2.addBox(0F, 0F, 0F, 4, 7, 6);
      bob2.setRotationPoint(8.5F, -3.5F, -4.5F);
      bob2.setTextureSize(128, 128);
      bob2.mirror = true;
      setRotation(bob2, 0F, -0.480327F, -0.1312612F);
      PixelmonModelRenderer  bob3 = new PixelmonModelRenderer(this, 20, 33);
      bob3.addBox(0F, 0F, 0F, 5, 8, 5);
      bob3.setRotationPoint(8F, -4F, -4F);
      bob3.setTextureSize(128, 128);
      bob3.mirror = true;
      setRotation(bob3, 0F, -0.480327F, -0.1312612F);
      PixelmonModelRenderer bob4 = new PixelmonModelRenderer(this, 20, 37);
      bob4.addBox(0F, 0F, 0F, 7, 6, 3);
      bob4.setRotationPoint(6.7F, -3F, -3F);
      bob4.setTextureSize(128, 128);
      bob4.mirror = true;
      setRotation(bob4, 0F, -0.480327F, -0.1312612F);
      
      
      Body.addChild(yolk1);
      Body.addChild(yolk2);
      Body.addChild(yolk3);
      Body.addChild(yolk4);
      Body.addChild(yolk5);
      Body.addChild(yolk6);
      Body.addChild(yolk7);
      Body.addChild(yolk8);
      Body.addChild(yolk9);
      Body.addChild(yolk10);
      Body.addChild(yolk11);
      Body.addChild(yolk12);
      Body.addChild(yolk13);
      Body.addChild(yolk14);
      Body.addChild(yolk15);
      Body.addChild(yolk16);
      Body.addChild(fester1);
      Body.addChild(fester2);
      Body.addChild(fester3);
      Body.addChild(fester4);
      Body.addChild(gary1);
      Body.addChild(gary2);
      Body.addChild(gary3);
      Body.addChild(gary4);
      Body.addChild(madeline1);
      Body.addChild(madeline2);
      Body.addChild(madeline3);
      Body.addChild(madeline4);
      Body.addChild(ein);
      Body.addChild(one);
      Body.addChild(uno);
      Body.addChild(une);
      Body.addChild(bob1);
      Body.addChild(bob2);
      Body.addChild(bob3);
      Body.addChild(bob4);
      
      
      skeleton = new SkeletonBase(Body);
      
      
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Body.render(f5);
  }
  
  private void setRotation(PixelmonModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
  }

}
