// Date: 8/4/2012 11:04:10 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package pixelmon.models.pokemon;

import net.minecraft.src.Entity;
import net.minecraft.src.ModelBase;
import net.minecraft.src.ModelRenderer;

public class ModelPrimeape extends ModelBase
{
  //fields
	ModelRenderer Main_body;
	ModelRenderer PRIMEAPE;
    ModelRenderer Llb1;
    ModelRenderer Llb2;
    ModelRenderer Llb3;
    ModelRenderer lc1;
    ModelRenderer lc2;
    ModelRenderer lc3;
    ModelRenderer Left_shackle;
    ModelRenderer lf1;
    ModelRenderer lf2;
    ModelRenderer lf3;
    ModelRenderer lf4;
    ModelRenderer Rlb_1;
    ModelRenderer Rlb_2;
    ModelRenderer Rlb_3;
    ModelRenderer rc1;
    ModelRenderer rc2;
    ModelRenderer rc3;
    ModelRenderer rls;
    ModelRenderer rf1;
    ModelRenderer rf2;
    ModelRenderer rf3;
    ModelRenderer rf4;
    ModelRenderer Main_body_middle;
    ModelRenderer MBVM;
    ModelRenderer MBFM;
    ModelRenderer MBHM;
    ModelRenderer nose;
    ModelRenderer Right_eyebrow;
    ModelRenderer Left_eyebrow;
    ModelRenderer re_right_edge;
    ModelRenderer re_left_edge;
    ModelRenderer Rec_1;
    ModelRenderer Rec_2;
    ModelRenderer Rec_3;
    ModelRenderer Lamm;
    ModelRenderer Lavm;
    ModelRenderer Lahm;
    ModelRenderer lf_1;
    ModelRenderer lf_2;
    ModelRenderer lf_3;
    ModelRenderer lf_4;
    ModelRenderer lf_5;
    ModelRenderer Lawmm;
    ModelRenderer Lawvm;
    ModelRenderer Lawhm;
    ModelRenderer Left_Shackle;
    ModelRenderer Ramm;
    ModelRenderer Ravm;
    ModelRenderer Rahm;
    ModelRenderer rf_5;
    ModelRenderer rf_4;
    ModelRenderer rf_3;
    ModelRenderer rf_2;
    ModelRenderer rf_1;
    ModelRenderer Rawfm;
    ModelRenderer Rawvm;
    ModelRenderer Rawhm;
    ModelRenderer Right_shackle;
    ModelRenderer le_right_edge;
    ModelRenderer le_left_edge;
    ModelRenderer Lec_1;
    ModelRenderer Lec_2;
    ModelRenderer Lec_3;
    ModelRenderer LEFT_EAR;
    ModelRenderer LEFT_LEG;
    ModelRenderer RIGHT_LEG;
    ModelRenderer RIGHT_ARM_WRIST;
    ModelRenderer LEFT_ARM_WRIST;
    ModelRenderer LEFT_ARM;
    ModelRenderer RIGHT_ARM;
    ModelRenderer LEFT_CALF;
    ModelRenderer RIGHT_CALF;
    ModelRenderer RIGHT_EAR;
    
    
    
    
    
    
    
  
  public ModelPrimeape()
  {
    textureWidth = 512;
    textureHeight = 256;
    setTextureOffset("PRIMEAPE.DELETE", 0, 0);
    
    PRIMEAPE = new ModelRenderer(this, "PRIMEAPE");
    PRIMEAPE.setRotationPoint(0F, 0F, 0F);
    setRotation(PRIMEAPE, 0F, 0F, 0F);
    PRIMEAPE.mirror = true;
   
      Llb1 = new ModelRenderer(this, 0, 100);
      Llb1.addBox(-4.5F, -8F, 23F, 4, 8, 4);
      Llb1.setRotationPoint(-7F, -12F, 0F);
      Llb1.setTextureSize(512, 256);
      Llb1.mirror = true;
      setRotation(Llb1, -0.6108652F, -0.8726646F, 0F);
      Llb2 = new ModelRenderer(this, 0, 100);
      Llb2.addBox(-5F, -7.5F, 23.5F, 5, 7, 3);
      Llb2.setRotationPoint(-7F, -12F, 0F);
      Llb2.setTextureSize(512, 256);
      Llb2.mirror = true;
      setRotation(Llb2, -0.6108652F, -0.8726646F, 0F);
      Llb3 = new ModelRenderer(this, 0, 100);
      Llb3.addBox(-4F, -8.5F, 22.5F, 3, 8, 5);
      Llb3.setRotationPoint(-7F, -12F, 0F);
      Llb3.setTextureSize(512, 256);
      Llb3.mirror = true;
      setRotation(Llb3, -0.6108652F, -0.8726646F, 0F);
  
      lc1 = new ModelRenderer(this, 0, 100);
      lc1.addBox(-5.5F, -1F, -8F, 3, 8, 3);
      lc1.setRotationPoint(-8.5F, -15.7F, 1.5F);
      lc1.setTextureSize(512, 256);
      lc1.mirror = true;
      setRotation(lc1, 0F, -0.8726646F, 0F);
      lc2 = new ModelRenderer(this, 0, 100);
      lc2.addBox(-5F, -0.5F, -8.5F, 2, 7, 4);
      lc2.setRotationPoint(-8.5F, -15.7F, 1.5F);
      lc2.setTextureSize(512, 256);
      lc2.mirror = true;
      setRotation(lc2, 0F, -0.8726646F, 0F);
      lc3 = new ModelRenderer(this, 0, 100);
      lc3.addBox(-6F, -0.5F, -7.5F, 4, 7, 2);
      lc3.setRotationPoint(-8.5F, -15.7F, 1.5F);
      lc3.setTextureSize(512, 256);
      lc3.mirror = true;
      setRotation(lc3, 0F, -0.8726646F, 0F);
      Left_shackle = new ModelRenderer(this, 0, 150);
      Left_shackle.addBox(-6.5F, 5.01F, -9F, 5, 2, 5);
      Left_shackle.setRotationPoint(-8.5F, -15.7F, 1.5F);
      Left_shackle.setTextureSize(512, 256);
      Left_shackle.mirror = true;
      setRotation(Left_shackle, 0F, -0.8726646F, 0F);
      lf1 = new ModelRenderer(this, 0, 100);
      lf1.addBox(-3.8F, 8F, -11F, 2, 2, 2);
      lf1.setRotationPoint(-8.5F, -15.7F, 1.5F);
      lf1.setTextureSize(512, 256);
      lf1.mirror = true;
      setRotation(lf1, 0F, -0.8726646F, 0F);
      lf2 = new ModelRenderer(this, 0, 100);
      lf2.addBox(-6F, 8F, -9.5F, 4, 2, 3);
      lf2.setRotationPoint(-8.5F, -15.7F, 1.5F);
      lf2.setTextureSize(512, 256);
      lf2.mirror = true;
      setRotation(lf2, 0F, -0.8726646F, 0F);
      lf3 = new ModelRenderer(this, 0, 100);
      lf3.addBox(-5.5F, 7F, -8F, 3, 3, 3);
      lf3.setRotationPoint(-8.5F, -15.7F, 1.5F);
      lf3.setTextureSize(512, 256);
      lf3.mirror = true;
      setRotation(lf3, 0F, -0.8726646F, 0F);
      lf4 = new ModelRenderer(this, 0, 100);
      lf4.addBox(-6.2F, 8F, -11F, 2, 2, 2);
      lf4.setRotationPoint(-8.5F, -15.7F, 1.5F);
      lf4.setTextureSize(512, 256);
      lf4.mirror = true;
      setRotation(lf4, 0F, -0.8726646F, 0F);
      
    
      Rlb_1 = new ModelRenderer(this, 0, 100);
      Rlb_1.addBox(1F, -8F, 23F, 4, 8, 4);
      Rlb_1.setRotationPoint(7F, -12F, 0F);
      Rlb_1.setTextureSize(512, 256);
      Rlb_1.mirror = true;
      setRotation(Rlb_1, -0.6108652F, 0.8726646F, 0F);
      Rlb_2 = new ModelRenderer(this, 0, 100);
      Rlb_2.addBox(0.5F, -7.5F, 23.5F, 5, 7, 3);
      Rlb_2.setRotationPoint(7F, -12F, 0F);
      Rlb_2.setTextureSize(512, 256);
      Rlb_2.mirror = true;
      setRotation(Rlb_2, -0.6108652F, 0.8726646F, 0F);
      Rlb_3 = new ModelRenderer(this, 0, 100);
      Rlb_3.addBox(1.5F, -8.5F, 22.5F, 3, 8, 5);
      Rlb_3.setRotationPoint(7F, -12F, 0F);
      Rlb_3.setTextureSize(512, 256);
      Rlb_3.mirror = true;
      setRotation(Rlb_3, -0.6108652F, 0.8726646F, 0F);
   
      rc1 = new ModelRenderer(this, 0, 100);
      rc1.addBox(3F, -1F, -7.5F, 3, 8, 3);
      rc1.setRotationPoint(8.5F, -15.7F, 2F);
      rc1.setTextureSize(512, 256);
      rc1.mirror = true;
      setRotation(rc1, 0F, 0.8726646F, 0F);
      rc2 = new ModelRenderer(this, 0, 100);
      rc2.addBox(3.5F, -0.5F, -8F, 2, 7, 4);
      rc2.setRotationPoint(8.5F, -15.7F, 2F);
      rc2.setTextureSize(512, 256);
      rc2.mirror = true;
      setRotation(rc2, 0F, 0.8726646F, 0F);
      rc3 = new ModelRenderer(this, 0, 100);
      rc3.addBox(2.5F, -0.5F, -7F, 4, 7, 2);
      rc3.setRotationPoint(8.5F, -15.7F, 2F);
      rc3.setTextureSize(512, 256);
      rc3.mirror = true;
      setRotation(rc3, 0F, 0.8726646F, 0F);
      rls = new ModelRenderer(this, 0, 150);
      rls.addBox(2F, 5.01F, -8.5F, 5, 2, 5);
      rls.setRotationPoint(8.5F, -15.7F, 2F);
      rls.setTextureSize(512, 256);
      rls.mirror = true;
      setRotation(rls, 0F, 0.8726646F, 0F);
      rf1 = new ModelRenderer(this, 0, 100);
      rf1.addBox(4.7F, 8F, -10.5F, 2, 2, 2);
      rf1.setRotationPoint(8.5F, -15.7F, 2F);
      rf1.setTextureSize(512, 256);
      rf1.mirror = true;
      setRotation(rf1, 0F, 0.8726646F, 0F);
      rf2 = new ModelRenderer(this, 0, 100);
      rf2.addBox(2.5F, 8F, -9F, 4, 2, 3);
      rf2.setRotationPoint(8.5F, -15.7F, 2F);
      rf2.setTextureSize(512, 256);
      rf2.mirror = true;
      setRotation(rf2, 0F, 0.8726646F, 0F);
      rf3 = new ModelRenderer(this, 0, 100);
      rf3.addBox(3F, 7F, -7.5F, 3, 3, 3);
      rf3.setRotationPoint(8.5F, -15.7F, 2F);
      rf3.setTextureSize(512, 256);
      rf3.mirror = true;
      setRotation(rf3, 0F, 0.8726646F, 0F);
      rf4 = new ModelRenderer(this, 0, 100);
      rf4.addBox(2.3F, 8F, -10.5F, 2, 2, 2);
      rf4.setRotationPoint(8.5F, -15.7F, 2F);
      rf4.setTextureSize(512, 256);
      rf4.mirror = true;
      setRotation(rf4, 0F, 0.8726646F, 0F);
      
  
      Main_body_middle = new ModelRenderer(this, 250, 0);
      Main_body_middle.addBox(-11F, -11F, -11F, 22, 22, 22);
      Main_body_middle.setRotationPoint(0F, 0F, 0F);
      Main_body_middle.setTextureSize(512, 256);
      Main_body_middle.mirror = true;
      setRotation(Main_body_middle, 0F, 0F, 0F);
      MBVM = new ModelRenderer(this, 250, 0);
      MBVM.addBox(-10F, -12F, -10F, 20, 24, 20);
      MBVM.setRotationPoint(0F, 0F, 0F);
      MBVM.setTextureSize(512, 256);
      MBVM.mirror = true;
      setRotation(MBVM, 0F, 0F, 0F);
      MBFM = new ModelRenderer(this, 250, 100);
      MBFM.addBox(-10F, -10F, -12F, 20, 20, 24);
      MBFM.setRotationPoint(0F, 0F, 0F);
      MBFM.setTextureSize(512, 256);
      MBFM.mirror = true;
      setRotation(MBFM, 0F, 0F, 0F);
      MBHM = new ModelRenderer(this, 250, 0);
      MBHM.addBox(-12F, -10F, -10F, 24, 20, 20);
      MBHM.setRotationPoint(0F, 0F, 0F);
      MBHM.setTextureSize(512, 256);
      MBHM.mirror = true;
      setRotation(MBHM, 0F, 0F, 0F);
      nose = new ModelRenderer(this, 0, 125);
      nose.addBox(-3F, -1F, -13F, 6, 3, 1);
      nose.setRotationPoint(0F, 0F, 0F);
      nose.setTextureSize(512, 256);
      nose.mirror = true;
      setRotation(nose, 0F, 0F, 0F);
      Right_eyebrow = new ModelRenderer(this, 290, 16);
      Right_eyebrow.addBox(7F, -8F, -12.5F, 7, 2, 1);
      Right_eyebrow.setRotationPoint(0F, 0F, 0F);
      Right_eyebrow.setTextureSize(512, 256);
      Right_eyebrow.mirror = true;
      setRotation(Right_eyebrow, 0F, 0F, 0.4363323F);
      Left_eyebrow = new ModelRenderer(this, 304, 12);
      Left_eyebrow.addBox(-14F, -8F, -12.5F, 7, 2, 1);
      Left_eyebrow.setRotationPoint(0F, 0F, 0F);
      Left_eyebrow.setTextureSize(512, 256);
      Left_eyebrow.mirror = true;
      setRotation(Left_eyebrow, 0F, 0F, -0.4363323F);
    
      re_right_edge = new ModelRenderer(this, 250, 0);
      re_right_edge.addBox(7F, -3.6F, -0.5F, 1, 6, 1);
      re_right_edge.setRotationPoint(6F, 12F, 0F);
      re_right_edge.setTextureSize(512, 256);
      re_right_edge.mirror = true;
      setRotation(re_right_edge, 0F, 0F, 0.3490659F);
  
      re_left_edge = new ModelRenderer(this, 250, 0);
      re_left_edge.addBox(-8F, -8F, -0.5F, 1, 6, 1);
      re_left_edge.setRotationPoint(6F, 12F, 0F);
      re_left_edge.setTextureSize(512, 256);
      re_left_edge.mirror = true;
      setRotation(re_left_edge, 0F, 0F, -0.3490659F);
      re_left_edge.mirror = false;
      Rec_1 = new ModelRenderer(this, 0, 200);
      Rec_1.addBox(-1F, -4F, 0F, 1, 6, 0);
      Rec_1.setRotationPoint(0F, 0F, 0F);
      Rec_1.setTextureSize(512, 256);
      Rec_1.mirror = true;
      setRotation(Rec_1, 0F, 0F, 0F);
      Rec_2 = new ModelRenderer(this, 0, 200);
      Rec_2.addBox(-2F, 0F, 0F, 3, 2, 0);
      Rec_2.setRotationPoint(0F, -2F, 0F);
      Rec_2.setTextureSize(512, 256);
      Rec_2.mirror = true;
      setRotation(Rec_2, 0F, 0F, 0F);
      Rec_3 = new ModelRenderer(this, 0, 200);
      Rec_3.addBox(0F, -5F, 0F, 2, 1, 0);
      Rec_3.setRotationPoint(-1.5F, 2F, 0F);
      Rec_3.setTextureSize(512, 256);
      Rec_3.mirror = true;
      setRotation(Rec_3, 0F, 0F, 0F);
     
   
      Lamm = new ModelRenderer(this, 0, 100);
      Lamm.addBox(18F, -22F, -2F, 14, 4, 4);
      Lamm.setRotationPoint(-12F, 2F, 0F);
      Lamm.setTextureSize(512, 256);
      Lamm.mirror = true;
      setRotation(Lamm, 0F, 0F, 0.7679449F);
      Lavm = new ModelRenderer(this, 0, 100);
      Lavm.addBox(17.5F, -22.5F, -1.5F, 14, 5, 3);
      Lavm.setRotationPoint(-12F, 2F, 0F);
      Lavm.setTextureSize(512, 256);
      Lavm.mirror = true;
      setRotation(Lavm, 0F, 0F, 0.7679449F);
      Lahm = new ModelRenderer(this, 0, 100);
      Lahm.addBox(18.5F, -21.5F, -2.5F, 13, 3, 5);
      Lahm.setRotationPoint(-12F, 2F, 0F);
      Lahm.setTextureSize(512, 256);
      Lahm.mirror = true;
      setRotation(Lahm, 0F, 0F, 0.7679449F);
   
      lf_1 = new ModelRenderer(this, 0, 100);
      lf_1.addBox(21F, -28F, -17F, 4, 4, 5);
      lf_1.setRotationPoint(-19F, -4F, 0F);
      lf_1.setTextureSize(512, 256);
      lf_1.mirror = true;
      setRotation(lf_1, 0F, 0F, 0.7679449F);
      lf_2 = new ModelRenderer(this, 0, 100);
      lf_2.addBox(23F, -31F, -19F, 6, 2, 6);
      lf_2.setRotationPoint(-19F, -4F, 0F);
      lf_2.setTextureSize(512, 256);
      lf_2.mirror = true;
      setRotation(lf_2, 0F, 0F, 0.7679449F);
      lf_3 = new ModelRenderer(this, 0, 100);
      lf_3.addBox(20F, -48F, -25.6F, 6, 2, 2);
      lf_3.setRotationPoint(-19F, -4F, 0F);
      lf_3.setTextureSize(512, 256);
      lf_3.mirror = true;
      setRotation(lf_3, 0.8726646F, 0F, 0.7679449F);
      lf_4 = new ModelRenderer(this, 0, 100);
      lf_4.addBox(20F, -26.7F, -20.3F, 6, 3, 2);
      lf_4.setRotationPoint(-19F, -4F, 0F);
      lf_4.setTextureSize(512, 256);
      lf_4.mirror = true;
      setRotation(lf_4, 0F, 0F, 0.7679449F);
      lf_5 = new ModelRenderer(this, 0, 100);
      lf_5.addBox(20.1F, -45.5F, -27F, 4, 2, 5);
      lf_5.setRotationPoint(-19F, -4F, 0F);
      lf_5.setTextureSize(512, 256);
      lf_5.mirror = true;
      setRotation(lf_5, 0.8726646F, 0F, 0.7679449F);
      Lawmm = new ModelRenderer(this, 0, 100);
      Lawmm.addBox(21F, -28F, -12F, 4, 4, 14);
      Lawmm.setRotationPoint(-19F, -4F, 0F);
      Lawmm.setTextureSize(512, 256);
      Lawmm.mirror = true;
      setRotation(Lawmm, 0F, 0F, 0.7679449F);
      Lawvm = new ModelRenderer(this, 0, 100);
      Lawvm.addBox(21.5F, -28.5F, -11.5F, 3, 5, 13);
      Lawvm.setRotationPoint(-19F, -4F, 0F);
      Lawvm.setTextureSize(512, 256);
      Lawvm.mirror = true;
      setRotation(Lawvm, 0F, 0F, 0.7679449F);
      Lawhm = new ModelRenderer(this, 0, 100);
      Lawhm.addBox(20.5F, -27.5F, -11.5F, 5, 3, 13);
      Lawhm.setRotationPoint(-19F, -4F, 0F);
      Lawhm.setTextureSize(512, 256);
      Lawhm.mirror = true;
      setRotation(Lawhm, 0F, 0F, 0.7679449F);
      Left_Shackle = new ModelRenderer(this, 0, 150);
      Left_Shackle.addBox(20F, -29F, -12.01F, 6, 6, 3);
      Left_Shackle.setRotationPoint(-19F, -4F, 0F);
      Left_Shackle.setTextureSize(512, 256);
      Left_Shackle.mirror = true;
      setRotation(Left_Shackle, 0F, 0F, 0.7679449F);
     
   
      Ramm = new ModelRenderer(this, 0, 100);
      Ramm.addBox(-32F, -22F, -2F, 14, 4, 4);
      Ramm.setRotationPoint(12F, 2F, 0F);
      Ramm.setTextureSize(512, 256);
      Ramm.mirror = true;
      setRotation(Ramm, 0F, 0F, -0.7679449F);
      Ravm = new ModelRenderer(this, 0, 100);
      Ravm.addBox(-31.5F, -22.5F, -1.5F, 14, 5, 3);
      Ravm.setRotationPoint(12F, 2F, 0F);
      Ravm.setTextureSize(512, 256);
      Ravm.mirror = true;
      setRotation(Ravm, 0F, 0F, -0.7679449F);
      Rahm = new ModelRenderer(this, 0, 100);
      Rahm.addBox(-31.5F, -21.5F, -2.5F, 13, 3, 5);
      Rahm.setRotationPoint(12F, 2F, 0F);
      Rahm.setTextureSize(512, 256);
      Rahm.mirror = true;
      setRotation(Rahm, 0F, 0F, -0.7679449F);
   
      rf_5 = new ModelRenderer(this, 0, 100);
      rf_5.addBox(-24F, -45.5F, -27F, 4, 2, 5);
      rf_5.setRotationPoint(19F, -4F, 0F);
      rf_5.setTextureSize(512, 256);
      rf_5.mirror = true;
      setRotation(rf_5, 0.8726646F, 0F, -0.7679449F);
      rf_4 = new ModelRenderer(this, 0, 100);
      rf_4.addBox(-26F, -26.5F, -20.3F, 6, 3, 2);
      rf_4.setRotationPoint(19F, -4F, 0F);
      rf_4.setTextureSize(512, 256);
      rf_4.mirror = true;
      setRotation(rf_4, 0F, 0F, -0.7679449F);
      rf_3 = new ModelRenderer(this, 0, 100);
      rf_3.addBox(-26F, -47.8F, -25.7F, 6, 2, 2);
      rf_3.setRotationPoint(19F, -4F, 0F);
      rf_3.setTextureSize(512, 256);
      rf_3.mirror = true;
      setRotation(rf_3, 0.8726646F, 0F, -0.7679449F);
      rf_2 = new ModelRenderer(this, 0, 100);
      rf_2.addBox(-26F, -28F, -19F, 6, 2, 6);
      rf_2.setRotationPoint(19F, -4F, 0F);
      rf_2.setTextureSize(512, 256);
      rf_2.mirror = true;
      setRotation(rf_2, 0F, 0F, -0.7679449F);
      rf_1 = new ModelRenderer(this, 0, 100);
      rf_1.addBox(-25F, -28.01F, -17F, 4, 4, 5);
      rf_1.setRotationPoint(19F, -4F, 0F);
      rf_1.setTextureSize(512, 256);
      rf_1.mirror = true;
      setRotation(rf_1, 0F, 0F, -0.7679449F);
      Rawfm = new ModelRenderer(this, 0, 100);
      Rawfm.addBox(-25F, -28F, -12F, 4, 4, 14);
      Rawfm.setRotationPoint(19F, -4F, 0F);
      Rawfm.setTextureSize(512, 256);
      Rawfm.mirror = true;
      setRotation(Rawfm, 0F, 0F, -0.7679449F);
      Rawvm = new ModelRenderer(this, 0, 100);
      Rawvm.addBox(-24.5F, -28.5F, -11.5F, 3, 5, 13);
      Rawvm.setRotationPoint(19F, -4F, 0F);
      Rawvm.setTextureSize(512, 256);
      Rawvm.mirror = true;
      setRotation(Rawvm, 0F, 0F, -0.7679449F);
      Rawhm = new ModelRenderer(this, 0, 100);
      Rawhm.addBox(-25.5F, -27.5F, -11.5F, 5, 3, 13);
      Rawhm.setRotationPoint(19F, -4F, 0F);
      Rawhm.setTextureSize(512, 256);
      Rawhm.mirror = true;
      setRotation(Rawhm, 0F, 0F, -0.7679449F);
      Right_shackle = new ModelRenderer(this, 0, 150);
      Right_shackle.addBox(-26F, -29F, -12.01F, 6, 6, 3);
      Right_shackle.setRotationPoint(19F, -4F, 0F);
      Right_shackle.setTextureSize(512, 256);
      Right_shackle.mirror = true;
      setRotation(Right_shackle, 0F, 0F, -0.7679449F);
     
   
      le_right_edge = new ModelRenderer(this, 250, 0);
      le_right_edge.addBox(6F, -7.6F, -0.5F, 1, 6, 1);
      le_right_edge.setRotationPoint(-6F, 12F, 0F);
      le_right_edge.setTextureSize(512, 256);
      le_right_edge.mirror = true;
      setRotation(le_right_edge, 0F, 0F, 0.3490659F);
      le_left_edge = new ModelRenderer(this, 250, 0);
      le_left_edge.addBox(-9F, -4F, -0.5F, 1, 6, 1);
      le_left_edge.setRotationPoint(-6F, 12F, 0F);
      le_left_edge.setTextureSize(512, 256);
      le_left_edge.mirror = true;
      setRotation(le_left_edge, 0F, 0F, -0.3490659F);
      Lec_1 = new ModelRenderer(this, 0, 200);
      Lec_1.addBox(-1F, -4F, 0F, 1, 6, 0);
      Lec_1.setRotationPoint(0F, 0F, 0F);
      Lec_1.setTextureSize(512, 256);
      Lec_1.mirror = true;
      setRotation(Lec_1, 0F, 0F, 0F);
      Lec_2 = new ModelRenderer(this, 0, 200);
      Lec_2.addBox(-2F, 0F, 0F, 3, 2, 0);
      Lec_2.setRotationPoint(0F, -2F, 0F);
      Lec_2.setTextureSize(512, 256);
      Lec_2.mirror = true;
      setRotation(Lec_2, 0F, 0F, 0F);
      Lec_3 = new ModelRenderer(this, 0, 200);
      Lec_3.addBox(0F, -5F, 0F, 2, 1, 0);
      Lec_3.setRotationPoint(-1.5F, 2F, 0F);
      Lec_3.setTextureSize(512, 256);
      Lec_3.mirror = true;
      setRotation(Lec_3, 0F, 0F, 0F);
      
      
      Main_body = new ModelRenderer(this, "Main_body");
      Main_body.setRotationPoint(0F, 0F, 0F);
      setRotation(Main_body, 0F, 0F, 0F);
      Main_body.mirror = true;
      
      LEFT_EAR = new ModelRenderer(this, "LEFT_EAR");
      LEFT_EAR.setRotationPoint(6F, -12F, 0F);
      setRotation(LEFT_EAR, 0F, 0F, 0F);
      LEFT_EAR.mirror = true;
      
      RIGHT_ARM_WRIST = new ModelRenderer(this, "RIGHT_ARM_WRIST");
      RIGHT_ARM_WRIST.setRotationPoint(-7F, 6F, 0F);
      setRotation(RIGHT_ARM_WRIST, 0F, 0F, 0F);
      RIGHT_ARM_WRIST.mirror = true;
      
      RIGHT_ARM = new ModelRenderer(this, "RIGHT_ARM");
      RIGHT_ARM.setRotationPoint(-12F, -2F, 0F);
      setRotation(RIGHT_ARM, 0F, 0F, 0F);
      RIGHT_ARM.mirror = true;
      
      LEFT_ARM = new ModelRenderer(this, "LEFT_ARM");
      LEFT_ARM.setRotationPoint(12F, -2F, 0F);
      setRotation(LEFT_ARM, 0F, 0F, 0F);
      LEFT_ARM.mirror = true;
     
      LEFT_ARM_WRIST = new ModelRenderer(this, "LEFT_ARM_WRIST");
      LEFT_ARM_WRIST.setRotationPoint(7F, 6F, 0F);
      setRotation(LEFT_ARM_WRIST, 0F, 0F, 0F);
      LEFT_ARM_WRIST.mirror = true;
      
      RIGHT_EAR = new ModelRenderer(this, "RIGHT_EAR");
      RIGHT_EAR.setRotationPoint(-6F, -12F, 0F);
      setRotation(RIGHT_EAR, 0F, 0F, 0F);
      RIGHT_EAR.mirror = true;
      
      RIGHT_CALF = new ModelRenderer(this, "RIGHT_CALF");
      RIGHT_CALF.setRotationPoint(-1.5F, 3.7F, -2F);
      setRotation(RIGHT_CALF, 0F, 0F, 0F);
      RIGHT_CALF.mirror = true;
      
      RIGHT_LEG = new ModelRenderer(this, "RIGHT_LEG");
      RIGHT_LEG.setRotationPoint(-7F, 12F, 0F);
      setRotation(RIGHT_LEG, 0F, 0F, 0F);
      RIGHT_LEG.mirror = true;
      
      LEFT_CALF = new ModelRenderer(this, "LEFT_CALF");
      LEFT_CALF.setRotationPoint(1.5F, 3.7F, -1.5F);
      setRotation(LEFT_CALF, 0F, 0F, 0F);
      LEFT_CALF.mirror = true;
      
      LEFT_LEG = new ModelRenderer(this, "LEFT_LEG");
      LEFT_LEG.setRotationPoint(7F, 12F, 0F);
      setRotation(LEFT_LEG, 0F, 0F, 0F);
      LEFT_LEG.mirror = true;
      
      
      
      PRIMEAPE.addChild(Main_body);
      PRIMEAPE.addChild(LEFT_LEG);
      PRIMEAPE.addChild(RIGHT_LEG);
      
      LEFT_LEG.addChild(LEFT_CALF);
      LEFT_LEG.addChild(Llb1);
      LEFT_LEG.addChild(Llb2);
      LEFT_LEG.addChild(Llb3);
      
      RIGHT_LEG.addChild(RIGHT_CALF);
      RIGHT_LEG.addChild(Rlb_1);
      RIGHT_LEG.addChild(Rlb_2);
      RIGHT_LEG.addChild(Rlb_3);
      
      Main_body.addChild(Main_body_middle);
      Main_body.addChild(MBVM);
      Main_body.addChild(MBFM);
      Main_body.addChild(MBHM);
      Main_body.addChild(nose);
      Main_body.addChild(Right_eyebrow);
      Main_body.addChild(Left_eyebrow);
      Main_body.addChild(RIGHT_EAR);
      Main_body.addChild(LEFT_EAR);
      Main_body.addChild(RIGHT_ARM);
      Main_body.addChild(LEFT_ARM);
     
      LEFT_CALF.addChild(lc1);
      LEFT_CALF.addChild(lc2);
      LEFT_CALF.addChild(lc3);
      LEFT_CALF.addChild(Left_shackle);
      LEFT_CALF.addChild(lf1);
      LEFT_CALF.addChild(lf2);
      LEFT_CALF.addChild(lf3);
      LEFT_CALF.addChild(lf4);
      
      RIGHT_CALF.addChild(rc1);
      RIGHT_CALF.addChild(rc2);
      RIGHT_CALF.addChild(rc3);
      RIGHT_CALF.addChild(rls);
      RIGHT_CALF.addChild(rf1);
      RIGHT_CALF.addChild(rf2);
      RIGHT_CALF.addChild(rf3);
      RIGHT_CALF.addChild(rf4);
      
      LEFT_ARM.addChild(Lamm);
      LEFT_ARM.addChild(Lavm);
      LEFT_ARM.addChild(Lahm);
      LEFT_ARM.addChild(LEFT_ARM_WRIST);
      
      RIGHT_ARM.addChild(Ramm);
      RIGHT_ARM.addChild(Ravm);
      RIGHT_ARM.addChild(Rahm);
      RIGHT_ARM.addChild(RIGHT_ARM_WRIST);
      
      RIGHT_EAR.addChild(Rec_1);
      RIGHT_EAR.addChild(Rec_2);
      RIGHT_EAR.addChild(Rec_3);
      RIGHT_EAR.addChild(re_right_edge);
      RIGHT_EAR.addChild(re_left_edge);
      
      LEFT_EAR.addChild(Lec_1);
      LEFT_EAR.addChild(Lec_2);
      LEFT_EAR.addChild(Lec_3);
      LEFT_EAR.addChild(le_left_edge);
      LEFT_EAR.addChild(le_right_edge);
      
      LEFT_ARM_WRIST.addChild(lf_1);
      LEFT_ARM_WRIST.addChild(lf_2);
      LEFT_ARM_WRIST.addChild(lf_3);
      LEFT_ARM_WRIST.addChild(lf_4);
      LEFT_ARM_WRIST.addChild(lf_5);
      LEFT_ARM_WRIST.addChild(Lawmm);
      LEFT_ARM_WRIST.addChild(Lawvm);
      LEFT_ARM_WRIST.addChild(Lawhm);
      LEFT_ARM_WRIST.addChild(Left_Shackle);
      
      RIGHT_ARM_WRIST.addChild(rf_5);
      RIGHT_ARM_WRIST.addChild(rf_4);
      RIGHT_ARM_WRIST.addChild(rf_3);
      RIGHT_ARM_WRIST.addChild(rf_2);
      RIGHT_ARM_WRIST.addChild(rf_1);
      RIGHT_ARM_WRIST.addChild(Rawfm);
      RIGHT_ARM_WRIST.addChild(Rawvm);
      RIGHT_ARM_WRIST.addChild(Rawhm);
      RIGHT_ARM_WRIST.addChild(Right_shackle);
      
      
      
      
      
      
      
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    PRIMEAPE.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
